SCALE Job started on Thu 08/08/2019 13:10:56
With Host name node40
working directory /tmp/scale.ybb.57393
and process id 57393.
Input file named /home/ybb/SCALE_beta/MSRE/MSRE_beta_100/MSRE_beta_100.inp
and output file named /home/ybb/SCALE_beta/MSRE/MSRE_beta_100/MSRE_beta_100.out
##########################################################
***Created 2 infinite homogeneous cells from unreferenced mixtures.
>>> Loading SCALE Standard Composition Library from /scale/release/6.3b4/linux/data/scale.rev40.sclib
>>> Loading CE library /scale/release/6.3b4/linux/data/ce_v7.1_endf.xml
***Warning:  iterp value not set correctly from XSProc cell data!  Setting to default...
                          (This is expected if you are using the timetable block in TRITON.)
Loading      nuclide       li-6 @ 900K
Loading      nuclide       li-6 @ 1200K
Broadening   nuclide       li-6 @ 922.039K
Loading      nuclide       li-7 @ 900K
Loading      nuclide       li-7 @ 1200K
Broadening   nuclide       li-7 @ 922.039K
Loading      nuclide       be-9 @ 900K
Loading      nuclide       be-9 @ 1200K
Broadening   nuclide       be-9 @ 922.039K
Loading      nuclide       f-19 @ 900K
Loading      nuclide       f-19 @ 1200K
Broadening   nuclide       f-19 @ 922.039K
Loading      nuclide      zr-90 @ 900K
Loading      nuclide      zr-90 @ 1200K
Broadening   nuclide      zr-90 @ 922.039K
Loading      nuclide      zr-91 @ 900K
Loading      nuclide      zr-91 @ 1200K
Broadening   nuclide      zr-91 @ 922.039K
Loading      nuclide      zr-92 @ 900K
Loading      nuclide      zr-92 @ 1200K
Broadening   nuclide      zr-92 @ 922.039K
Loading      nuclide      zr-94 @ 900K
Loading      nuclide      zr-94 @ 1200K
Broadening   nuclide      zr-94 @ 922.039K
Loading      nuclide      zr-96 @ 900K
Loading      nuclide      zr-96 @ 1200K
Broadening   nuclide      zr-96 @ 922.039K
Loading      nuclide      u-235 @ 900K
Loading      nuclide      u-235 @ 1200K
Broadening   nuclide      u-235 @ 922.039K
Loading      nuclide      u-238 @ 900K
Loading      nuclide      u-238 @ 1200K
Broadening   nuclide      u-238 @ 922.039K
Loading      nuclide      u-234 @ 900K
Loading      nuclide      u-234 @ 1200K
Broadening   nuclide      u-234 @ 922.039K
Loading      nuclide      u-236 @ 900K
Loading      nuclide      u-236 @ 1200K
Broadening   nuclide      u-236 @ 922.039K
Loading      nuclide     np-237 @ 900K
Loading      nuclide     np-237 @ 1200K
Broadening   nuclide     np-237 @ 922.039K
Loading      nuclide     pu-238 @ 900K
Loading      nuclide     pu-238 @ 1200K
Broadening   nuclide     pu-238 @ 922.039K
Loading      nuclide     pu-239 @ 900K
Loading      nuclide     pu-239 @ 1200K
Broadening   nuclide     pu-239 @ 922.039K
Loading      nuclide     pu-240 @ 900K
Loading      nuclide     pu-240 @ 1200K
Broadening   nuclide     pu-240 @ 922.039K
Loading      nuclide     pu-241 @ 900K
Loading      nuclide     pu-241 @ 1200K
Broadening   nuclide     pu-241 @ 922.039K
Loading      nuclide     pu-242 @ 900K
Loading      nuclide     pu-242 @ 1200K
Broadening   nuclide     pu-242 @ 922.039K
Loading      nuclide     am-241 @ 900K
Loading      nuclide     am-241 @ 1200K
Broadening   nuclide     am-241 @ 922.039K
Loading      nuclide     am-242 @ 900K
Loading      nuclide     am-242 @ 1200K
Broadening   nuclide     am-242 @ 922.039K
Loading      nuclide     am-243 @ 900K
Loading      nuclide     am-243 @ 1200K
Broadening   nuclide     am-243 @ 922.039K
Loading      nuclide     cm-242 @ 900K
Loading      nuclide     cm-242 @ 1200K
Broadening   nuclide     cm-242 @ 922.039K
Loading      nuclide     cm-243 @ 900K
Loading      nuclide     cm-243 @ 1200K
Broadening   nuclide     cm-243 @ 922.039K
Loading      nuclide     cm-244 @ 900K
Loading      nuclide     cm-244 @ 1200K
Broadening   nuclide     cm-244 @ 922.039K
Loading      nuclide     xe-135 @ 900K
Loading      nuclide     xe-135 @ 1200K
Broadening   nuclide     xe-135 @ 922.039K
Loading      nuclide     cs-133 @ 900K
Loading      nuclide     cs-133 @ 1200K
Broadening   nuclide     cs-133 @ 922.039K
Loading      nuclide      nb-93 @ 900K
Loading      nuclide      nb-93 @ 1200K
Broadening   nuclide      nb-93 @ 922.039K
Loading      nuclide      mo-95 @ 900K
Loading      nuclide      mo-95 @ 1200K
Broadening   nuclide      mo-95 @ 922.039K
Loading      nuclide      tc-99 @ 900K
Loading      nuclide      tc-99 @ 1200K
Broadening   nuclide      tc-99 @ 922.039K
Loading      nuclide     ru-106 @ 900K
Loading      nuclide     ru-106 @ 1200K
Broadening   nuclide     ru-106 @ 922.039K
Loading      nuclide     rh-103 @ 900K
Loading      nuclide     rh-103 @ 1200K
Broadening   nuclide     rh-103 @ 922.039K
Loading      nuclide     rh-105 @ 900K
Loading      nuclide     rh-105 @ 1200K
Broadening   nuclide     rh-105 @ 922.039K
Loading      nuclide     sn-126 @ 900K
Loading      nuclide     sn-126 @ 1200K
Broadening   nuclide     sn-126 @ 922.039K
Loading      nuclide     xe-131 @ 900K
Loading      nuclide     xe-131 @ 1200K
Broadening   nuclide     xe-131 @ 922.039K
Loading      nuclide     cs-134 @ 900K
Loading      nuclide     cs-134 @ 1200K
Broadening   nuclide     cs-134 @ 922.039K
Loading      nuclide     cs-135 @ 900K
Loading      nuclide     cs-135 @ 1200K
Broadening   nuclide     cs-135 @ 922.039K
Loading      nuclide     cs-137 @ 900K
Loading      nuclide     cs-137 @ 1200K
Broadening   nuclide     cs-137 @ 922.039K
Loading      nuclide     ce-144 @ 900K
Loading      nuclide     ce-144 @ 1200K
Broadening   nuclide     ce-144 @ 922.039K
Loading      nuclide     pr-143 @ 900K
Loading      nuclide     pr-143 @ 1200K
Broadening   nuclide     pr-143 @ 922.039K
Loading      nuclide     nd-143 @ 900K
Loading      nuclide     nd-143 @ 1200K
Broadening   nuclide     nd-143 @ 922.039K
Loading      nuclide     nd-145 @ 900K
Loading      nuclide     nd-145 @ 1200K
Broadening   nuclide     nd-145 @ 922.039K
Loading      nuclide     nd-146 @ 900K
Loading      nuclide     nd-146 @ 1200K
Broadening   nuclide     nd-146 @ 922.039K
Loading      nuclide     nd-147 @ 900K
Loading      nuclide     nd-147 @ 1200K
Broadening   nuclide     nd-147 @ 922.039K
Loading      nuclide     nd-148 @ 900K
Loading      nuclide     nd-148 @ 1200K
Broadening   nuclide     nd-148 @ 922.039K
Loading      nuclide     pm-147 @ 900K
Loading      nuclide     pm-147 @ 1200K
Broadening   nuclide     pm-147 @ 922.039K
Loading      nuclide     pm-149 @ 900K
Loading      nuclide     pm-149 @ 1200K
Broadening   nuclide     pm-149 @ 922.039K
Loading      nuclide     sm-147 @ 900K
Loading      nuclide     sm-147 @ 1200K
Broadening   nuclide     sm-147 @ 922.039K
Loading      nuclide     sm-149 @ 900K
Loading      nuclide     sm-149 @ 1200K
Broadening   nuclide     sm-149 @ 922.039K
Loading      nuclide     sm-150 @ 900K
Loading      nuclide     sm-150 @ 1200K
Broadening   nuclide     sm-150 @ 922.039K
Loading      nuclide     sm-151 @ 900K
Loading      nuclide     sm-151 @ 1200K
Broadening   nuclide     sm-151 @ 922.039K
Loading      nuclide     sm-152 @ 900K
Loading      nuclide     sm-152 @ 1200K
Broadening   nuclide     sm-152 @ 922.039K
Loading      nuclide     eu-151 @ 900K
Loading      nuclide     eu-151 @ 1200K
Broadening   nuclide     eu-151 @ 922.039K
Loading      nuclide     eu-153 @ 900K
Loading      nuclide     eu-153 @ 1200K
Broadening   nuclide     eu-153 @ 922.039K
Loading      nuclide     eu-154 @ 900K
Loading      nuclide     eu-154 @ 1200K
Broadening   nuclide     eu-154 @ 922.039K
Loading      nuclide     eu-155 @ 900K
Loading      nuclide     eu-155 @ 1200K
Broadening   nuclide     eu-155 @ 922.039K
Loading      nuclide     gd-154 @ 900K
Loading      nuclide     gd-154 @ 1200K
Broadening   nuclide     gd-154 @ 922.039K
Loading      nuclide     gd-155 @ 900K
Loading      nuclide     gd-155 @ 1200K
Broadening   nuclide     gd-155 @ 922.039K
Loading      nuclide     gd-157 @ 900K
Loading      nuclide     gd-157 @ 1200K
Broadening   nuclide     gd-157 @ 922.039K
Loading      nuclide     gd-158 @ 900K
Loading      nuclide     gd-158 @ 1200K
Broadening   nuclide     gd-158 @ 922.039K
Loading      nuclide     gd-160 @ 900K
Loading      nuclide     gd-160 @ 1200K
Broadening   nuclide     gd-160 @ 922.039K
Loading      nuclide        h-1 @ 800K
Loading      nuclide       b-10 @ 900K
Loading      nuclide       b-10 @ 1200K
Broadening   nuclide       b-10 @ 922.039K
Loading      nuclide       b-11 @ 900K
Loading      nuclide       b-11 @ 1200K
Broadening   nuclide       b-11 @ 922.039K
Loading      nuclide       n-14 @ 900K
Loading      nuclide       n-14 @ 1200K
Broadening   nuclide       n-14 @ 922.039K
Loading      nuclide       o-16 @ 900K
Loading      nuclide       o-16 @ 1200K
Broadening   nuclide       o-16 @ 922.039K
Loading      nuclide      kr-83 @ 900K
Loading      nuclide      kr-83 @ 1200K
Broadening   nuclide      kr-83 @ 922.039K
Loading      nuclide     ag-109 @ 900K
Loading      nuclide     ag-109 @ 1200K
Broadening   nuclide     ag-109 @ 922.039K
Loading      nuclide      i-135 @ 900K
Loading      nuclide      i-135 @ 1200K
Broadening   nuclide      i-135 @ 922.039K
Loading      nuclide     pm-148 @ 900K
Loading      nuclide     pm-148 @ 1200K
Broadening   nuclide     pm-148 @ 922.039K
Loading      nuclide     gd-152 @ 900K
Loading      nuclide     gd-152 @ 1200K
Broadening   nuclide     gd-152 @ 922.039K
Loading      nuclide     gd-156 @ 900K
Loading      nuclide     gd-156 @ 1200K
Broadening   nuclide     gd-156 @ 922.039K
Loading      nuclide     xe-133 @ 900K
Loading      nuclide     xe-133 @ 1200K
Broadening   nuclide     xe-133 @ 922.039K
Loading      nuclide     cd-113 @ 900K
Loading      nuclide     cd-113 @ 1200K
Broadening   nuclide     cd-113 @ 922.039K
Loading      nuclide     ce-141 @ 900K
Loading      nuclide     ce-141 @ 1200K
Broadening   nuclide     ce-141 @ 922.039K
Loading      nuclide     ru-101 @ 900K
Loading      nuclide     ru-101 @ 1200K
Broadening   nuclide     ru-101 @ 922.039K
Loading      nuclide     sm-153 @ 900K
Loading      nuclide     sm-153 @ 1200K
Broadening   nuclide     sm-153 @ 922.039K
Loading      nuclide     ru-103 @ 900K
Loading      nuclide     ru-103 @ 1200K
Broadening   nuclide     ru-103 @ 922.039K
Loading      nuclide     la-139 @ 900K
Loading      nuclide     la-139 @ 1200K
Broadening   nuclide     la-139 @ 922.039K
Loading      nuclide     ce-143 @ 900K
Loading      nuclide     ce-143 @ 1200K
Broadening   nuclide     ce-143 @ 922.039K
Loading      nuclide      zr-93 @ 900K
Loading      nuclide      zr-93 @ 1200K
Broadening   nuclide      zr-93 @ 922.039K
Loading      nuclide      mo-99 @ 900K
Loading      nuclide      mo-99 @ 1200K
Broadening   nuclide      mo-99 @ 922.039K
Loading      nuclide      mo-97 @ 900K
Loading      nuclide      mo-97 @ 1200K
Broadening   nuclide      mo-97 @ 922.039K
Loading      nuclide      mo-98 @ 900K
Loading      nuclide      mo-98 @ 1200K
Broadening   nuclide      mo-98 @ 922.039K
Loading      nuclide     ba-140 @ 900K
Loading      nuclide     ba-140 @ 1200K
Broadening   nuclide     ba-140 @ 922.039K
Loading      nuclide      i-129 @ 900K
Loading      nuclide      i-129 @ 1200K
Broadening   nuclide      i-129 @ 922.039K
Loading      nuclide     pd-105 @ 900K
Loading      nuclide     pd-105 @ 1200K
Broadening   nuclide     pd-105 @ 922.039K
Loading      nuclide      zr-95 @ 900K
Loading      nuclide      zr-95 @ 1200K
Broadening   nuclide      zr-95 @ 922.039K
Loading      nuclide     pd-107 @ 900K
Loading      nuclide     pd-107 @ 1200K
Broadening   nuclide     pd-107 @ 922.039K
Loading      nuclide     pd-108 @ 900K
Loading      nuclide     pd-108 @ 1200K
Broadening   nuclide     pd-108 @ 922.039K
Loading      nuclide     pr-141 @ 900K
Loading      nuclide     pr-141 @ 1200K
Broadening   nuclide     pr-141 @ 922.039K
Loading      nuclide     in-115 @ 900K
Loading      nuclide     in-115 @ 1200K
Broadening   nuclide     in-115 @ 922.039K
Loading      nuclide     eu-156 @ 900K
Loading      nuclide     eu-156 @ 1200K
Broadening   nuclide     eu-156 @ 922.039K
Loading      nuclide     ru-102 @ 900K
Loading      nuclide     ru-102 @ 1200K
Broadening   nuclide     ru-102 @ 922.039K
Loading      nuclide     nd-144 @ 900K
Loading      nuclide     nd-144 @ 1200K
Broadening   nuclide     nd-144 @ 922.039K
Loading      nuclide      i-127 @ 900K
Loading      nuclide      i-127 @ 1200K
Broadening   nuclide      i-127 @ 922.039K
Loading      nuclide     mo-100 @ 900K
Loading      nuclide     mo-100 @ 1200K
Broadening   nuclide     mo-100 @ 922.039K
Loading      nuclide     ru-104 @ 900K
Loading      nuclide     ru-104 @ 1200K
Broadening   nuclide     ru-104 @ 922.039K
Loading      nuclide     ce-142 @ 900K
Loading      nuclide     ce-142 @ 1200K
Broadening   nuclide     ce-142 @ 922.039K
Loading      nuclide      nb-95 @ 900K
Loading      nuclide      nb-95 @ 1200K
Broadening   nuclide      nb-95 @ 922.039K
Loading      nuclide    am-242m @ 900K
Loading      nuclide    am-242m @ 1200K
Broadening   nuclide    am-242m @ 922.039K
Loading      nuclide      ge-72 @ 900K
Loading      nuclide      ge-72 @ 1200K
Broadening   nuclide      ge-72 @ 922.039K
Loading      nuclide     sb-124 @ 900K
Loading      nuclide     sb-124 @ 1200K
Broadening   nuclide     sb-124 @ 922.039K
Loading      nuclide      ge-73 @ 900K
Loading      nuclide      ge-73 @ 1200K
Broadening   nuclide      ge-73 @ 922.039K
Loading      nuclide     sb-125 @ 900K
Loading      nuclide     sb-125 @ 1200K
Broadening   nuclide     sb-125 @ 922.039K
Loading      nuclide      ge-74 @ 900K
Loading      nuclide      ge-74 @ 1200K
Broadening   nuclide      ge-74 @ 922.039K
Loading      nuclide     sb-126 @ 900K
Loading      nuclide     sb-126 @ 1200K
Broadening   nuclide     sb-126 @ 922.039K
Loading      nuclide     te-120 @ 900K
Loading      nuclide     te-120 @ 1200K
Broadening   nuclide     te-120 @ 922.039K
Loading      nuclide      ge-76 @ 900K
Loading      nuclide      ge-76 @ 1200K
Broadening   nuclide      ge-76 @ 922.039K
Loading      nuclide     te-122 @ 900K
Loading      nuclide     te-122 @ 1200K
Broadening   nuclide     te-122 @ 922.039K
Loading      nuclide      as-75 @ 900K
Loading      nuclide      as-75 @ 1200K
Broadening   nuclide      as-75 @ 922.039K
Loading      nuclide     te-123 @ 900K
Loading      nuclide     te-123 @ 1200K
Broadening   nuclide     te-123 @ 922.039K
Loading      nuclide      se-76 @ 900K
Loading      nuclide      se-76 @ 1200K
Broadening   nuclide      se-76 @ 922.039K
Loading      nuclide     te-124 @ 900K
Loading      nuclide     te-124 @ 1200K
Broadening   nuclide     te-124 @ 922.039K
Loading      nuclide      se-77 @ 900K
Loading      nuclide      se-77 @ 1200K
Broadening   nuclide      se-77 @ 922.039K
Loading      nuclide     te-125 @ 900K
Loading      nuclide     te-125 @ 1200K
Broadening   nuclide     te-125 @ 922.039K
Loading      nuclide      se-78 @ 900K
Loading      nuclide      se-78 @ 1200K
Broadening   nuclide      se-78 @ 922.039K
Loading      nuclide     te-126 @ 900K
Loading      nuclide     te-126 @ 1200K
Broadening   nuclide     te-126 @ 922.039K
Loading      nuclide      se-80 @ 900K
Loading      nuclide      se-80 @ 1200K
Broadening   nuclide      se-80 @ 922.039K
Loading      nuclide    te-127m @ 900K
Loading      nuclide    te-127m @ 1200K
Broadening   nuclide    te-127m @ 922.039K
Loading      nuclide      se-82 @ 900K
Loading      nuclide      se-82 @ 1200K
Broadening   nuclide      se-82 @ 922.039K
Loading      nuclide     te-128 @ 900K
Loading      nuclide     te-128 @ 1200K
Broadening   nuclide     te-128 @ 922.039K
Loading      nuclide      br-79 @ 900K
Loading      nuclide      br-79 @ 1200K
Broadening   nuclide      br-79 @ 922.039K
Loading      nuclide    te-129m @ 900K
Loading      nuclide    te-129m @ 1200K
Broadening   nuclide    te-129m @ 922.039K
Loading      nuclide      br-81 @ 900K
Loading      nuclide      br-81 @ 1200K
Broadening   nuclide      br-81 @ 922.039K
Loading      nuclide     te-130 @ 900K
Loading      nuclide     te-130 @ 1200K
Broadening   nuclide     te-130 @ 922.039K
Loading      nuclide      kr-80 @ 900K
Loading      nuclide      kr-80 @ 1200K
Broadening   nuclide      kr-80 @ 922.039K
Loading      nuclide     te-132 @ 900K
Loading      nuclide     te-132 @ 1200K
Broadening   nuclide     te-132 @ 922.039K
Loading      nuclide      kr-82 @ 900K
Loading      nuclide      kr-82 @ 1200K
Broadening   nuclide      kr-82 @ 922.039K
Loading      nuclide      kr-84 @ 900K
Loading      nuclide      kr-84 @ 1200K
Broadening   nuclide      kr-84 @ 922.039K
Loading      nuclide      i-130 @ 900K
Loading      nuclide      i-130 @ 1200K
Broadening   nuclide      i-130 @ 922.039K
Loading      nuclide      kr-85 @ 900K
Loading      nuclide      kr-85 @ 1200K
Broadening   nuclide      kr-85 @ 922.039K
Loading      nuclide      i-131 @ 900K
Loading      nuclide      i-131 @ 1200K
Broadening   nuclide      i-131 @ 922.039K
Loading      nuclide      kr-86 @ 900K
Loading      nuclide      kr-86 @ 1200K
Broadening   nuclide      kr-86 @ 922.039K
Loading      nuclide     xe-124 @ 900K
Loading      nuclide     xe-124 @ 1200K
Broadening   nuclide     xe-124 @ 922.039K
Loading      nuclide     xe-126 @ 900K
Loading      nuclide     xe-126 @ 1200K
Broadening   nuclide     xe-126 @ 922.039K
Loading      nuclide      rb-85 @ 900K
Loading      nuclide      rb-85 @ 1200K
Broadening   nuclide      rb-85 @ 922.039K
Loading      nuclide     xe-128 @ 900K
Loading      nuclide     xe-128 @ 1200K
Broadening   nuclide     xe-128 @ 922.039K
Loading      nuclide      rb-86 @ 900K
Loading      nuclide      rb-86 @ 1200K
Broadening   nuclide      rb-86 @ 922.039K
Loading      nuclide     xe-129 @ 900K
Loading      nuclide     xe-129 @ 1200K
Broadening   nuclide     xe-129 @ 922.039K
Loading      nuclide      rb-87 @ 900K
Loading      nuclide      rb-87 @ 1200K
Broadening   nuclide      rb-87 @ 922.039K
Loading      nuclide     xe-130 @ 900K
Loading      nuclide     xe-130 @ 1200K
Broadening   nuclide     xe-130 @ 922.039K
Loading      nuclide      sr-84 @ 900K
Loading      nuclide      sr-84 @ 1200K
Broadening   nuclide      sr-84 @ 922.039K
Loading      nuclide      sr-86 @ 900K
Loading      nuclide      sr-86 @ 1200K
Broadening   nuclide      sr-86 @ 922.039K
Loading      nuclide     xe-132 @ 900K
Loading      nuclide     xe-132 @ 1200K
Broadening   nuclide     xe-132 @ 922.039K
Loading      nuclide      sr-87 @ 900K
Loading      nuclide      sr-87 @ 1200K
Broadening   nuclide      sr-87 @ 922.039K
Loading      nuclide      sr-88 @ 900K
Loading      nuclide      sr-88 @ 1200K
Broadening   nuclide      sr-88 @ 922.039K
Loading      nuclide     xe-134 @ 900K
Loading      nuclide     xe-134 @ 1200K
Broadening   nuclide     xe-134 @ 922.039K
Loading      nuclide      sr-89 @ 900K
Loading      nuclide      sr-89 @ 1200K
Broadening   nuclide      sr-89 @ 922.039K
Loading      nuclide      sr-90 @ 900K
Loading      nuclide      sr-90 @ 1200K
Broadening   nuclide      sr-90 @ 922.039K
Loading      nuclide     xe-136 @ 900K
Loading      nuclide     xe-136 @ 1200K
Broadening   nuclide     xe-136 @ 922.039K
Loading      nuclide       y-89 @ 900K
Loading      nuclide       y-89 @ 1200K
Broadening   nuclide       y-89 @ 922.039K
Loading      nuclide       y-90 @ 900K
Loading      nuclide       y-90 @ 1200K
Broadening   nuclide       y-90 @ 922.039K
Loading      nuclide       y-91 @ 900K
Loading      nuclide       y-91 @ 1200K
Broadening   nuclide       y-91 @ 922.039K
Loading      nuclide     cs-136 @ 900K
Loading      nuclide     cs-136 @ 1200K
Broadening   nuclide     cs-136 @ 922.039K
Loading      nuclide     ba-134 @ 900K
Loading      nuclide     ba-134 @ 1200K
Broadening   nuclide     ba-134 @ 922.039K
Loading      nuclide     ba-135 @ 900K
Loading      nuclide     ba-135 @ 1200K
Broadening   nuclide     ba-135 @ 922.039K
Loading      nuclide     ba-136 @ 900K
Loading      nuclide     ba-136 @ 1200K
Broadening   nuclide     ba-136 @ 922.039K
Loading      nuclide     ba-137 @ 900K
Loading      nuclide     ba-137 @ 1200K
Broadening   nuclide     ba-137 @ 922.039K
Loading      nuclide     ba-138 @ 900K
Loading      nuclide     ba-138 @ 1200K
Broadening   nuclide     ba-138 @ 922.039K
Loading      nuclide      nb-94 @ 900K
Loading      nuclide      nb-94 @ 1200K
Broadening   nuclide      nb-94 @ 922.039K
Loading      nuclide     la-140 @ 900K
Loading      nuclide     la-140 @ 1200K
Broadening   nuclide     la-140 @ 922.039K
Loading      nuclide     ce-140 @ 900K
Loading      nuclide     ce-140 @ 1200K
Broadening   nuclide     ce-140 @ 922.039K
Loading      nuclide      mo-92 @ 900K
Loading      nuclide      mo-92 @ 1200K
Broadening   nuclide      mo-92 @ 922.039K
Loading      nuclide      mo-94 @ 900K
Loading      nuclide      mo-94 @ 1200K
Broadening   nuclide      mo-94 @ 922.039K
Loading      nuclide      mo-96 @ 900K
Loading      nuclide      mo-96 @ 1200K
Broadening   nuclide      mo-96 @ 922.039K
Loading      nuclide     pr-142 @ 900K
Loading      nuclide     pr-142 @ 1200K
Broadening   nuclide     pr-142 @ 922.039K
Loading      nuclide     nd-142 @ 900K
Loading      nuclide     nd-142 @ 1200K
Broadening   nuclide     nd-142 @ 922.039K
Loading      nuclide      ru-96 @ 900K
Loading      nuclide      ru-96 @ 1200K
Broadening   nuclide      ru-96 @ 922.039K
Loading      nuclide      ru-98 @ 900K
Loading      nuclide      ru-98 @ 1200K
Broadening   nuclide      ru-98 @ 922.039K
Loading      nuclide      ru-99 @ 900K
Loading      nuclide      ru-99 @ 1200K
Broadening   nuclide      ru-99 @ 922.039K
Loading      nuclide     ru-100 @ 900K
Loading      nuclide     ru-100 @ 1200K
Broadening   nuclide     ru-100 @ 922.039K
Loading      nuclide     ru-105 @ 900K
Loading      nuclide     ru-105 @ 1200K
Broadening   nuclide     ru-105 @ 922.039K
Loading      nuclide     nd-150 @ 900K
Loading      nuclide     nd-150 @ 1200K
Broadening   nuclide     nd-150 @ 922.039K
Loading      nuclide     pd-102 @ 900K
Loading      nuclide     pd-102 @ 1200K
Broadening   nuclide     pd-102 @ 922.039K
Loading      nuclide     pm-151 @ 900K
Loading      nuclide     pm-151 @ 1200K
Broadening   nuclide     pm-151 @ 922.039K
Loading      nuclide     pd-104 @ 900K
Loading      nuclide     pd-104 @ 1200K
Broadening   nuclide     pd-104 @ 922.039K
Loading      nuclide     sm-144 @ 900K
Loading      nuclide     sm-144 @ 1200K
Broadening   nuclide     sm-144 @ 922.039K
Loading      nuclide     pd-106 @ 900K
Loading      nuclide     pd-106 @ 1200K
Broadening   nuclide     pd-106 @ 922.039K
Loading      nuclide     sm-148 @ 900K
Loading      nuclide     sm-148 @ 1200K
Broadening   nuclide     sm-148 @ 922.039K
Loading      nuclide     pd-110 @ 900K
Loading      nuclide     pd-110 @ 1200K
Broadening   nuclide     pd-110 @ 922.039K
Loading      nuclide     ag-107 @ 900K
Loading      nuclide     ag-107 @ 1200K
Broadening   nuclide     ag-107 @ 922.039K
Loading      nuclide     ag-111 @ 900K
Loading      nuclide     ag-111 @ 1200K
Broadening   nuclide     ag-111 @ 922.039K
Loading      nuclide     sm-154 @ 900K
Loading      nuclide     sm-154 @ 1200K
Broadening   nuclide     sm-154 @ 922.039K
Loading      nuclide     cd-106 @ 900K
Loading      nuclide     cd-106 @ 1200K
Broadening   nuclide     cd-106 @ 922.039K
Loading      nuclide     cd-108 @ 900K
Loading      nuclide     cd-108 @ 1200K
Broadening   nuclide     cd-108 @ 922.039K
Loading      nuclide     eu-152 @ 900K
Loading      nuclide     eu-152 @ 1200K
Broadening   nuclide     eu-152 @ 922.039K
Loading      nuclide     cd-110 @ 900K
Loading      nuclide     cd-110 @ 1200K
Broadening   nuclide     cd-110 @ 922.039K
Loading      nuclide     cd-111 @ 900K
Loading      nuclide     cd-111 @ 1200K
Broadening   nuclide     cd-111 @ 922.039K
Loading      nuclide     cd-112 @ 900K
Loading      nuclide     cd-112 @ 1200K
Broadening   nuclide     cd-112 @ 922.039K
Loading      nuclide     cd-114 @ 900K
Loading      nuclide     cd-114 @ 1200K
Broadening   nuclide     cd-114 @ 922.039K
Loading      nuclide     eu-157 @ 900K
Loading      nuclide     eu-157 @ 1200K
Broadening   nuclide     eu-157 @ 922.039K
Loading      nuclide    cd-115m @ 900K
Loading      nuclide    cd-115m @ 1200K
Broadening   nuclide    cd-115m @ 922.039K
Loading      nuclide     cd-116 @ 900K
Loading      nuclide     cd-116 @ 1200K
Broadening   nuclide     cd-116 @ 922.039K
Loading      nuclide     in-113 @ 900K
Loading      nuclide     in-113 @ 1200K
Broadening   nuclide     in-113 @ 922.039K
Loading      nuclide     sn-112 @ 900K
Loading      nuclide     sn-112 @ 1200K
Broadening   nuclide     sn-112 @ 922.039K
Loading      nuclide     sn-114 @ 900K
Loading      nuclide     sn-114 @ 1200K
Broadening   nuclide     sn-114 @ 922.039K
Loading      nuclide     sn-115 @ 900K
Loading      nuclide     sn-115 @ 1200K
Broadening   nuclide     sn-115 @ 922.039K
Loading      nuclide     sn-116 @ 900K
Loading      nuclide     sn-116 @ 1200K
Broadening   nuclide     sn-116 @ 922.039K
Loading      nuclide     sn-117 @ 900K
Loading      nuclide     sn-117 @ 1200K
Broadening   nuclide     sn-117 @ 922.039K
Loading      nuclide     sn-118 @ 900K
Loading      nuclide     sn-118 @ 1200K
Broadening   nuclide     sn-118 @ 922.039K
Loading      nuclide     tb-159 @ 900K
Loading      nuclide     tb-159 @ 1200K
Broadening   nuclide     tb-159 @ 922.039K
Loading      nuclide     sn-119 @ 900K
Loading      nuclide     sn-119 @ 1200K
Broadening   nuclide     sn-119 @ 922.039K
Loading      nuclide     tb-160 @ 900K
Loading      nuclide     tb-160 @ 1200K
Broadening   nuclide     tb-160 @ 922.039K
Loading      nuclide     sn-120 @ 900K
Loading      nuclide     sn-120 @ 1200K
Broadening   nuclide     sn-120 @ 922.039K
Loading      nuclide     dy-160 @ 900K
Loading      nuclide     dy-160 @ 1200K
Broadening   nuclide     dy-160 @ 922.039K
Loading      nuclide     sn-122 @ 900K
Loading      nuclide     sn-122 @ 1200K
Broadening   nuclide     sn-122 @ 922.039K
Loading      nuclide     dy-161 @ 900K
Loading      nuclide     dy-161 @ 1200K
Broadening   nuclide     dy-161 @ 922.039K
Loading      nuclide     sn-123 @ 900K
Loading      nuclide     sn-123 @ 1200K
Broadening   nuclide     sn-123 @ 922.039K
Loading      nuclide     dy-162 @ 900K
Loading      nuclide     dy-162 @ 1200K
Broadening   nuclide     dy-162 @ 922.039K
Loading      nuclide     sn-124 @ 900K
Loading      nuclide     sn-124 @ 1200K
Broadening   nuclide     sn-124 @ 922.039K
Loading      nuclide     dy-163 @ 900K
Loading      nuclide     dy-163 @ 1200K
Broadening   nuclide     dy-163 @ 922.039K
Loading      nuclide     sn-125 @ 900K
Loading      nuclide     sn-125 @ 1200K
Broadening   nuclide     sn-125 @ 922.039K
Loading      nuclide     dy-164 @ 900K
Loading      nuclide     dy-164 @ 1200K
Broadening   nuclide     dy-164 @ 922.039K
Loading      nuclide     ho-165 @ 900K
Loading      nuclide     ho-165 @ 1200K
Broadening   nuclide     ho-165 @ 922.039K
Loading      nuclide     sb-121 @ 900K
Loading      nuclide     sb-121 @ 1200K
Broadening   nuclide     sb-121 @ 922.039K
Loading      nuclide     er-166 @ 900K
Loading      nuclide     er-166 @ 1200K
Broadening   nuclide     er-166 @ 922.039K
Loading      nuclide     sb-123 @ 900K
Loading      nuclide     sb-123 @ 1200K
Broadening   nuclide     sb-123 @ 922.039K
Loading      nuclide     er-167 @ 900K
Loading      nuclide     er-167 @ 1200K
Broadening   nuclide     er-167 @ 922.039K
Loading      nuclide     lu-175 @ 900K
Loading      nuclide     lu-175 @ 1200K
Broadening   nuclide     lu-175 @ 922.039K
Loading      nuclide     re-185 @ 900K
Loading      nuclide     re-185 @ 1200K
Broadening   nuclide     re-185 @ 922.039K
Loading      nuclide     lu-176 @ 900K
Loading      nuclide     lu-176 @ 1200K
Broadening   nuclide     lu-176 @ 922.039K
Loading      nuclide     re-187 @ 900K
Loading      nuclide     re-187 @ 1200K
Broadening   nuclide     re-187 @ 922.039K
Loading      nuclide     ta-181 @ 900K
Loading      nuclide     ta-181 @ 1200K
Broadening   nuclide     ta-181 @ 922.039K
Loading      nuclide     au-197 @ 900K
Loading      nuclide     au-197 @ 1200K
Broadening   nuclide     au-197 @ 922.039K
Loading      nuclide      w-182 @ 900K
Loading      nuclide      w-182 @ 1200K
Broadening   nuclide      w-182 @ 922.039K
Loading      nuclide     th-232 @ 900K
Loading      nuclide     th-232 @ 1200K
Broadening   nuclide     th-232 @ 922.039K
Loading      nuclide      w-183 @ 900K
Loading      nuclide      w-183 @ 1200K
Broadening   nuclide      w-183 @ 922.039K
Loading      nuclide     pa-231 @ 900K
Loading      nuclide     pa-231 @ 1200K
Broadening   nuclide     pa-231 @ 922.039K
Loading      nuclide      w-184 @ 900K
Loading      nuclide      w-184 @ 1200K
Broadening   nuclide      w-184 @ 922.039K
Loading      nuclide     pa-233 @ 900K
Loading      nuclide     pa-233 @ 1200K
Broadening   nuclide     pa-233 @ 922.039K
Loading      nuclide      w-186 @ 900K
Loading      nuclide      w-186 @ 1200K
Broadening   nuclide      w-186 @ 922.039K
Loading      nuclide      u-233 @ 900K
Loading      nuclide      u-233 @ 1200K
Broadening   nuclide      u-233 @ 922.039K
Loading      nuclide     th-230 @ 900K
Loading      nuclide     th-230 @ 1200K
Broadening   nuclide     th-230 @ 922.039K
Loading      nuclide      u-232 @ 900K
Loading      nuclide      u-232 @ 1200K
Broadening   nuclide      u-232 @ 922.039K
Loading      nuclide        h-2 @ 650K
Loading      nuclide        h-3 @ 900K
Loading      nuclide        h-3 @ 1200K
Broadening   nuclide        h-3 @ 922.039K
Loading      nuclide       he-3 @ 900K
Loading      nuclide       he-3 @ 1200K
Broadening   nuclide       he-3 @ 922.039K
Loading      nuclide       he-4 @ 900K
Loading      nuclide       he-4 @ 1200K
Broadening   nuclide       he-4 @ 922.039K
Loading      nuclide       be-7 @ 900K
Loading      nuclide       be-7 @ 1200K
Broadening   nuclide       be-7 @ 922.039K
Loading      nuclide       n-15 @ 900K
Loading      nuclide       n-15 @ 1200K
Broadening   nuclide       n-15 @ 922.039K
Loading      nuclide       o-17 @ 900K
Loading      nuclide       o-17 @ 1200K
Broadening   nuclide       o-17 @ 922.039K
Loading      nuclide      na-23 @ 900K
Loading      nuclide      na-23 @ 1200K
Broadening   nuclide      na-23 @ 922.039K
Loading      nuclide      mg-24 @ 900K
Loading      nuclide      mg-24 @ 1200K
Broadening   nuclide      mg-24 @ 922.039K
Loading      nuclide      mg-25 @ 900K
Loading      nuclide      mg-25 @ 1200K
Broadening   nuclide      mg-25 @ 922.039K
Loading      nuclide      mg-26 @ 900K
Loading      nuclide      mg-26 @ 1200K
Broadening   nuclide      mg-26 @ 922.039K
Loading      nuclide      al-27 @ 900K
Loading      nuclide      al-27 @ 1200K
Broadening   nuclide      al-27 @ 922.039K
Loading      nuclide      si-28 @ 900K
Loading      nuclide      si-28 @ 1200K
Broadening   nuclide      si-28 @ 922.039K
Loading      nuclide      si-29 @ 900K
Loading      nuclide      si-29 @ 1200K
Broadening   nuclide      si-29 @ 922.039K
Loading      nuclide      si-30 @ 900K
Loading      nuclide      si-30 @ 1200K
Broadening   nuclide      si-30 @ 922.039K
Loading      nuclide       p-31 @ 900K
Loading      nuclide       p-31 @ 1200K
Broadening   nuclide       p-31 @ 922.039K
Loading      nuclide       s-32 @ 900K
Loading      nuclide       s-32 @ 1200K
Broadening   nuclide       s-32 @ 922.039K
Loading      nuclide       s-33 @ 900K
Loading      nuclide       s-33 @ 1200K
Broadening   nuclide       s-33 @ 922.039K
Loading      nuclide       s-34 @ 900K
Loading      nuclide       s-34 @ 1200K
Broadening   nuclide       s-34 @ 922.039K
Loading      nuclide       s-36 @ 900K
Loading      nuclide       s-36 @ 1200K
Broadening   nuclide       s-36 @ 922.039K
Loading      nuclide      cl-35 @ 900K
Loading      nuclide      cl-35 @ 1200K
Broadening   nuclide      cl-35 @ 922.039K
Loading      nuclide      cl-37 @ 900K
Loading      nuclide      cl-37 @ 1200K
Broadening   nuclide      cl-37 @ 922.039K
Loading      nuclide      ar-36 @ 900K
Loading      nuclide      ar-36 @ 1200K
Broadening   nuclide      ar-36 @ 922.039K
Loading      nuclide      ar-38 @ 900K
Loading      nuclide      ar-38 @ 1200K
Broadening   nuclide      ar-38 @ 922.039K
Loading      nuclide      ar-40 @ 900K
Loading      nuclide      ar-40 @ 1200K
Broadening   nuclide      ar-40 @ 922.039K
Loading      nuclide       k-39 @ 900K
Loading      nuclide       k-39 @ 1200K
Broadening   nuclide       k-39 @ 922.039K
Loading      nuclide       k-40 @ 900K
Loading      nuclide       k-40 @ 1200K
Broadening   nuclide       k-40 @ 922.039K
Loading      nuclide       k-41 @ 900K
Loading      nuclide       k-41 @ 1200K
Broadening   nuclide       k-41 @ 922.039K
Loading      nuclide      ca-40 @ 900K
Loading      nuclide      ca-40 @ 1200K
Broadening   nuclide      ca-40 @ 922.039K
Loading      nuclide      ca-42 @ 900K
Loading      nuclide      ca-42 @ 1200K
Broadening   nuclide      ca-42 @ 922.039K
Loading      nuclide      ca-43 @ 900K
Loading      nuclide      ca-43 @ 1200K
Broadening   nuclide      ca-43 @ 922.039K
Loading      nuclide      ca-44 @ 900K
Loading      nuclide      ca-44 @ 1200K
Broadening   nuclide      ca-44 @ 922.039K
Loading      nuclide      ca-46 @ 900K
Loading      nuclide      ca-46 @ 1200K
Broadening   nuclide      ca-46 @ 922.039K
Loading      nuclide      ca-48 @ 900K
Loading      nuclide      ca-48 @ 1200K
Broadening   nuclide      ca-48 @ 922.039K
Loading      nuclide      sc-45 @ 900K
Loading      nuclide      sc-45 @ 1200K
Broadening   nuclide      sc-45 @ 922.039K
Loading      nuclide      ti-46 @ 900K
Loading      nuclide      ti-46 @ 1200K
Broadening   nuclide      ti-46 @ 922.039K
Loading      nuclide      ti-47 @ 900K
Loading      nuclide      ti-47 @ 1200K
Broadening   nuclide      ti-47 @ 922.039K
Loading      nuclide      ti-48 @ 900K
Loading      nuclide      ti-48 @ 1200K
Broadening   nuclide      ti-48 @ 922.039K
Loading      nuclide      ti-49 @ 900K
Loading      nuclide      ti-49 @ 1200K
Broadening   nuclide      ti-49 @ 922.039K
Loading      nuclide      ti-50 @ 900K
Loading      nuclide      ti-50 @ 1200K
Broadening   nuclide      ti-50 @ 922.039K
Loading      nuclide      cr-50 @ 900K
Loading      nuclide      cr-50 @ 1200K
Broadening   nuclide      cr-50 @ 922.039K
Loading      nuclide      cr-52 @ 900K
Loading      nuclide      cr-52 @ 1200K
Broadening   nuclide      cr-52 @ 922.039K
Loading      nuclide      cr-53 @ 900K
Loading      nuclide      cr-53 @ 1200K
Broadening   nuclide      cr-53 @ 922.039K
Loading      nuclide      cr-54 @ 900K
Loading      nuclide      cr-54 @ 1200K
Broadening   nuclide      cr-54 @ 922.039K
Loading      nuclide      mn-55 @ 900K
Loading      nuclide      mn-55 @ 1200K
Broadening   nuclide      mn-55 @ 922.039K
Loading      nuclide      fe-54 @ 900K
Loading      nuclide      fe-54 @ 1200K
Broadening   nuclide      fe-54 @ 922.039K
Loading      nuclide      fe-56 @ 900K
Loading      nuclide      fe-56 @ 1200K
Broadening   nuclide      fe-56 @ 922.039K
Loading      nuclide      fe-57 @ 900K
Loading      nuclide      fe-57 @ 1200K
Broadening   nuclide      fe-57 @ 922.039K
Loading      nuclide      fe-58 @ 900K
Loading      nuclide      fe-58 @ 1200K
Broadening   nuclide      fe-58 @ 922.039K
Loading      nuclide      co-58 @ 900K
Loading      nuclide      co-58 @ 1200K
Broadening   nuclide      co-58 @ 922.039K
Loading      nuclide      co-59 @ 900K
Loading      nuclide      co-59 @ 1200K
Broadening   nuclide      co-59 @ 922.039K
Loading      nuclide     co-58m @ 900K
Loading      nuclide     co-58m @ 1200K
Broadening   nuclide     co-58m @ 922.039K
Loading      nuclide      ni-58 @ 900K
Loading      nuclide      ni-58 @ 1200K
Broadening   nuclide      ni-58 @ 922.039K
Loading      nuclide      ni-59 @ 900K
Loading      nuclide      ni-59 @ 1200K
Broadening   nuclide      ni-59 @ 922.039K
Loading      nuclide      ni-60 @ 900K
Loading      nuclide      ni-60 @ 1200K
Broadening   nuclide      ni-60 @ 922.039K
Loading      nuclide      ni-61 @ 900K
Loading      nuclide      ni-61 @ 1200K
Broadening   nuclide      ni-61 @ 922.039K
Loading      nuclide      ni-62 @ 900K
Loading      nuclide      ni-62 @ 1200K
Broadening   nuclide      ni-62 @ 922.039K
Loading      nuclide      ni-64 @ 900K
Loading      nuclide      ni-64 @ 1200K
Broadening   nuclide      ni-64 @ 922.039K
Loading      nuclide      cu-63 @ 900K
Loading      nuclide      cu-63 @ 1200K
Broadening   nuclide      cu-63 @ 922.039K
Loading      nuclide      cu-65 @ 900K
Loading      nuclide      cu-65 @ 1200K
Broadening   nuclide      cu-65 @ 922.039K
Loading      nuclide      ga-69 @ 900K
Loading      nuclide      ga-69 @ 1200K
Broadening   nuclide      ga-69 @ 922.039K
Loading      nuclide      ga-71 @ 900K
Loading      nuclide      ga-71 @ 1200K
Broadening   nuclide      ga-71 @ 922.039K
Loading      nuclide      ge-70 @ 900K
Loading      nuclide      ge-70 @ 1200K
Broadening   nuclide      ge-70 @ 922.039K
Loading      nuclide      as-74 @ 900K
Loading      nuclide      as-74 @ 1200K
Broadening   nuclide      as-74 @ 922.039K
Loading      nuclide      se-74 @ 900K
Loading      nuclide      se-74 @ 1200K
Broadening   nuclide      se-74 @ 922.039K
Loading      nuclide      se-79 @ 900K
Loading      nuclide      se-79 @ 1200K
Broadening   nuclide      se-79 @ 922.039K
Loading      nuclide      kr-78 @ 900K
Loading      nuclide      kr-78 @ 1200K
Broadening   nuclide      kr-78 @ 922.039K
Loading      nuclide    ag-110m @ 900K
Loading      nuclide    ag-110m @ 1200K
Broadening   nuclide    ag-110m @ 922.039K
Loading      nuclide     sn-113 @ 900K
Loading      nuclide     sn-113 @ 1200K
Broadening   nuclide     sn-113 @ 922.039K
Loading      nuclide     xe-123 @ 900K
Loading      nuclide     xe-123 @ 1200K
Broadening   nuclide     xe-123 @ 922.039K
Loading      nuclide     ba-130 @ 900K
Loading      nuclide     ba-130 @ 1200K
Broadening   nuclide     ba-130 @ 922.039K
Loading      nuclide     ba-132 @ 900K
Loading      nuclide     ba-132 @ 1200K
Broadening   nuclide     ba-132 @ 922.039K
Loading      nuclide     ba-133 @ 900K
Loading      nuclide     ba-133 @ 1200K
Broadening   nuclide     ba-133 @ 922.039K
Loading      nuclide     la-138 @ 900K
Loading      nuclide     la-138 @ 1200K
Broadening   nuclide     la-138 @ 922.039K
Loading      nuclide     ce-136 @ 900K
Loading      nuclide     ce-136 @ 1200K
Broadening   nuclide     ce-136 @ 922.039K
Loading      nuclide     ce-138 @ 900K
Loading      nuclide     ce-138 @ 1200K
Broadening   nuclide     ce-138 @ 922.039K
Loading      nuclide     ce-139 @ 900K
Loading      nuclide     ce-139 @ 1200K
Broadening   nuclide     ce-139 @ 922.039K
Loading      nuclide    pm-148m @ 900K
Loading      nuclide    pm-148m @ 1200K
Broadening   nuclide    pm-148m @ 922.039K
Loading      nuclide     gd-153 @ 900K
Loading      nuclide     gd-153 @ 1200K
Broadening   nuclide     gd-153 @ 922.039K
Loading      nuclide     dy-156 @ 900K
Loading      nuclide     dy-156 @ 1200K
Broadening   nuclide     dy-156 @ 922.039K
Loading      nuclide     dy-158 @ 900K
Loading      nuclide     dy-158 @ 1200K
Broadening   nuclide     dy-158 @ 922.039K
Loading      nuclide    ho-166m @ 900K
Loading      nuclide    ho-166m @ 1200K
Broadening   nuclide    ho-166m @ 922.039K
Loading      nuclide     er-162 @ 900K
Loading      nuclide     er-162 @ 1200K
Broadening   nuclide     er-162 @ 922.039K
Loading      nuclide     er-164 @ 900K
Loading      nuclide     er-164 @ 1200K
Broadening   nuclide     er-164 @ 922.039K
Loading      nuclide     er-168 @ 900K
Loading      nuclide     er-168 @ 1200K
Broadening   nuclide     er-168 @ 922.039K
Loading      nuclide     er-170 @ 900K
Loading      nuclide     er-170 @ 1200K
Broadening   nuclide     er-170 @ 922.039K
Loading      nuclide     hf-174 @ 900K
Loading      nuclide     hf-174 @ 1200K
Broadening   nuclide     hf-174 @ 922.039K
Loading      nuclide     hf-176 @ 900K
Loading      nuclide     hf-176 @ 1200K
Broadening   nuclide     hf-176 @ 922.039K
Loading      nuclide     hf-177 @ 900K
Loading      nuclide     hf-177 @ 1200K
Broadening   nuclide     hf-177 @ 922.039K
Loading      nuclide     hf-178 @ 900K
Loading      nuclide     hf-178 @ 1200K
Broadening   nuclide     hf-178 @ 922.039K
Loading      nuclide     hf-179 @ 900K
Loading      nuclide     hf-179 @ 1200K
Broadening   nuclide     hf-179 @ 922.039K
Loading      nuclide     hf-180 @ 900K
Loading      nuclide     hf-180 @ 1200K
Broadening   nuclide     hf-180 @ 922.039K
Loading      nuclide     ta-182 @ 900K
Loading      nuclide     ta-182 @ 1200K
Broadening   nuclide     ta-182 @ 922.039K
Loading      nuclide     ir-191 @ 900K
Loading      nuclide     ir-191 @ 1200K
Broadening   nuclide     ir-191 @ 922.039K
Loading      nuclide     ir-193 @ 900K
Loading      nuclide     ir-193 @ 1200K
Broadening   nuclide     ir-193 @ 922.039K
Loading      nuclide     hg-196 @ 900K
Loading      nuclide     hg-196 @ 1200K
Broadening   nuclide     hg-196 @ 922.039K
Loading      nuclide     hg-198 @ 900K
Loading      nuclide     hg-198 @ 1200K
Broadening   nuclide     hg-198 @ 922.039K
Loading      nuclide     hg-199 @ 900K
Loading      nuclide     hg-199 @ 1200K
Broadening   nuclide     hg-199 @ 922.039K
Loading      nuclide     hg-200 @ 900K
Loading      nuclide     hg-200 @ 1200K
Broadening   nuclide     hg-200 @ 922.039K
Loading      nuclide     hg-201 @ 900K
Loading      nuclide     hg-201 @ 1200K
Broadening   nuclide     hg-201 @ 922.039K
Loading      nuclide     hg-202 @ 900K
Loading      nuclide     hg-202 @ 1200K
Broadening   nuclide     hg-202 @ 922.039K
Loading      nuclide     hg-204 @ 900K
Loading      nuclide     hg-204 @ 1200K
Broadening   nuclide     hg-204 @ 922.039K
Loading      nuclide     pb-204 @ 900K
Loading      nuclide     pb-204 @ 1200K
Broadening   nuclide     pb-204 @ 922.039K
Loading      nuclide     pb-206 @ 900K
Loading      nuclide     pb-206 @ 1200K
Broadening   nuclide     pb-206 @ 922.039K
Loading      nuclide     pb-207 @ 900K
Loading      nuclide     pb-207 @ 1200K
Broadening   nuclide     pb-207 @ 922.039K
Loading      nuclide     pb-208 @ 900K
Loading      nuclide     pb-208 @ 1200K
Broadening   nuclide     pb-208 @ 922.039K
Loading      nuclide     bi-209 @ 900K
Loading      nuclide     bi-209 @ 1200K
Broadening   nuclide     bi-209 @ 922.039K
Loading      nuclide     ra-223 @ 900K
Loading      nuclide     ra-223 @ 1200K
Broadening   nuclide     ra-223 @ 922.039K
Loading      nuclide     ra-224 @ 900K
Loading      nuclide     ra-224 @ 1200K
Broadening   nuclide     ra-224 @ 922.039K
Loading      nuclide     ra-225 @ 900K
Loading      nuclide     ra-225 @ 1200K
Broadening   nuclide     ra-225 @ 922.039K
Loading      nuclide     ra-226 @ 900K
Loading      nuclide     ra-226 @ 1200K
Broadening   nuclide     ra-226 @ 922.039K
Loading      nuclide     ac-225 @ 900K
Loading      nuclide     ac-225 @ 1200K
Broadening   nuclide     ac-225 @ 922.039K
Loading      nuclide     ac-226 @ 900K
Loading      nuclide     ac-226 @ 1200K
Broadening   nuclide     ac-226 @ 922.039K
Loading      nuclide     ac-227 @ 900K
Loading      nuclide     ac-227 @ 1200K
Broadening   nuclide     ac-227 @ 922.039K
Loading      nuclide     th-227 @ 900K
Loading      nuclide     th-227 @ 1200K
Broadening   nuclide     th-227 @ 922.039K
Loading      nuclide     th-228 @ 900K
Loading      nuclide     th-228 @ 1200K
Broadening   nuclide     th-228 @ 922.039K
Loading      nuclide     th-229 @ 900K
Loading      nuclide     th-229 @ 1200K
Broadening   nuclide     th-229 @ 922.039K
Loading      nuclide     th-233 @ 900K
Loading      nuclide     th-233 @ 1200K
Broadening   nuclide     th-233 @ 922.039K
Loading      nuclide     th-234 @ 900K
Loading      nuclide     th-234 @ 1200K
Broadening   nuclide     th-234 @ 922.039K
Loading      nuclide     pa-232 @ 900K
Loading      nuclide     pa-232 @ 1200K
Broadening   nuclide     pa-232 @ 922.039K
Loading      nuclide      u-237 @ 900K
Loading      nuclide      u-237 @ 1200K
Broadening   nuclide      u-237 @ 922.039K
Loading      nuclide      u-239 @ 900K
Loading      nuclide      u-239 @ 1200K
Broadening   nuclide      u-239 @ 922.039K
Loading      nuclide      u-240 @ 900K
Loading      nuclide      u-240 @ 1200K
Broadening   nuclide      u-240 @ 922.039K
Loading      nuclide      u-241 @ 900K
Loading      nuclide      u-241 @ 1200K
Broadening   nuclide      u-241 @ 922.039K
Loading      nuclide     np-235 @ 900K
Loading      nuclide     np-235 @ 1200K
Broadening   nuclide     np-235 @ 922.039K
Loading      nuclide     np-236 @ 900K
Loading      nuclide     np-236 @ 1200K
Broadening   nuclide     np-236 @ 922.039K
Loading      nuclide     np-238 @ 900K
Loading      nuclide     np-238 @ 1200K
Broadening   nuclide     np-238 @ 922.039K
Loading      nuclide     np-239 @ 900K
Loading      nuclide     np-239 @ 1200K
Broadening   nuclide     np-239 @ 922.039K
Loading      nuclide     pu-236 @ 900K
Loading      nuclide     pu-236 @ 1200K
Broadening   nuclide     pu-236 @ 922.039K
Loading      nuclide     pu-237 @ 900K
Loading      nuclide     pu-237 @ 1200K
Broadening   nuclide     pu-237 @ 922.039K
Loading      nuclide     pu-243 @ 900K
Loading      nuclide     pu-243 @ 1200K
Broadening   nuclide     pu-243 @ 922.039K
Loading      nuclide     pu-244 @ 900K
Loading      nuclide     pu-244 @ 1200K
Broadening   nuclide     pu-244 @ 922.039K
Loading      nuclide     pu-246 @ 900K
Loading      nuclide     pu-246 @ 1200K
Broadening   nuclide     pu-246 @ 922.039K
Loading      nuclide     am-244 @ 900K
Loading      nuclide     am-244 @ 1200K
Broadening   nuclide     am-244 @ 922.039K
Loading      nuclide    am-244m @ 900K
Loading      nuclide    am-244m @ 1200K
Broadening   nuclide    am-244m @ 922.039K
Loading      nuclide     cm-241 @ 900K
Loading      nuclide     cm-241 @ 1200K
Broadening   nuclide     cm-241 @ 922.039K
Loading      nuclide     cm-245 @ 900K
Loading      nuclide     cm-245 @ 1200K
Broadening   nuclide     cm-245 @ 922.039K
Loading      nuclide     cm-246 @ 900K
Loading      nuclide     cm-246 @ 1200K
Broadening   nuclide     cm-246 @ 922.039K
Loading      nuclide     cm-247 @ 900K
Loading      nuclide     cm-247 @ 1200K
Broadening   nuclide     cm-247 @ 922.039K
Loading      nuclide     cm-248 @ 900K
Loading      nuclide     cm-248 @ 1200K
Broadening   nuclide     cm-248 @ 922.039K
Loading      nuclide     cm-249 @ 900K
Loading      nuclide     cm-249 @ 1200K
Broadening   nuclide     cm-249 @ 922.039K
Loading      nuclide     cm-250 @ 900K
Loading      nuclide     cm-250 @ 1200K
Broadening   nuclide     cm-250 @ 922.039K
Loading      nuclide     bk-249 @ 900K
Loading      nuclide     bk-249 @ 1200K
Broadening   nuclide     bk-249 @ 922.039K
Loading      nuclide     bk-250 @ 900K
Loading      nuclide     bk-250 @ 1200K
Broadening   nuclide     bk-250 @ 922.039K
Loading      nuclide     cf-249 @ 900K
Loading      nuclide     cf-249 @ 1200K
Broadening   nuclide     cf-249 @ 922.039K
Loading      nuclide     cf-250 @ 900K
Loading      nuclide     cf-250 @ 1200K
Broadening   nuclide     cf-250 @ 922.039K
Loading      nuclide     cf-251 @ 900K
Loading      nuclide     cf-251 @ 1200K
Broadening   nuclide     cf-251 @ 922.039K
Loading      nuclide     cf-252 @ 900K
Loading      nuclide     cf-252 @ 1200K
Broadening   nuclide     cf-252 @ 922.039K
Loading      nuclide     cf-253 @ 900K
Loading      nuclide     cf-253 @ 1200K
Broadening   nuclide     cf-253 @ 922.039K
Loading      nuclide     cf-254 @ 900K
Loading      nuclide     cf-254 @ 1200K
Broadening   nuclide     cf-254 @ 922.039K
Loading      nuclide     es-253 @ 900K
Loading      nuclide     es-253 @ 1200K
Broadening   nuclide     es-253 @ 922.039K
Loading      nuclide     es-254 @ 900K
Loading      nuclide     es-254 @ 1200K
Broadening   nuclide     es-254 @ 922.039K
Loading      nuclide     es-255 @ 900K
Loading      nuclide     es-255 @ 1200K
Broadening   nuclide     es-255 @ 922.039K
Loading      nuclide c-graphite @ 800K
Loading      nuclide c-graphite @ 1000K
Broadening   nuclide c-graphite @ 922.039K
MixMacros: MT 2022 greater than MT 2 for nuclide 60146.
MixMacros: MT 2022 greater than MT 2 for nuclide 60148.
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
MixMacros: MT 2022 greater than MT 2 for nuclide 62148.
MixMacros: MT 2022 greater than MT 2 for nuclide 66164.
MixMacros: MT 2022 greater than MT 2 for nuclide 74182.
MixMacros: MT 2022 greater than MT 2 for nuclide 74186.
MixMacros: MT 2022 greater than MT 2 for nuclide 72180.
MixMacros: MT 2022 greater than MT 2 for nuclide 60146.
MixMacros: MT 2022 greater than MT 2 for nuclide 60148.
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
MixMacros: MT 2022 greater than MT 2 for nuclide 62148.
MixMacros: MT 2022 greater than MT 2 for nuclide 66164.
MixMacros: MT 2022 greater than MT 2 for nuclide 74182.
MixMacros: MT 2022 greater than MT 2 for nuclide 74186.
MixMacros: MT 2022 greater than MT 2 for nuclide 72180.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:17:19

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00000   0.000E+00 1.530E+06 (    1,252)   1.000E+00 (    2,  0) 13:17:22    2.6 s     2.6 s  87.7%    F
     2    0.38405   1.604E+00 1.516E+03 (  461,  6)   1.642E+00 (   38,  0) 13:17:25    5.3 s     2.7 s  88.7%    F
     3    0.31537   2.178E-01 1.286E+00 (  895,  1)   2.157E-01 (  242,  0) 13:17:27    8.0 s     2.7 s 134.5%    F
     4    0.36896   1.452E-01 1.374E+00 (   14,  7)   1.803E-01 (  944,  0) 13:17:30   10.6 s     2.7 s  89.0%    F
     5    0.47444   2.223E-01 3.934E+00 (   14,  7)   1.551E-01 (  584,  0) 13:17:33   13.3 s     2.7 s  88.3%    F
     6    0.62216   2.374E-01 1.495E+01 (   14,  8)   1.351E-01 (  941,  0) 13:17:35   16.0 s     2.7 s 133.0%    F
     7    0.80139   2.236E-01 2.303E+01 (  242,  9)   1.276E-01 (  517,  0) 13:17:38   18.6 s     2.7 s  89.0%    F
     8    0.99683   1.961E-01 1.165E+00 (  150,  1)   1.109E-01 (  517,  0) 13:17:41   21.3 s     2.7 s  89.0%    F
     9    1.19120   1.632E-01 1.161E+00 (   88,  1)   9.099E-02 (  517,  0) 13:17:43   24.0 s     2.7 s 133.0%    F
    10    1.36881   1.298E-01 1.158E+00 (  897,  1)   7.131E-02 (  517,  0) 13:17:46   26.6 s     2.7 s  89.0%    F
    11    1.51838   9.851E-02 1.156E+00 (   88,  1)   5.345E-02 (  517,  0) 13:17:49   29.3 s     2.7 s  89.0%    F
    12    1.63413   7.084E-02 1.154E+00 (  831,  1)   3.808E-02 (  517,  0) 13:17:51   32.0 s     2.7 s 133.5%    F
    13    1.71545   4.740E-02 1.153E+00 (  150,  1)   2.536E-02 (  517,  0) 13:17:54   34.6 s     2.7 s  88.7%    F
    14    1.76549   2.835E-02 1.151E+00 (   88,  1)   1.522E-02 (  517,  0) 13:17:57   37.3 s     2.7 s  89.0%    F
    15    1.78963   1.349E-02 1.151E+00 (   88,  1)   7.427E-03 (  936,  0) 13:17:59   40.0 s     2.7 s 134.5%    F
    16    1.79400   2.436E-03 1.150E+00 (  150,  1)   4.824E-03 (  584,  0) 13:18:02   42.7 s     2.7 s  89.7%    F
    17    1.78451   5.322E-03 1.149E+00 (   88,  1)   6.857E-03 (  944,  0) 13:18:05   45.3 s     2.7 s  89.0%    F
    18    1.76624   1.034E-02 1.149E+00 (  897,  1)   7.819E-03 (  584,  0) 13:18:07   48.0 s     2.7 s 133.0%    F
    19    1.74327   1.318E-02 1.148E+00 (  150,  1)   8.001E-03 (  584,  0) 13:18:10   50.7 s     2.7 s  89.0%    F
    20    1.71864   1.433E-02 1.148E+00 (  897,  1)   7.642E-03 (  944,  0) 13:18:13   53.3 s     2.7 s  88.7%    F
    21    1.69445   1.427E-02 1.148E+00 (  150,  1)   7.110E-03 (  517,  0) 13:18:15   56.0 s     2.7 s 133.5%    F
    22    1.67210   1.337E-02 1.148E+00 (  769,  1)   6.699E-03 (  947,  0) 13:18:18   58.7 s     2.7 s  88.7%    F
    23    1.65235   1.195E-02 1.147E+00 (  146,  1)   6.016E-03 (  517,  0) 13:18:21   61.3 s     2.7 s  89.0%    F
    24    1.63558   1.025E-02 1.147E+00 (  769,  1)   5.187E-03 (  947,  0) 13:18:23   64.0 s     2.7 s 133.0%    F
    25    1.62183   8.475E-03 1.147E+00 (  146,  1)   4.306E-03 (  947,  0) 13:18:26   66.7 s     2.7 s  89.0%    F
    26    1.61097   6.744E-03 1.147E+00 (  769,  1)   3.443E-03 (  517,  0) 13:18:29   69.3 s     2.7 s  88.7%    F
    27    1.60271   5.152E-03 1.147E+00 (  146,  1)   2.643E-03 (  517,  0) 13:18:31   72.0 s     2.7 s 133.0%    F
    28    1.59672   3.752E-03 1.147E+00 (  146,  1)   1.936E-03 (  517,  0) 13:18:34   74.7 s     2.7 s  89.0%    F
    29    1.59263   2.569E-03 1.147E+00 (  769,  1)   1.336E-03 (  947,  0) 13:18:37   77.3 s     2.7 s  88.7%    F
    30    1.59008   1.606E-03 1.147E+00 (  769,  1)   8.446E-04 (  936,  0) 13:18:39   80.0 s     2.7 s 133.5%    F
    31    1.58872   8.526E-04 1.147E+00 (  769,  1)   4.587E-04 (  933,  0) 13:18:42   82.7 s     2.7 s  88.7%    F
    32    1.58828   2.785E-04 1.147E+00 (  175,  1)   1.687E-04 (  944,  0) 13:18:45   85.3 s     2.7 s  88.7%    F
    33    1.58841   8.081E-05 1.147E+00 (  740,  1)   2.751E-04 (  584,  0) 13:18:47   88.0 s     2.7 s 135.5%    F
    34    1.58871   1.885E-04 1.147E+00 (  740,  1)   3.308E-04 (  584,  0) 13:18:50   90.8 s     2.8 s  93.0%    F
    35    1.58925   3.427E-04 1.147E+00 (  175,  1)   3.540E-04 (  944,  0) 13:18:53   93.5 s     2.7 s  89.3%    F
    36    1.59001   4.751E-04 1.147E+00 (  205,  1)   3.510E-04 (  584,  0) 13:18:55   96.1 s     2.7 s 132.5%    F
    37    1.59087   5.394E-04 1.147E+00 (  741,  1)   3.314E-04 (  944,  0) 13:18:58   98.8 s     2.7 s  88.7%    F
    38    1.59173   5.434E-04 1.147E+00 (  741,  1)   3.153E-04 (  947,  0) 13:19:01  101.4 s     2.6 s  87.7%    F
    39    1.59254   5.071E-04 1.147E+00 (  205,  1)   2.949E-04 (  517,  0) 13:19:03  104.1 s     2.6 s 131.0%    F
    40    1.59325   4.478E-04 1.147E+00 (  741,  1)   2.658E-04 (  947,  0) 13:19:06  106.7 s     2.6 s  88.0%    F
    41    1.59385   3.781E-04 1.147E+00 (  205,  1)   2.325E-04 (  947,  0) 13:19:09  109.3 s     2.6 s  88.0%    F
    42    1.59434   3.071E-04 1.147E+00 (  235,  1)   1.980E-04 (  517,  0) 13:19:11  112.0 s     2.7 s 132.5%    F
    43    1.59473   2.407E-04 1.147E+00 (  742,  1)   1.650E-04 (  517,  0) 13:19:14  114.6 s     2.6 s  88.3%    F
    44    1.59502   1.824E-04 1.147E+00 (  235,  1)   1.348E-04 (  947,  0) 13:19:17  117.3 s     2.7 s  88.7%    F
    45    1.59523   1.339E-04 1.147E+00 (  742,  1)   1.085E-04 (  947,  0) 13:19:19  119.9 s     2.7 s 132.5%    F
    46    1.59538   9.523E-05 1.147E+00 (  742,  1)   8.649E-05 (  517,  0) 13:19:22  122.6 s     2.7 s  89.0%    F
    47    1.59549   6.698E-05 1.147E+00 (  235,  1)   6.850E-05 (  933,  0) 13:19:25  125.3 s     2.7 s  90.7%    F
 k-eff =       1.59549074     Time=      0.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.444
 Inscatter Source  :     0.221
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.027
 Total (per outer):      2.692

  Total iteration time breakdown (sec):
 Transport Sweeping:   114.874
 Inscatter Source  :    10.371
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.286
 Total Time        :   126.531

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.59611E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:21:58

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.59549   6.698E-05 1.147E+00 (  742,  1)   6.346E-05 (   14,  0) 13:22:01    2.7 s     2.7 s  90.7%    F
     2    1.59537   7.522E-05 1.147E+00 (  742,  1)   2.077E-04 (  242,  0) 13:22:04    5.5 s     2.8 s  92.0%    F
     3    1.59530   4.214E-05 1.147E+00 (  235,  1)   4.312E-05 (   90,  0) 13:22:06    8.0 s     2.5 s 126.0%    F
 k-eff =       1.59530350     Time=      1.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.423
 Inscatter Source  :     0.230
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.390
 Total (per outer):      3.043

  Total iteration time breakdown (sec):
 Transport Sweeping:     7.269
 Inscatter Source  :     0.690
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.169
 Total Time        :     9.128

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.59460E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:24:46

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.59530   4.214E-05 1.147E+00 (  713,  1)   1.349E-03 (  948,  0) 13:24:49    2.5 s     2.5 s  83.7%    F
     2    1.59497   2.092E-04 1.231E+00 (  242,  4)   4.044E-04 (  242,  0) 13:24:51    5.1 s     2.6 s 130.5%    F
     3    1.59458   2.469E-04 1.147E+00 (  266,  1)   1.916E-04 (   14,  0) 13:24:54    7.7 s     2.6 s  87.3%    F
     4    1.59416   2.620E-04 1.147E+00 (  713,  1)   1.895E-04 (   14,  0) 13:24:57   10.4 s     2.7 s  88.3%    F
     5    1.59374   2.655E-04 1.147E+00 (  713,  1)   1.874E-04 (  941,  0) 13:24:59   13.0 s     2.6 s 132.0%    F
     6    1.59332   2.595E-04 1.147E+00 (  655,  1)   1.830E-04 (  517,  0) 13:25:02   15.7 s     2.7 s  88.3%    F
     7    1.59293   2.451E-04 1.147E+00 (  655,  1)   1.745E-04 (  947,  0) 13:25:04   18.3 s     2.6 s 132.0%    F
     8    1.59257   2.241E-04 1.124E+00 (  507,  2)   1.627E-04 (  517,  0) 13:25:07   20.8 s     2.5 s  82.7%    F
     9    1.59226   1.984E-04 1.104E+00 (  507,  3)   1.485E-04 (  517,  0) 13:25:09   23.3 s     2.5 s 126.0%    F
    10    1.59199   1.706E-04 2.195E-03 (  944,  4)   1.330E-04 (  947,  0) 13:25:12   25.9 s     2.6 s  87.3%    F
    11    1.59176   1.428E-04 9.661E-04 (  584,  4)   1.174E-04 (  947,  0) 13:25:15   28.6 s     2.7 s  89.3%    F
    12    1.59157   1.167E-04 4.561E-04 (  584,  4)   1.025E-04 (  517,  0) 13:25:17   31.3 s     2.6 s 132.0%    F
    13    1.59143   9.343E-05 2.388E-04 (  584,  4)   8.882E-05 (  517,  0) 13:25:20   33.9 s     2.6 s  87.7%    F
    14    1.59130   7.557E-05 1.304E-04 (  944,  4)   7.666E-05 (  947,  0) 13:25:23   36.3 s     2.5 s  82.0%    F
 k-eff =       1.59130483     Time=     24.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.374
 Inscatter Source  :     0.219
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.085
 Total (per outer):      2.678

  Total iteration time breakdown (sec):
 Transport Sweeping:    33.241
 Inscatter Source  :     3.067
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.185
 Total Time        :    37.493

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.59035E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:28:03

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.59130   7.557E-05 9.306E-01 (  242,  4)   2.261E-03 (  948,  0) 13:28:06    2.7 s     2.7 s  88.3%    F
     2    1.59089   2.581E-04 1.071E+00 (  242,  4)   4.859E-04 (   14,  0) 13:28:08    5.3 s     2.6 s 131.5%    F
     3    1.59033   3.570E-04 5.489E-01 (   14,  4)   2.808E-04 (  944,  0) 13:28:11    7.9 s     2.6 s  87.3%    F
     4    1.58968   4.066E-04 2.685E-01 (  944,  4)   2.736E-04 (  242,  0) 13:28:14   10.5 s     2.6 s  87.7%    F
     5    1.58900   4.255E-04 1.128E-01 (  584,  4)   2.645E-04 (  904,  0) 13:28:16   13.1 s     2.6 s 131.0%    F
     6    1.58833   4.227E-04 4.845E-02 (  944,  4)   2.605E-04 (  486,  0) 13:28:19   15.8 s     2.6 s  87.7%    F
     7    1.58769   4.021E-04 2.050E-02 (  584,  4)   2.490E-04 (  517,  0) 13:28:22   18.4 s     2.6 s  87.3%    F
     8    1.58711   3.675E-04 8.447E-03 (  944,  4)   2.312E-04 (  517,  0) 13:28:24   20.9 s     2.5 s 124.0%    F
     9    1.58660   3.235E-04 3.585E-03 (  584,  4)   2.091E-04 (  947,  0) 13:28:27   23.5 s     2.6 s  88.0%    F
    10    1.58616   2.748E-04 1.577E-03 (  944,  4)   1.845E-04 (  517,  0) 13:28:29   26.2 s     2.7 s 133.0%    F
    11    1.58580   2.258E-04 7.424E-04 (  944,  4)   1.594E-04 (  517,  0) 13:28:32   28.8 s     2.6 s  88.0%    F
    12    1.58552   1.799E-04 3.973E-04 (  944,  4)   1.352E-04 (  947,  0) 13:28:35   31.5 s     2.7 s  88.7%    F
    13    1.58530   1.394E-04 2.460E-04 (  584,  4)   1.131E-04 (  947,  0) 13:28:37   34.1 s     2.7 s 133.0%    F
    14    1.58513   1.052E-04 1.722E-04 (  944,  4)   9.371E-05 (  517,  0) 13:28:40   36.8 s     2.7 s  89.0%    F
    15    1.58501   7.748E-05 1.327E-04 (  242,  4)   7.724E-05 (  947,  0) 13:28:43   39.5 s     2.7 s  91.3%    F
    16    1.58491   6.259E-05 8.308E-05 (  870,238)   6.375E-05 (  947,  0) 13:28:45   42.1 s     2.6 s 129.5%    F
 k-eff =       1.58490880     Time=     70.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.406
 Inscatter Source  :     0.223
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.081
 Total (per outer):      2.710

  Total iteration time breakdown (sec):
 Transport Sweeping:    38.495
 Inscatter Source  :     3.569
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.294
 Total Time        :    43.358

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.58422E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:31:30

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.58491   6.259E-05 1.000E+00 (    2,  3)   2.307E-03 (  581,  0) 13:31:33    2.7 s     2.7 s  88.7%    F
     2    1.58481   6.230E-05 1.217E+00 (  242,  3)   9.882E-05 (  242,  0) 13:31:35    5.3 s     2.6 s 131.5%    F
     3    1.58463   1.160E-04 7.117E-01 (   14,  3)   1.770E-04 (  584,  0) 13:31:38    8.0 s     2.7 s  90.3%    F
     4    1.58438   1.537E-04 3.799E-01 (  584,  3)   1.810E-04 (  242,  0) 13:31:41   10.7 s     2.7 s  91.3%    F
     5    1.58408   1.941E-04 1.721E-01 (  944,  3)   1.846E-04 (   14,  0) 13:31:44   13.4 s     2.7 s  90.0%    F
     6    1.58372   2.250E-04 7.641E-02 (  584,  3)   1.831E-04 (  944,  0) 13:31:46   16.1 s     2.7 s 135.0%    F
     7    1.58334   2.409E-04 3.272E-02 (  944,  3)   1.783E-04 (  487,  0) 13:31:49   18.8 s     2.7 s  90.0%    F
     8    1.58295   2.419E-04 1.359E-02 (  944,  3)   1.758E-04 (  517,  0) 13:31:52   21.5 s     2.7 s  89.7%    F
     9    1.58259   2.306E-04 5.693E-03 (  944,  3)   1.678E-04 (  947,  0) 13:31:54   24.2 s     2.6 s 132.5%    F
    10    1.58226   2.105E-04 2.402E-03 (  584,  3)   1.558E-04 (  517,  0) 13:31:57   26.7 s     2.5 s  84.0%    F
    11    1.58196   1.853E-04 1.038E-03 (  944,  3)   1.415E-04 (  517,  0) 13:32:00   29.3 s     2.6 s  88.0%    F
    12    1.58171   1.581E-04 4.804E-04 (  944,  3)   1.262E-04 (  947,  0) 13:32:02   32.0 s     2.7 s 133.0%    F
    13    1.58151   1.313E-04 2.512E-04 (  944,  3)   1.110E-04 (  517,  0) 13:32:05   34.7 s     2.7 s  88.3%    F
    14    1.58134   1.065E-04 1.547E-04 (  584,  3)   9.659E-05 (  517,  0) 13:32:08   37.4 s     2.7 s  90.7%    F
    15    1.58120   8.473E-05 1.112E-04 (  584,  3)   8.366E-05 (  947,  0) 13:32:10   40.0 s     2.7 s 133.0%    F
 k-eff =       1.58120353     Time=    115.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.442
 Inscatter Source  :     0.222
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.080
 Total (per outer):      2.744

  Total iteration time breakdown (sec):
 Transport Sweeping:    36.636
 Inscatter Source  :     3.335
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.196
 Total Time        :    41.167

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.58018E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:34:54

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.58120   8.473E-05 1.000E+00 (    1,  2)   2.391E-03 (  581,  0) 13:34:57    2.7 s     2.7 s  91.0%    F
     2    1.58124   2.066E-05 1.174E+00 (  242,  2)   9.068E-05 (  242,  0) 13:35:00    5.4 s     2.7 s  90.7%    F
     3    1.58113   6.424E-05 7.140E-01 (   14,  2)   1.420E-04 (  944,  0) 13:35:03    8.1 s     2.7 s  90.0%    F
     4    1.58097   1.015E-04 3.930E-01 (  944,  2)   1.495E-04 (   14,  0) 13:35:05   10.8 s     2.7 s 133.5%    F
     5    1.58077   1.283E-04 1.853E-01 (  584,  2)   1.567E-04 (  242,  0) 13:35:08   13.5 s     2.6 s  88.0%    F
     6    1.58052   1.597E-04 8.471E-02 (  584,  2)   1.593E-04 (  584,  0) 13:35:10   16.1 s     2.6 s 132.0%    F
     7    1.58023   1.835E-04 3.712E-02 (  944,  2)   1.581E-04 (  944,  0) 13:35:13   18.8 s     2.6 s  88.3%    F
     8    1.57992   1.947E-04 1.577E-02 (  944,  2)   1.543E-04 (  486,  0) 13:35:16   21.4 s     2.7 s  89.3%    F
     9    1.57962   1.935E-04 6.717E-03 (  584,  2)   1.507E-04 (  947,  0) 13:35:18   24.1 s     2.7 s 133.5%    F
    10    1.57933   1.825E-04 2.864E-03 (  584,  2)   1.428E-04 (  517,  0) 13:35:21   26.6 s     2.5 s  84.0%    F
    11    1.57907   1.652E-04 1.237E-03 (  584,  2)   1.322E-04 (  947,  0) 13:35:23   29.1 s     2.4 s 122.5%    F
    12    1.57884   1.445E-04 5.604E-04 (  944,  2)   1.199E-04 (  517,  0) 13:35:26   31.8 s     2.7 s  89.7%    F
    13    1.57864   1.230E-04 2.790E-04 (  584,  2)   1.072E-04 (  517,  0) 13:35:29   34.5 s     2.7 s  90.3%    F
    14    1.57848   1.022E-04 1.612E-04 (  584,  2)   9.495E-05 (  947,  0) 13:35:32   37.2 s     2.7 s  89.7%    F
    15    1.57835   8.325E-05 1.103E-04 (  944,  2)   8.353E-05 (  947,  0) 13:35:34   39.8 s     2.6 s 130.0%    F
 k-eff =       1.57835146     Time=    161.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.423
 Inscatter Source  :     0.223
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.081
 Total (per outer):      2.727

  Total iteration time breakdown (sec):
 Transport Sweeping:    36.347
 Inscatter Source  :     3.346
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.209
 Total Time        :    40.902

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.57727E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:38:21

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.57835   8.325E-05 8.435E-01 (   14,  2)   2.457E-03 (  948,  0) 13:38:23    2.7 s     2.7 s 134.5%    F
     2    1.57847   7.522E-05 8.366E-01 (  242,  2)   2.036E-04 (   14,  0) 13:38:26    5.4 s     2.7 s  89.7%    F
     3    1.57843   2.841E-05 4.221E-01 (   14,  2)   1.166E-04 (  944,  0) 13:38:29    8.0 s     2.6 s  87.3%    F
     4    1.57831   7.193E-05 2.043E-01 (  584,  2)   1.262E-04 (  242,  0) 13:38:31   10.6 s     2.6 s 130.5%    F
     5    1.57815   1.021E-04 8.845E-02 (  944,  2)   1.387E-04 (   14,  0) 13:38:34   13.3 s     2.7 s  88.3%    F
     6    1.57796   1.238E-04 3.875E-02 (  944,  2)   1.421E-04 (  584,  0) 13:38:37   15.9 s     2.6 s  88.3%    F
     7    1.57772   1.467E-04 1.662E-02 (  944,  2)   1.436E-04 (  944,  0) 13:38:39   18.4 s     2.5 s 126.0%    F
     8    1.57747   1.615E-04 6.965E-03 (  584,  2)   1.403E-04 (  584,  0) 13:38:42   21.1 s     2.6 s  87.7%    F
     9    1.57721   1.656E-04 2.926E-03 (  584,  2)   1.375E-04 (  947,  0) 13:38:44   23.7 s     2.6 s 131.5%    F
    10    1.57696   1.600E-04 1.231E-03 (  584,  2)   1.320E-04 (  947,  0) 13:38:47   26.3 s     2.6 s  88.0%    F
    11    1.57672   1.478E-04 5.329E-04 (  584,  3)   1.237E-04 (  947,  0) 13:38:49   28.5 s     2.2 s 110.0%    F
    12    1.57652   1.316E-04 2.502E-04 (  584,  3)   1.135E-04 (  517,  0) 13:38:51   30.8 s     2.3 s 115.5%    F
    13    1.57634   1.136E-04 1.379E-04 (  584,  2)   1.027E-04 (  947,  0) 13:38:54   33.4 s     2.6 s  86.7%    F
    14    1.57618   9.594E-05 1.073E-04 (  272,238)   9.192E-05 (  517,  0) 13:38:57   36.1 s     2.6 s  87.7%    F
    15    1.57606   8.085E-05 9.629E-05 (  870,238)   8.179E-05 (  517,  0) 13:38:59   38.4 s     2.3 s 117.5%    F
 k-eff =       1.57605726     Time=    206.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.329
 Inscatter Source  :     0.228
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.080
 Total (per outer):      2.637

  Total iteration time breakdown (sec):
 Transport Sweeping:    34.931
 Inscatter Source  :     3.427
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.199
 Total Time        :    39.557

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.57495E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:41:47

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.57606   8.085E-05 8.146E-01 (   14,  2)   2.519E-03 (  948,  0) 13:41:50    2.8 s     2.8 s  92.7%    F
     2    1.57623   1.076E-04 7.854E-01 (  242,  2)   2.693E-04 (   14,  0) 13:41:53    5.5 s     2.8 s  92.0%    F
     3    1.57622   7.138E-06 3.863E-01 (  242,  2)   1.031E-04 (  944,  0) 13:41:55    8.3 s     2.8 s 137.5%    F
     4    1.57613   5.459E-05 1.842E-01 (  584,  2)   1.137E-04 (   14,  0) 13:41:58   10.9 s     2.6 s  87.7%    F
     5    1.57599   8.840E-05 7.908E-02 (  944,  2)   1.288E-04 (  242,  0) 13:42:01   13.7 s     2.7 s  91.3%    F
     6    1.57582   1.109E-04 3.451E-02 (  944,  2)   1.324E-04 (  584,  0) 13:42:04   16.4 s     2.8 s  92.3%    F
     7    1.57561   1.302E-04 1.480E-02 (  584,  2)   1.361E-04 (  584,  0) 13:42:06   19.1 s     2.6 s 132.5%    F
     8    1.57538   1.452E-04 6.203E-03 (  944,  2)   1.339E-04 (  944,  0) 13:42:09   21.8 s     2.8 s  91.7%    F
     9    1.57514   1.512E-04 2.600E-03 (  944,  2)   1.304E-04 (  517,  0) 13:42:12   24.7 s     2.9 s  95.3%    F
    10    1.57491   1.481E-04 1.090E-03 (  944,  3)   1.262E-04 (  947,  0) 13:42:15   27.5 s     2.9 s  95.3%    F
    11    1.57469   1.383E-04 4.690E-04 (  584,  3)   1.189E-04 (  517,  0) 13:42:17   30.0 s     2.4 s 120.5%    F
    12    1.57450   1.239E-04 2.190E-04 (  944,  3)   1.095E-04 (  947,  0) 13:42:19   32.1 s     2.2 s 109.0%    F
    13    1.57433   1.085E-04 1.211E-04 (  944,  3)   1.002E-04 (  947,  0) 13:42:22   34.7 s     2.5 s  84.0%    F
    14    1.57418   9.225E-05 1.042E-04 (  272,238)   9.010E-05 (  947,  0) 13:42:24   37.0 s     2.3 s 115.0%    F
    15    1.57405   8.112E-05 9.449E-05 (  272,238)   8.190E-05 (  517,  0) 13:42:26   38.4 s     1.5 s  74.0%    F
 k-eff =       1.57405385     Time=    252.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.328
 Inscatter Source  :     0.232
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.084
 Total (per outer):      2.644

  Total iteration time breakdown (sec):
 Transport Sweeping:    34.915
 Inscatter Source  :     3.479
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.262
 Total Time        :    39.656

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.57294E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:45:13

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.57405   8.112E-05 7.858E-01 (  242,  2)   2.584E-03 (  948,  0) 13:45:15    2.7 s     2.7 s 133.0%    F
     2    1.57426   1.279E-04 7.372E-01 (  242,  2)   3.109E-04 (  242,  0) 13:45:18    5.4 s     2.7 s  90.7%    F
     3    1.57427   7.107E-06 3.542E-01 (   14,  2)   9.268E-05 (  584,  0) 13:45:21    8.1 s     2.7 s  91.0%    F
     4    1.57420   4.386E-05 1.667E-01 (  584,  2)   1.074E-04 (  242,  0) 13:45:24   10.9 s     2.8 s  93.3%    F
     5    1.57407   7.979E-05 7.104E-02 (  944,  2)   1.206E-04 (   14,  0) 13:45:26   13.6 s     2.7 s 133.0%    F
     6    1.57391   1.038E-04 3.089E-02 (  584,  2)   1.299E-04 (  944,  0) 13:45:29   16.3 s     2.7 s  90.0%    F
     7    1.57372   1.209E-04 1.325E-02 (  944,  2)   1.318E-04 (  944,  0) 13:45:32   18.9 s     2.6 s  87.0%    F
     8    1.57350   1.361E-04 5.549E-03 (  584,  2)   1.305E-04 (  584,  0) 13:45:34   21.4 s     2.5 s 127.0%    F
     9    1.57328   1.433E-04 2.321E-03 (  944,  2)   1.266E-04 (  947,  0) 13:45:37   24.0 s     2.6 s  87.0%    F
    10    1.57306   1.415E-04 9.699E-04 (  584,  3)   1.230E-04 (  947,  0) 13:45:39   26.6 s     2.6 s 128.5%    F
    11    1.57285   1.330E-04 4.152E-04 (  944,  3)   1.163E-04 (  517,  0) 13:45:42   29.2 s     2.6 s  85.7%    F
    12    1.57266   1.204E-04 1.934E-04 (  584,  3)   1.080E-04 (  947,  0) 13:45:44   31.1 s     1.9 s  96.0%    F
    13    1.57249   1.057E-04 1.119E-04 (  870,238)   9.872E-05 (  517,  0) 13:45:46   33.2 s     2.2 s 107.5%    F
    14    1.57235   9.072E-05 1.028E-04 (  870,238)   8.951E-05 (  947,  0) 13:45:47   34.7 s     1.4 s 143.0%    F
 k-eff =       1.57234844     Time=    297.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.245
 Inscatter Source  :     0.228
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.085
 Total (per outer):      2.558

  Total iteration time breakdown (sec):
 Transport Sweeping:    31.429
 Inscatter Source  :     3.186
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.190
 Total Time        :    35.805

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.57110E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:48:33

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.57235   9.072E-05 1.000E+00 (    1,  1)   2.654E-03 (  581,  0) 13:48:36    2.7 s     2.7 s  89.3%    F
     2    1.57256   1.340E-04 1.110E+00 (   14,  1)   3.309E-04 (   14,  0) 13:48:38    5.3 s     2.6 s 132.5%    F
     3    1.57257   9.365E-06 7.116E-01 (  242,  1)   9.306E-05 (  584,  0) 13:48:41    8.0 s     2.6 s  88.0%    F
     4    1.57251   4.349E-05 4.086E-01 (  944,  1)   1.086E-04 (   14,  0) 13:48:43   10.6 s     2.6 s 131.0%    F
     5    1.57238   8.056E-05 2.034E-01 (  944,  1)   1.230E-04 (   14,  0) 13:48:46   13.2 s     2.6 s  87.7%    F
     6    1.57221   1.056E-04 9.702E-02 (  584,  1)   1.329E-04 (  944,  0) 13:48:49   15.9 s     2.7 s  89.7%    F
     7    1.57202   1.241E-04 4.413E-02 (  944,  1)   1.347E-04 (  584,  0) 13:48:51   18.5 s     2.6 s 130.0%    F
     8    1.57180   1.405E-04 1.945E-02 (  584,  1)   1.335E-04 (  584,  0) 13:48:54   21.1 s     2.6 s  85.3%    F
     9    1.57156   1.481E-04 8.527E-03 (  944,  1)   1.293E-04 (  517,  0) 13:48:57   23.7 s     2.6 s  87.0%    F
    10    1.57133   1.465E-04 3.722E-03 (  944,  1)   1.257E-04 (  947,  0) 13:48:59   26.3 s     2.6 s 130.0%    F
    11    1.57112   1.378E-04 1.631E-03 (  584,  1)   1.189E-04 (  947,  0) 13:49:02   28.9 s     2.6 s  86.0%    F
    12    1.57092   1.246E-04 7.324E-04 (  944,  1)   1.103E-04 (  517,  0) 13:49:04   30.9 s     2.0 s 100.0%    F
    13    1.57075   1.095E-04 3.484E-04 (  584,  1)   1.009E-04 (  947,  0) 13:49:06   33.2 s     2.3 s 115.5%    F
    14    1.57060   9.353E-05 1.851E-04 (  944,  1)   9.096E-05 (  517,  0) 13:49:08   34.7 s     1.5 s  76.5%    F
 k-eff =       1.57060276     Time=    343.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.249
 Inscatter Source  :     0.225
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.086
 Total (per outer):      2.559

  Total iteration time breakdown (sec):
 Transport Sweeping:    31.480
 Inscatter Source  :     3.149
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.200
 Total Time        :    35.829

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56935E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:51:56

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.57060   9.353E-05 7.295E-01 (   14,  2)   2.717E-03 (  948,  0) 13:51:59    2.7 s     2.7 s  90.3%    F
     2    1.57083   1.421E-04 6.454E-01 (  242,  2)   3.485E-04 (   14,  0) 13:52:01    5.4 s     2.7 s 133.0%    F
     3    1.57085   1.548E-05 2.995E-01 (  242,  2)   9.076E-05 (  944,  0) 13:52:04    8.0 s     2.7 s  88.3%    F
     4    1.57079   3.972E-05 1.387E-01 (  584,  2)   1.067E-04 (   14,  0) 13:52:07   10.7 s     2.7 s  88.7%    F
     5    1.57066   7.827E-05 5.913E-02 (  584,  1)   1.184E-04 (   14,  0) 13:52:09   13.3 s     2.7 s 133.0%    F
     6    1.57050   1.041E-04 2.640E-02 (  944,  1)   1.350E-04 (  242,  0) 13:52:12   16.0 s     2.7 s  89.3%    F
     7    1.57031   1.227E-04 1.162E-02 (  584,  1)   1.346E-04 (  584,  0) 13:52:15   18.7 s     2.7 s  88.7%    F
     8    1.57009   1.398E-04 5.006E-03 (  944,  1)   1.341E-04 (  584,  0) 13:52:17   21.3 s     2.6 s 129.0%    F
     9    1.56986   1.483E-04 2.141E-03 (  584,  1)   1.297E-04 (  947,  0) 13:52:20   23.9 s     2.6 s  88.0%    F
    10    1.56963   1.473E-04 9.107E-04 (  584,  1)   1.263E-04 (  947,  0) 13:52:23   26.5 s     2.6 s  86.0%    F
    11    1.56941   1.389E-04 3.961E-04 (  944,  1)   1.197E-04 (  517,  0) 13:52:25   29.0 s     2.6 s 127.5%    F
    12    1.56921   1.259E-04 1.894E-04 (  584,  1)   1.111E-04 (  947,  0) 13:52:27   31.1 s     2.1 s 105.0%    F
    13    1.56904   1.108E-04 1.152E-04 (  870,238)   1.016E-04 (  517,  0) 13:52:30   33.4 s     2.3 s  76.7%    F
    14    1.56889   9.465E-05 1.056E-04 (  272,238)   9.162E-05 (  517,  0) 13:52:32   36.0 s     2.5 s 127.0%    F
 k-eff =       1.56888732     Time=    388.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.339
 Inscatter Source  :     0.226
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.086
 Total (per outer):      2.652

  Total iteration time breakdown (sec):
 Transport Sweeping:    32.751
 Inscatter Source  :     3.169
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.205
 Total Time        :    37.125

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56763E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:55:21

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56889   9.465E-05 7.037E-01 (  242,  2)   2.776E-03 (  581,  0) 13:55:23    2.8 s     2.8 s 138.0%    F
     2    1.56912   1.494E-04 6.087E-01 (  242,  2)   3.625E-04 (  242,  0) 13:55:26    5.5 s     2.7 s  90.7%    F
     3    1.56915   2.104E-05 2.777E-01 (   14,  2)   8.722E-05 (  584,  0) 13:55:29    8.2 s     2.7 s  89.7%    F
     4    1.56910   3.680E-05 1.275E-01 (  584,  2)   1.062E-04 (  242,  0) 13:55:31   10.9 s     2.7 s 135.0%    F
     5    1.56898   7.627E-05 5.487E-02 (  944,  1)   1.206E-04 (   14,  0) 13:55:34   13.5 s     2.6 s  87.3%    F
     6    1.56882   1.033E-04 2.445E-02 (  584,  1)   1.331E-04 (  944,  0) 13:55:37   16.1 s     2.6 s  88.3%    F
     7    1.56862   1.223E-04 1.076E-02 (  584,  1)   1.352E-04 (  584,  0) 13:55:39   18.8 s     2.7 s 134.0%    F
     8    1.56840   1.402E-04 4.625E-03 (  584,  1)   1.352E-04 (  584,  0) 13:55:42   21.4 s     2.5 s  84.7%    F
     9    1.56817   1.495E-04 1.971E-03 (  584,  1)   1.306E-04 (  947,  0) 13:55:45   24.0 s     2.6 s  88.3%    F
    10    1.56794   1.491E-04 8.339E-04 (  944,  1)   1.275E-04 (  517,  0) 13:55:47   26.6 s     2.6 s 131.5%    F
    11    1.56771   1.410E-04 3.609E-04 (  584,  1)   1.209E-04 (  947,  0) 13:55:50   29.2 s     2.5 s  84.0%    F
    12    1.56751   1.276E-04 1.735E-04 (  944,  1)   1.120E-04 (  947,  0) 13:55:52   31.2 s     2.0 s 100.0%    F
    13    1.56734   1.125E-04 1.163E-04 (  272,238)   1.026E-04 (  517,  0) 13:55:54   33.5 s     2.3 s 116.5%    F
    14    1.56719   9.615E-05 1.066E-04 (  870,238)   9.249E-05 (  947,  0) 13:55:57   36.0 s     2.5 s  84.7%    F
 k-eff =       1.56718710     Time=    434.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.344
 Inscatter Source  :     0.225
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.086
 Total (per outer):      2.655

  Total iteration time breakdown (sec):
 Transport Sweeping:    32.820
 Inscatter Source  :     3.145
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.201
 Total Time        :    37.166

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56596E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:58:46

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56719   9.615E-05 6.790E-01 (  242,  2)   2.834E-03 (  948,  0) 13:58:49    2.7 s     2.7 s  89.7%    F
     2    1.56743   1.546E-04 5.752E-01 (  242,  2)   3.738E-04 (   14,  0) 13:58:51    5.4 s     2.8 s 137.5%    F
     3    1.56747   2.504E-05 2.585E-01 (   14,  2)   8.500E-05 (  584,  0) 13:58:54    8.1 s     2.7 s  88.3%    F
     4    1.56741   3.477E-05 1.177E-01 (  584,  2)   1.055E-04 (   14,  0) 13:58:57   10.8 s     2.7 s  88.7%    F
     5    1.56730   7.524E-05 5.106E-02 (  584,  1)   1.225E-04 (   14,  0) 13:58:59   13.3 s     2.6 s 129.5%    F
     6    1.56713   1.032E-04 2.271E-02 (  944,  1)   1.328E-04 (  584,  0) 13:59:02   16.0 s     2.6 s  88.3%    F
     7    1.56694   1.226E-04 9.987E-03 (  584,  1)   1.363E-04 (  944,  0) 13:59:05   18.6 s     2.6 s  88.0%    F
     8    1.56672   1.412E-04 4.286E-03 (  584,  1)   1.365E-04 (  584,  0) 13:59:07   21.2 s     2.5 s 127.0%    F
     9    1.56648   1.512E-04 1.820E-03 (  944,  1)   1.317E-04 (  517,  0) 13:59:10   23.8 s     2.6 s  88.3%    F
    10    1.56625   1.512E-04 7.655E-04 (  944,  1)   1.287E-04 (  947,  0) 13:59:12   26.4 s     2.6 s 130.5%    F
    11    1.56602   1.432E-04 3.298E-04 (  944,  1)   1.222E-04 (  947,  0) 13:59:15   29.0 s     2.5 s  84.0%    F
    12    1.56582   1.298E-04 1.594E-04 (  584,  1)   1.132E-04 (  947,  0) 13:59:17   31.1 s     2.1 s 106.0%    F
    13    1.56564   1.144E-04 1.175E-04 (  870,238)   1.037E-04 (  517,  0) 13:59:19   33.4 s     2.4 s 118.5%    F
    14    1.56549   9.782E-05 1.078E-04 (  272,238)   9.342E-05 (  947,  0) 13:59:22   36.0 s     2.6 s  85.3%    F
 k-eff =       1.56548779     Time=    479.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.341
 Inscatter Source  :     0.226
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.086
 Total (per outer):      2.653

  Total iteration time breakdown (sec):
 Transport Sweeping:    32.772
 Inscatter Source  :     3.164
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.201
 Total Time        :    37.137

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56425E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 14:02:12

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56549   9.782E-05 6.556E-01 (  242,  2)   2.894E-03 (  948,  0) 14:02:14    2.6 s     2.6 s 132.0%    F
     2    1.56574   1.595E-04 5.445E-01 (   14,  2)   3.841E-04 (   14,  0) 14:02:17    5.3 s     2.7 s  88.7%    F
     3    1.56578   2.888E-05 2.414E-01 (  242,  2)   8.345E-05 (  584,  0) 14:02:20    8.0 s     2.7 s  88.7%    F
     4    1.56573   3.291E-05 1.100E-01 (  944,  1)   1.047E-04 (   14,  0) 14:02:22   10.6 s     2.7 s 133.5%    F
     5    1.56561   7.444E-05 4.764E-02 (  584,  1)   1.231E-04 (   14,  0) 14:02:25   13.2 s     2.6 s  85.3%    F
     6    1.56545   1.031E-04 2.116E-02 (  584,  1)   1.340E-04 (  584,  0) 14:02:27   15.9 s     2.7 s 133.5%    F
     7    1.56526   1.233E-04 9.297E-03 (  944,  1)   1.368E-04 (  944,  0) 14:02:30   18.5 s     2.7 s  89.0%    F
     8    1.56504   1.426E-04 3.982E-03 (  944,  1)   1.379E-04 (  944,  0) 14:02:33   21.1 s     2.6 s  85.3%    F
     9    1.56480   1.532E-04 1.684E-03 (  584,  1)   1.329E-04 (  584,  0) 14:02:35   23.7 s     2.6 s 132.0%    F
    10    1.56456   1.535E-04 7.040E-04 (  944,  1)   1.301E-04 (  947,  0) 14:02:38   26.3 s     2.6 s  87.0%    F
    11    1.56433   1.456E-04 3.019E-04 (  584,  1)   1.235E-04 (  517,  0) 14:02:40   28.9 s     2.5 s 126.0%    F
    12    1.56412   1.321E-04 1.468E-04 (  944,  1)   1.145E-04 (  947,  0) 14:02:43   31.1 s     2.2 s  73.7%    F
    13    1.56394   1.165E-04 1.188E-04 (  272,238)   1.049E-04 (  947,  0) 14:02:45   33.5 s     2.4 s 120.0%    F
    14    1.56378   9.964E-05 1.090E-04 (  870,238)   9.445E-05 (  517,  0) 14:02:48   36.0 s     2.6 s  85.7%    F
 k-eff =       1.56378466     Time=    525.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.348
 Inscatter Source  :     0.223
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.086
 Total (per outer):      2.656

  Total iteration time breakdown (sec):
 Transport Sweeping:    32.866
 Inscatter Source  :     3.119
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.198
 Total Time        :    37.183

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56251E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 14:05:39

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56378   9.964E-05 6.332E-01 (   14,  2)   2.950E-03 (  948,  0) 14:05:42    2.7 s     2.7 s  89.7%    F
     2    1.56404   1.635E-04 5.163E-01 (  242,  2)   3.929E-04 (  242,  0) 14:05:45    5.4 s     2.7 s  89.7%    F
     3    1.56409   3.203E-05 2.260E-01 (   14,  2)   8.260E-05 (  584,  0) 14:05:47    8.1 s     2.7 s 136.5%    F
     4    1.56404   3.150E-05 1.031E-01 (  584,  1)   1.048E-04 (  242,  0) 14:05:50   10.8 s     2.7 s  89.0%    F
     5    1.56393   7.405E-05 4.456E-02 (  944,  1)   1.213E-04 (  242,  0) 14:05:53   13.3 s     2.6 s  85.0%    F
     6    1.56376   1.035E-04 1.976E-02 (  584,  1)   1.365E-04 (   14,  0) 14:05:55   16.0 s     2.7 s 133.5%    F
     7    1.56357   1.242E-04 8.676E-03 (  944,  1)   1.383E-04 (  584,  0) 14:05:58   18.7 s     2.7 s  89.0%    F
     8    1.56334   1.443E-04 3.708E-03 (  944,  1)   1.393E-04 (  944,  0) 14:06:01   21.2 s     2.6 s  85.3%    F
     9    1.56310   1.554E-04 1.562E-03 (  584,  1)   1.344E-04 (  584,  0) 14:06:03   23.9 s     2.6 s 132.5%    F
    10    1.56286   1.559E-04 6.489E-04 (  944,  1)   1.314E-04 (  517,  0) 14:06:06   26.5 s     2.6 s  87.7%    F
    11    1.56263   1.480E-04 2.769E-04 (  944,  1)   1.249E-04 (  947,  0) 14:06:08   29.1 s     2.6 s 128.0%    F
    12    1.56242   1.344E-04 1.355E-04 (  944,  1)   1.158E-04 (  947,  0) 14:06:11   31.3 s     2.2 s  73.3%    F
    13    1.56223   1.185E-04 1.201E-04 (  272,238)   1.060E-04 (  517,  0) 14:06:13   33.7 s     2.5 s 122.5%    F
    14    1.56207   1.014E-04 1.102E-04 (  272,238)   9.544E-05 (  517,  0) 14:06:16   36.3 s     2.6 s  87.0%    F
    15    1.56194   8.501E-05 9.975E-05 (  870,238)   8.544E-05 (  947,  0) 14:06:18   38.5 s     2.1 s 107.5%    F
 k-eff =       1.56193958     Time=    570.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.340
 Inscatter Source  :     0.224
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.080
 Total (per outer):      2.644

  Total iteration time breakdown (sec):
 Transport Sweeping:    35.103
 Inscatter Source  :     3.358
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.197
 Total Time        :    39.658

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56079E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 14:09:12

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56194   8.501E-05 6.120E-01 (  242,  2)   3.002E-03 (  948,  0) 14:09:15    2.8 s     2.8 s  94.0%    F
     2    1.56221   1.752E-04 4.906E-01 (   14,  2)   4.090E-04 (  242,  0) 14:09:18    5.6 s     2.8 s  92.7%    F
     3    1.56228   4.432E-05 2.124E-01 (  242,  2)   7.474E-05 (  584,  0) 14:09:21    8.4 s     2.8 s  92.0%    F
     4    1.56225   2.400E-05 9.702E-02 (  944,  1)   9.941E-05 (   14,  0) 14:09:23   11.2 s     2.8 s 140.5%    F
 k-eff =       1.56224503     Time=    616.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.548
 Inscatter Source  :     0.234
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.307
 Total (per outer):      3.089

  Total iteration time breakdown (sec):
 Transport Sweeping:    10.191
 Inscatter Source  :     0.937
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.230
 Total Time        :    12.358

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.55904E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 14:12:20

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56225   2.400E-05 5.699E-01 (  242,  2)   3.095E-03 (  584,  0) 14:12:23    2.8 s     2.8 s  92.7%    F
     2    1.56248   1.487E-04 4.734E-01 (  242,  2)   3.458E-04 (   14,  0) 14:12:26    5.5 s     2.8 s  92.0%    F
     3    1.56244   2.292E-05 2.041E-01 (   14,  2)   1.585E-04 (  584,  0) 14:12:29    8.3 s     2.8 s  92.7%    F
     4    1.56229   9.676E-05 9.409E-02 (  584,  1)   1.875E-04 (  242,  0) 14:12:31   11.0 s     2.7 s 135.5%    F
     5    1.56206   1.497E-04 4.056E-02 (  584,  1)   2.103E-04 (  242,  0) 14:12:34   13.8 s     2.8 s  92.0%    F
     6    1.56172   2.165E-04 1.776E-02 (  584,  1)   2.172E-04 (  944,  0) 14:12:37   16.5 s     2.7 s  90.7%    F
     7    1.56130   2.705E-04 7.559E-03 (  944,  1)   2.184E-04 (  584,  0) 14:12:40   19.1 s     2.6 s  88.0%    F
     8    1.56083   2.980E-04 3.111E-03 (  944,  1)   2.104E-04 (  944,  0) 14:12:42   21.8 s     2.6 s 132.0%    F
     9    1.56036   3.003E-04 1.270E-03 (  584,  1)   2.046E-04 (  947,  0) 14:12:45   24.4 s     2.6 s  87.7%    F
    10    1.55992   2.841E-04 5.323E-04 (  944,  1)   1.937E-04 (  947,  0) 14:12:47   26.9 s     2.5 s 122.5%    F
    11    1.55952   2.562E-04 2.560E-04 (  584,  1)   1.780E-04 (  517,  0) 14:12:50   29.5 s     2.6 s  87.7%    F
    12    1.55917   2.223E-04 1.853E-04 (  272,238)   1.596E-04 (  947,  0) 14:12:53   32.1 s     2.6 s  87.7%    F
    13    1.55888   1.868E-04 1.676E-04 (  870,238)   1.405E-04 (  947,  0) 14:12:55   34.8 s     2.6 s 132.0%    F
    14    1.55864   1.527E-04 1.484E-04 (  272,238)   1.218E-04 (  517,  0) 14:12:58   37.5 s     2.7 s  91.0%    F
    15    1.55845   1.219E-04 1.296E-04 (  242,  1)   1.045E-04 (  517,  0) 14:13:01   40.2 s     2.7 s  88.3%    F
    16    1.55831   9.528E-05 1.195E-04 (   14,  1)   8.915E-05 (  947,  0) 14:13:03   42.8 s     2.6 s 132.0%    F
    17    1.55819   7.466E-05 9.551E-05 (  242,  1)   7.583E-05 (  517,  0) 14:13:06   45.4 s     2.6 s  88.0%    F
 k-eff =       1.55818921     Time=    661.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.444
 Inscatter Source  :     0.227
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.074
 Total (per outer):      2.745

  Total iteration time breakdown (sec):
 Transport Sweeping:    41.549
 Inscatter Source  :     3.861
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.256
 Total Time        :    46.666

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.55727E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 14:15:58

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.55819   7.466E-05 5.728E-01 (  242,  2)   3.095E-03 (  581,  0) 14:16:00    2.6 s     2.6 s 131.0%    F
     2    1.55850   1.970E-04 4.452E-01 (  242,  2)   4.397E-04 (  242,  0) 14:16:03    5.3 s     2.7 s  89.0%    F
     3    1.55861   7.011E-05 1.894E-01 (   14,  1)   6.219E-05 (  776,  0) 14:16:06    7.9 s     2.7 s  88.3%    F
     4    1.55859   7.763E-06 8.644E-02 (  584,  1)   8.622E-05 (   14,  0) 14:16:08   10.6 s     2.7 s 135.5%    F
 k-eff =       1.55859341     Time=    707.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.431
 Inscatter Source  :     0.221
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.292
 Total (per outer):      2.943

  Total iteration time breakdown (sec):
 Transport Sweeping:     9.723
 Inscatter Source  :     0.883
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.168
 Total Time        :    11.774

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.55556E+00
 Equivalent core height is infinite.
cp /tmp/scale.ybb.57393/StdCmpMix00001 /home/ybb/SCALE_beta/MSRE/MSRE_beta_100/MSRE_beta_100.stdcmp_m1
