SCALE Job started on Thu 08/08/2019 13:10:56
With Host name node40
working directory /tmp/scale.ybb.57441
and process id 57441.
Input file named /home/ybb/SCALE_beta/MSRE/MSRE_beta_60/MSRE_beta_60.inp
and output file named /home/ybb/SCALE_beta/MSRE/MSRE_beta_60/MSRE_beta_60.out
##########################################################
***Created 2 infinite homogeneous cells from unreferenced mixtures.
>>> Loading SCALE Standard Composition Library from /scale/release/6.3b4/linux/data/scale.rev40.sclib
>>> Loading CE library /scale/release/6.3b4/linux/data/ce_v7.1_endf.xml
***Warning:  iterp value not set correctly from XSProc cell data!  Setting to default...
                          (This is expected if you are using the timetable block in TRITON.)
Loading      nuclide       li-6 @ 900K
Loading      nuclide       li-6 @ 1200K
Broadening   nuclide       li-6 @ 922.039K
Loading      nuclide       li-7 @ 900K
Loading      nuclide       li-7 @ 1200K
Broadening   nuclide       li-7 @ 922.039K
Loading      nuclide       be-9 @ 900K
Loading      nuclide       be-9 @ 1200K
Broadening   nuclide       be-9 @ 922.039K
Loading      nuclide       f-19 @ 900K
Loading      nuclide       f-19 @ 1200K
Broadening   nuclide       f-19 @ 922.039K
Loading      nuclide      zr-90 @ 900K
Loading      nuclide      zr-90 @ 1200K
Broadening   nuclide      zr-90 @ 922.039K
Loading      nuclide      zr-91 @ 900K
Loading      nuclide      zr-91 @ 1200K
Broadening   nuclide      zr-91 @ 922.039K
Loading      nuclide      zr-92 @ 900K
Loading      nuclide      zr-92 @ 1200K
Broadening   nuclide      zr-92 @ 922.039K
Loading      nuclide      zr-94 @ 900K
Loading      nuclide      zr-94 @ 1200K
Broadening   nuclide      zr-94 @ 922.039K
Loading      nuclide      zr-96 @ 900K
Loading      nuclide      zr-96 @ 1200K
Broadening   nuclide      zr-96 @ 922.039K
Loading      nuclide      u-235 @ 900K
Loading      nuclide      u-235 @ 1200K
Broadening   nuclide      u-235 @ 922.039K
Loading      nuclide      u-238 @ 900K
Loading      nuclide      u-238 @ 1200K
Broadening   nuclide      u-238 @ 922.039K
Loading      nuclide      u-234 @ 900K
Loading      nuclide      u-234 @ 1200K
Broadening   nuclide      u-234 @ 922.039K
Loading      nuclide      u-236 @ 900K
Loading      nuclide      u-236 @ 1200K
Broadening   nuclide      u-236 @ 922.039K
Loading      nuclide     np-237 @ 900K
Loading      nuclide     np-237 @ 1200K
Broadening   nuclide     np-237 @ 922.039K
Loading      nuclide     pu-238 @ 900K
Loading      nuclide     pu-238 @ 1200K
Broadening   nuclide     pu-238 @ 922.039K
Loading      nuclide     pu-239 @ 900K
Loading      nuclide     pu-239 @ 1200K
Broadening   nuclide     pu-239 @ 922.039K
Loading      nuclide     pu-240 @ 900K
Loading      nuclide     pu-240 @ 1200K
Broadening   nuclide     pu-240 @ 922.039K
Loading      nuclide     pu-241 @ 900K
Loading      nuclide     pu-241 @ 1200K
Broadening   nuclide     pu-241 @ 922.039K
Loading      nuclide     pu-242 @ 900K
Loading      nuclide     pu-242 @ 1200K
Broadening   nuclide     pu-242 @ 922.039K
Loading      nuclide     am-241 @ 900K
Loading      nuclide     am-241 @ 1200K
Broadening   nuclide     am-241 @ 922.039K
Loading      nuclide     am-242 @ 900K
Loading      nuclide     am-242 @ 1200K
Broadening   nuclide     am-242 @ 922.039K
Loading      nuclide     am-243 @ 900K
Loading      nuclide     am-243 @ 1200K
Broadening   nuclide     am-243 @ 922.039K
Loading      nuclide     cm-242 @ 900K
Loading      nuclide     cm-242 @ 1200K
Broadening   nuclide     cm-242 @ 922.039K
Loading      nuclide     cm-243 @ 900K
Loading      nuclide     cm-243 @ 1200K
Broadening   nuclide     cm-243 @ 922.039K
Loading      nuclide     cm-244 @ 900K
Loading      nuclide     cm-244 @ 1200K
Broadening   nuclide     cm-244 @ 922.039K
Loading      nuclide     xe-135 @ 900K
Loading      nuclide     xe-135 @ 1200K
Broadening   nuclide     xe-135 @ 922.039K
Loading      nuclide     cs-133 @ 900K
Loading      nuclide     cs-133 @ 1200K
Broadening   nuclide     cs-133 @ 922.039K
Loading      nuclide      nb-93 @ 900K
Loading      nuclide      nb-93 @ 1200K
Broadening   nuclide      nb-93 @ 922.039K
Loading      nuclide      mo-95 @ 900K
Loading      nuclide      mo-95 @ 1200K
Broadening   nuclide      mo-95 @ 922.039K
Loading      nuclide      tc-99 @ 900K
Loading      nuclide      tc-99 @ 1200K
Broadening   nuclide      tc-99 @ 922.039K
Loading      nuclide     ru-106 @ 900K
Loading      nuclide     ru-106 @ 1200K
Broadening   nuclide     ru-106 @ 922.039K
Loading      nuclide     rh-103 @ 900K
Loading      nuclide     rh-103 @ 1200K
Broadening   nuclide     rh-103 @ 922.039K
Loading      nuclide     rh-105 @ 900K
Loading      nuclide     rh-105 @ 1200K
Broadening   nuclide     rh-105 @ 922.039K
Loading      nuclide     sn-126 @ 900K
Loading      nuclide     sn-126 @ 1200K
Broadening   nuclide     sn-126 @ 922.039K
Loading      nuclide     xe-131 @ 900K
Loading      nuclide     xe-131 @ 1200K
Broadening   nuclide     xe-131 @ 922.039K
Loading      nuclide     cs-134 @ 900K
Loading      nuclide     cs-134 @ 1200K
Broadening   nuclide     cs-134 @ 922.039K
Loading      nuclide     cs-135 @ 900K
Loading      nuclide     cs-135 @ 1200K
Broadening   nuclide     cs-135 @ 922.039K
Loading      nuclide     cs-137 @ 900K
Loading      nuclide     cs-137 @ 1200K
Broadening   nuclide     cs-137 @ 922.039K
Loading      nuclide     ce-144 @ 900K
Loading      nuclide     ce-144 @ 1200K
Broadening   nuclide     ce-144 @ 922.039K
Loading      nuclide     pr-143 @ 900K
Loading      nuclide     pr-143 @ 1200K
Broadening   nuclide     pr-143 @ 922.039K
Loading      nuclide     nd-143 @ 900K
Loading      nuclide     nd-143 @ 1200K
Broadening   nuclide     nd-143 @ 922.039K
Loading      nuclide     nd-145 @ 900K
Loading      nuclide     nd-145 @ 1200K
Broadening   nuclide     nd-145 @ 922.039K
Loading      nuclide     nd-146 @ 900K
Loading      nuclide     nd-146 @ 1200K
Broadening   nuclide     nd-146 @ 922.039K
Loading      nuclide     nd-147 @ 900K
Loading      nuclide     nd-147 @ 1200K
Broadening   nuclide     nd-147 @ 922.039K
Loading      nuclide     nd-148 @ 900K
Loading      nuclide     nd-148 @ 1200K
Broadening   nuclide     nd-148 @ 922.039K
Loading      nuclide     pm-147 @ 900K
Loading      nuclide     pm-147 @ 1200K
Broadening   nuclide     pm-147 @ 922.039K
Loading      nuclide     pm-149 @ 900K
Loading      nuclide     pm-149 @ 1200K
Broadening   nuclide     pm-149 @ 922.039K
Loading      nuclide     sm-147 @ 900K
Loading      nuclide     sm-147 @ 1200K
Broadening   nuclide     sm-147 @ 922.039K
Loading      nuclide     sm-149 @ 900K
Loading      nuclide     sm-149 @ 1200K
Broadening   nuclide     sm-149 @ 922.039K
Loading      nuclide     sm-150 @ 900K
Loading      nuclide     sm-150 @ 1200K
Broadening   nuclide     sm-150 @ 922.039K
Loading      nuclide     sm-151 @ 900K
Loading      nuclide     sm-151 @ 1200K
Broadening   nuclide     sm-151 @ 922.039K
Loading      nuclide     sm-152 @ 900K
Loading      nuclide     sm-152 @ 1200K
Broadening   nuclide     sm-152 @ 922.039K
Loading      nuclide     eu-151 @ 900K
Loading      nuclide     eu-151 @ 1200K
Broadening   nuclide     eu-151 @ 922.039K
Loading      nuclide     eu-153 @ 900K
Loading      nuclide     eu-153 @ 1200K
Broadening   nuclide     eu-153 @ 922.039K
Loading      nuclide     eu-154 @ 900K
Loading      nuclide     eu-154 @ 1200K
Broadening   nuclide     eu-154 @ 922.039K
Loading      nuclide     eu-155 @ 900K
Loading      nuclide     eu-155 @ 1200K
Broadening   nuclide     eu-155 @ 922.039K
Loading      nuclide     gd-154 @ 900K
Loading      nuclide     gd-154 @ 1200K
Broadening   nuclide     gd-154 @ 922.039K
Loading      nuclide     gd-155 @ 900K
Loading      nuclide     gd-155 @ 1200K
Broadening   nuclide     gd-155 @ 922.039K
Loading      nuclide     gd-157 @ 900K
Loading      nuclide     gd-157 @ 1200K
Broadening   nuclide     gd-157 @ 922.039K
Loading      nuclide     gd-158 @ 900K
Loading      nuclide     gd-158 @ 1200K
Broadening   nuclide     gd-158 @ 922.039K
Loading      nuclide     gd-160 @ 900K
Loading      nuclide     gd-160 @ 1200K
Broadening   nuclide     gd-160 @ 922.039K
Loading      nuclide        h-1 @ 800K
Loading      nuclide       b-10 @ 900K
Loading      nuclide       b-10 @ 1200K
Broadening   nuclide       b-10 @ 922.039K
Loading      nuclide       b-11 @ 900K
Loading      nuclide       b-11 @ 1200K
Broadening   nuclide       b-11 @ 922.039K
Loading      nuclide       n-14 @ 900K
Loading      nuclide       n-14 @ 1200K
Broadening   nuclide       n-14 @ 922.039K
Loading      nuclide       o-16 @ 900K
Loading      nuclide       o-16 @ 1200K
Broadening   nuclide       o-16 @ 922.039K
Loading      nuclide      kr-83 @ 900K
Loading      nuclide      kr-83 @ 1200K
Broadening   nuclide      kr-83 @ 922.039K
Loading      nuclide     ag-109 @ 900K
Loading      nuclide     ag-109 @ 1200K
Broadening   nuclide     ag-109 @ 922.039K
Loading      nuclide      i-135 @ 900K
Loading      nuclide      i-135 @ 1200K
Broadening   nuclide      i-135 @ 922.039K
Loading      nuclide     pm-148 @ 900K
Loading      nuclide     pm-148 @ 1200K
Broadening   nuclide     pm-148 @ 922.039K
Loading      nuclide     gd-152 @ 900K
Loading      nuclide     gd-152 @ 1200K
Broadening   nuclide     gd-152 @ 922.039K
Loading      nuclide     gd-156 @ 900K
Loading      nuclide     gd-156 @ 1200K
Broadening   nuclide     gd-156 @ 922.039K
Loading      nuclide     xe-133 @ 900K
Loading      nuclide     xe-133 @ 1200K
Broadening   nuclide     xe-133 @ 922.039K
Loading      nuclide     cd-113 @ 900K
Loading      nuclide     cd-113 @ 1200K
Broadening   nuclide     cd-113 @ 922.039K
Loading      nuclide     ce-141 @ 900K
Loading      nuclide     ce-141 @ 1200K
Broadening   nuclide     ce-141 @ 922.039K
Loading      nuclide     ru-101 @ 900K
Loading      nuclide     ru-101 @ 1200K
Broadening   nuclide     ru-101 @ 922.039K
Loading      nuclide     sm-153 @ 900K
Loading      nuclide     sm-153 @ 1200K
Broadening   nuclide     sm-153 @ 922.039K
Loading      nuclide     ru-103 @ 900K
Loading      nuclide     ru-103 @ 1200K
Broadening   nuclide     ru-103 @ 922.039K
Loading      nuclide     la-139 @ 900K
Loading      nuclide     la-139 @ 1200K
Broadening   nuclide     la-139 @ 922.039K
Loading      nuclide     ce-143 @ 900K
Loading      nuclide     ce-143 @ 1200K
Broadening   nuclide     ce-143 @ 922.039K
Loading      nuclide      zr-93 @ 900K
Loading      nuclide      zr-93 @ 1200K
Broadening   nuclide      zr-93 @ 922.039K
Loading      nuclide      mo-99 @ 900K
Loading      nuclide      mo-99 @ 1200K
Broadening   nuclide      mo-99 @ 922.039K
Loading      nuclide      mo-97 @ 900K
Loading      nuclide      mo-97 @ 1200K
Broadening   nuclide      mo-97 @ 922.039K
Loading      nuclide      mo-98 @ 900K
Loading      nuclide      mo-98 @ 1200K
Broadening   nuclide      mo-98 @ 922.039K
Loading      nuclide     ba-140 @ 900K
Loading      nuclide     ba-140 @ 1200K
Broadening   nuclide     ba-140 @ 922.039K
Loading      nuclide      i-129 @ 900K
Loading      nuclide      i-129 @ 1200K
Broadening   nuclide      i-129 @ 922.039K
Loading      nuclide     pd-105 @ 900K
Loading      nuclide     pd-105 @ 1200K
Broadening   nuclide     pd-105 @ 922.039K
Loading      nuclide      zr-95 @ 900K
Loading      nuclide      zr-95 @ 1200K
Broadening   nuclide      zr-95 @ 922.039K
Loading      nuclide     pd-107 @ 900K
Loading      nuclide     pd-107 @ 1200K
Broadening   nuclide     pd-107 @ 922.039K
Loading      nuclide     pd-108 @ 900K
Loading      nuclide     pd-108 @ 1200K
Broadening   nuclide     pd-108 @ 922.039K
Loading      nuclide     pr-141 @ 900K
Loading      nuclide     pr-141 @ 1200K
Broadening   nuclide     pr-141 @ 922.039K
Loading      nuclide     in-115 @ 900K
Loading      nuclide     in-115 @ 1200K
Broadening   nuclide     in-115 @ 922.039K
Loading      nuclide     eu-156 @ 900K
Loading      nuclide     eu-156 @ 1200K
Broadening   nuclide     eu-156 @ 922.039K
Loading      nuclide     ru-102 @ 900K
Loading      nuclide     ru-102 @ 1200K
Broadening   nuclide     ru-102 @ 922.039K
Loading      nuclide     nd-144 @ 900K
Loading      nuclide     nd-144 @ 1200K
Broadening   nuclide     nd-144 @ 922.039K
Loading      nuclide      i-127 @ 900K
Loading      nuclide      i-127 @ 1200K
Broadening   nuclide      i-127 @ 922.039K
Loading      nuclide     mo-100 @ 900K
Loading      nuclide     mo-100 @ 1200K
Broadening   nuclide     mo-100 @ 922.039K
Loading      nuclide     ru-104 @ 900K
Loading      nuclide     ru-104 @ 1200K
Broadening   nuclide     ru-104 @ 922.039K
Loading      nuclide     ce-142 @ 900K
Loading      nuclide     ce-142 @ 1200K
Broadening   nuclide     ce-142 @ 922.039K
Loading      nuclide      nb-95 @ 900K
Loading      nuclide      nb-95 @ 1200K
Broadening   nuclide      nb-95 @ 922.039K
Loading      nuclide    am-242m @ 900K
Loading      nuclide    am-242m @ 1200K
Broadening   nuclide    am-242m @ 922.039K
Loading      nuclide      ge-72 @ 900K
Loading      nuclide      ge-72 @ 1200K
Broadening   nuclide      ge-72 @ 922.039K
Loading      nuclide     sb-124 @ 900K
Loading      nuclide     sb-124 @ 1200K
Broadening   nuclide     sb-124 @ 922.039K
Loading      nuclide      ge-73 @ 900K
Loading      nuclide      ge-73 @ 1200K
Broadening   nuclide      ge-73 @ 922.039K
Loading      nuclide     sb-125 @ 900K
Loading      nuclide     sb-125 @ 1200K
Broadening   nuclide     sb-125 @ 922.039K
Loading      nuclide      ge-74 @ 900K
Loading      nuclide      ge-74 @ 1200K
Broadening   nuclide      ge-74 @ 922.039K
Loading      nuclide     sb-126 @ 900K
Loading      nuclide     sb-126 @ 1200K
Broadening   nuclide     sb-126 @ 922.039K
Loading      nuclide     te-120 @ 900K
Loading      nuclide     te-120 @ 1200K
Broadening   nuclide     te-120 @ 922.039K
Loading      nuclide      ge-76 @ 900K
Loading      nuclide      ge-76 @ 1200K
Broadening   nuclide      ge-76 @ 922.039K
Loading      nuclide     te-122 @ 900K
Loading      nuclide     te-122 @ 1200K
Broadening   nuclide     te-122 @ 922.039K
Loading      nuclide      as-75 @ 900K
Loading      nuclide      as-75 @ 1200K
Broadening   nuclide      as-75 @ 922.039K
Loading      nuclide     te-123 @ 900K
Loading      nuclide     te-123 @ 1200K
Broadening   nuclide     te-123 @ 922.039K
Loading      nuclide      se-76 @ 900K
Loading      nuclide      se-76 @ 1200K
Broadening   nuclide      se-76 @ 922.039K
Loading      nuclide     te-124 @ 900K
Loading      nuclide     te-124 @ 1200K
Broadening   nuclide     te-124 @ 922.039K
Loading      nuclide      se-77 @ 900K
Loading      nuclide      se-77 @ 1200K
Broadening   nuclide      se-77 @ 922.039K
Loading      nuclide     te-125 @ 900K
Loading      nuclide     te-125 @ 1200K
Broadening   nuclide     te-125 @ 922.039K
Loading      nuclide      se-78 @ 900K
Loading      nuclide      se-78 @ 1200K
Broadening   nuclide      se-78 @ 922.039K
Loading      nuclide     te-126 @ 900K
Loading      nuclide     te-126 @ 1200K
Broadening   nuclide     te-126 @ 922.039K
Loading      nuclide      se-80 @ 900K
Loading      nuclide      se-80 @ 1200K
Broadening   nuclide      se-80 @ 922.039K
Loading      nuclide    te-127m @ 900K
Loading      nuclide    te-127m @ 1200K
Broadening   nuclide    te-127m @ 922.039K
Loading      nuclide      se-82 @ 900K
Loading      nuclide      se-82 @ 1200K
Broadening   nuclide      se-82 @ 922.039K
Loading      nuclide     te-128 @ 900K
Loading      nuclide     te-128 @ 1200K
Broadening   nuclide     te-128 @ 922.039K
Loading      nuclide      br-79 @ 900K
Loading      nuclide      br-79 @ 1200K
Broadening   nuclide      br-79 @ 922.039K
Loading      nuclide    te-129m @ 900K
Loading      nuclide    te-129m @ 1200K
Broadening   nuclide    te-129m @ 922.039K
Loading      nuclide      br-81 @ 900K
Loading      nuclide      br-81 @ 1200K
Broadening   nuclide      br-81 @ 922.039K
Loading      nuclide     te-130 @ 900K
Loading      nuclide     te-130 @ 1200K
Broadening   nuclide     te-130 @ 922.039K
Loading      nuclide      kr-80 @ 900K
Loading      nuclide      kr-80 @ 1200K
Broadening   nuclide      kr-80 @ 922.039K
Loading      nuclide     te-132 @ 900K
Loading      nuclide     te-132 @ 1200K
Broadening   nuclide     te-132 @ 922.039K
Loading      nuclide      kr-82 @ 900K
Loading      nuclide      kr-82 @ 1200K
Broadening   nuclide      kr-82 @ 922.039K
Loading      nuclide      kr-84 @ 900K
Loading      nuclide      kr-84 @ 1200K
Broadening   nuclide      kr-84 @ 922.039K
Loading      nuclide      i-130 @ 900K
Loading      nuclide      i-130 @ 1200K
Broadening   nuclide      i-130 @ 922.039K
Loading      nuclide      kr-85 @ 900K
Loading      nuclide      kr-85 @ 1200K
Broadening   nuclide      kr-85 @ 922.039K
Loading      nuclide      i-131 @ 900K
Loading      nuclide      i-131 @ 1200K
Broadening   nuclide      i-131 @ 922.039K
Loading      nuclide      kr-86 @ 900K
Loading      nuclide      kr-86 @ 1200K
Broadening   nuclide      kr-86 @ 922.039K
Loading      nuclide     xe-124 @ 900K
Loading      nuclide     xe-124 @ 1200K
Broadening   nuclide     xe-124 @ 922.039K
Loading      nuclide     xe-126 @ 900K
Loading      nuclide     xe-126 @ 1200K
Broadening   nuclide     xe-126 @ 922.039K
Loading      nuclide      rb-85 @ 900K
Loading      nuclide      rb-85 @ 1200K
Broadening   nuclide      rb-85 @ 922.039K
Loading      nuclide     xe-128 @ 900K
Loading      nuclide     xe-128 @ 1200K
Broadening   nuclide     xe-128 @ 922.039K
Loading      nuclide      rb-86 @ 900K
Loading      nuclide      rb-86 @ 1200K
Broadening   nuclide      rb-86 @ 922.039K
Loading      nuclide     xe-129 @ 900K
Loading      nuclide     xe-129 @ 1200K
Broadening   nuclide     xe-129 @ 922.039K
Loading      nuclide      rb-87 @ 900K
Loading      nuclide      rb-87 @ 1200K
Broadening   nuclide      rb-87 @ 922.039K
Loading      nuclide     xe-130 @ 900K
Loading      nuclide     xe-130 @ 1200K
Broadening   nuclide     xe-130 @ 922.039K
Loading      nuclide      sr-84 @ 900K
Loading      nuclide      sr-84 @ 1200K
Broadening   nuclide      sr-84 @ 922.039K
Loading      nuclide      sr-86 @ 900K
Loading      nuclide      sr-86 @ 1200K
Broadening   nuclide      sr-86 @ 922.039K
Loading      nuclide     xe-132 @ 900K
Loading      nuclide     xe-132 @ 1200K
Broadening   nuclide     xe-132 @ 922.039K
Loading      nuclide      sr-87 @ 900K
Loading      nuclide      sr-87 @ 1200K
Broadening   nuclide      sr-87 @ 922.039K
Loading      nuclide      sr-88 @ 900K
Loading      nuclide      sr-88 @ 1200K
Broadening   nuclide      sr-88 @ 922.039K
Loading      nuclide     xe-134 @ 900K
Loading      nuclide     xe-134 @ 1200K
Broadening   nuclide     xe-134 @ 922.039K
Loading      nuclide      sr-89 @ 900K
Loading      nuclide      sr-89 @ 1200K
Broadening   nuclide      sr-89 @ 922.039K
Loading      nuclide      sr-90 @ 900K
Loading      nuclide      sr-90 @ 1200K
Broadening   nuclide      sr-90 @ 922.039K
Loading      nuclide     xe-136 @ 900K
Loading      nuclide     xe-136 @ 1200K
Broadening   nuclide     xe-136 @ 922.039K
Loading      nuclide       y-89 @ 900K
Loading      nuclide       y-89 @ 1200K
Broadening   nuclide       y-89 @ 922.039K
Loading      nuclide       y-90 @ 900K
Loading      nuclide       y-90 @ 1200K
Broadening   nuclide       y-90 @ 922.039K
Loading      nuclide       y-91 @ 900K
Loading      nuclide       y-91 @ 1200K
Broadening   nuclide       y-91 @ 922.039K
Loading      nuclide     cs-136 @ 900K
Loading      nuclide     cs-136 @ 1200K
Broadening   nuclide     cs-136 @ 922.039K
Loading      nuclide     ba-134 @ 900K
Loading      nuclide     ba-134 @ 1200K
Broadening   nuclide     ba-134 @ 922.039K
Loading      nuclide     ba-135 @ 900K
Loading      nuclide     ba-135 @ 1200K
Broadening   nuclide     ba-135 @ 922.039K
Loading      nuclide     ba-136 @ 900K
Loading      nuclide     ba-136 @ 1200K
Broadening   nuclide     ba-136 @ 922.039K
Loading      nuclide     ba-137 @ 900K
Loading      nuclide     ba-137 @ 1200K
Broadening   nuclide     ba-137 @ 922.039K
Loading      nuclide     ba-138 @ 900K
Loading      nuclide     ba-138 @ 1200K
Broadening   nuclide     ba-138 @ 922.039K
Loading      nuclide      nb-94 @ 900K
Loading      nuclide      nb-94 @ 1200K
Broadening   nuclide      nb-94 @ 922.039K
Loading      nuclide     la-140 @ 900K
Loading      nuclide     la-140 @ 1200K
Broadening   nuclide     la-140 @ 922.039K
Loading      nuclide     ce-140 @ 900K
Loading      nuclide     ce-140 @ 1200K
Broadening   nuclide     ce-140 @ 922.039K
Loading      nuclide      mo-92 @ 900K
Loading      nuclide      mo-92 @ 1200K
Broadening   nuclide      mo-92 @ 922.039K
Loading      nuclide      mo-94 @ 900K
Loading      nuclide      mo-94 @ 1200K
Broadening   nuclide      mo-94 @ 922.039K
Loading      nuclide      mo-96 @ 900K
Loading      nuclide      mo-96 @ 1200K
Broadening   nuclide      mo-96 @ 922.039K
Loading      nuclide     pr-142 @ 900K
Loading      nuclide     pr-142 @ 1200K
Broadening   nuclide     pr-142 @ 922.039K
Loading      nuclide     nd-142 @ 900K
Loading      nuclide     nd-142 @ 1200K
Broadening   nuclide     nd-142 @ 922.039K
Loading      nuclide      ru-96 @ 900K
Loading      nuclide      ru-96 @ 1200K
Broadening   nuclide      ru-96 @ 922.039K
Loading      nuclide      ru-98 @ 900K
Loading      nuclide      ru-98 @ 1200K
Broadening   nuclide      ru-98 @ 922.039K
Loading      nuclide      ru-99 @ 900K
Loading      nuclide      ru-99 @ 1200K
Broadening   nuclide      ru-99 @ 922.039K
Loading      nuclide     ru-100 @ 900K
Loading      nuclide     ru-100 @ 1200K
Broadening   nuclide     ru-100 @ 922.039K
Loading      nuclide     ru-105 @ 900K
Loading      nuclide     ru-105 @ 1200K
Broadening   nuclide     ru-105 @ 922.039K
Loading      nuclide     nd-150 @ 900K
Loading      nuclide     nd-150 @ 1200K
Broadening   nuclide     nd-150 @ 922.039K
Loading      nuclide     pd-102 @ 900K
Loading      nuclide     pd-102 @ 1200K
Broadening   nuclide     pd-102 @ 922.039K
Loading      nuclide     pm-151 @ 900K
Loading      nuclide     pm-151 @ 1200K
Broadening   nuclide     pm-151 @ 922.039K
Loading      nuclide     pd-104 @ 900K
Loading      nuclide     pd-104 @ 1200K
Broadening   nuclide     pd-104 @ 922.039K
Loading      nuclide     sm-144 @ 900K
Loading      nuclide     sm-144 @ 1200K
Broadening   nuclide     sm-144 @ 922.039K
Loading      nuclide     pd-106 @ 900K
Loading      nuclide     pd-106 @ 1200K
Broadening   nuclide     pd-106 @ 922.039K
Loading      nuclide     sm-148 @ 900K
Loading      nuclide     sm-148 @ 1200K
Broadening   nuclide     sm-148 @ 922.039K
Loading      nuclide     pd-110 @ 900K
Loading      nuclide     pd-110 @ 1200K
Broadening   nuclide     pd-110 @ 922.039K
Loading      nuclide     ag-107 @ 900K
Loading      nuclide     ag-107 @ 1200K
Broadening   nuclide     ag-107 @ 922.039K
Loading      nuclide     ag-111 @ 900K
Loading      nuclide     ag-111 @ 1200K
Broadening   nuclide     ag-111 @ 922.039K
Loading      nuclide     sm-154 @ 900K
Loading      nuclide     sm-154 @ 1200K
Broadening   nuclide     sm-154 @ 922.039K
Loading      nuclide     cd-106 @ 900K
Loading      nuclide     cd-106 @ 1200K
Broadening   nuclide     cd-106 @ 922.039K
Loading      nuclide     cd-108 @ 900K
Loading      nuclide     cd-108 @ 1200K
Broadening   nuclide     cd-108 @ 922.039K
Loading      nuclide     eu-152 @ 900K
Loading      nuclide     eu-152 @ 1200K
Broadening   nuclide     eu-152 @ 922.039K
Loading      nuclide     cd-110 @ 900K
Loading      nuclide     cd-110 @ 1200K
Broadening   nuclide     cd-110 @ 922.039K
Loading      nuclide     cd-111 @ 900K
Loading      nuclide     cd-111 @ 1200K
Broadening   nuclide     cd-111 @ 922.039K
Loading      nuclide     cd-112 @ 900K
Loading      nuclide     cd-112 @ 1200K
Broadening   nuclide     cd-112 @ 922.039K
Loading      nuclide     cd-114 @ 900K
Loading      nuclide     cd-114 @ 1200K
Broadening   nuclide     cd-114 @ 922.039K
Loading      nuclide     eu-157 @ 900K
Loading      nuclide     eu-157 @ 1200K
Broadening   nuclide     eu-157 @ 922.039K
Loading      nuclide    cd-115m @ 900K
Loading      nuclide    cd-115m @ 1200K
Broadening   nuclide    cd-115m @ 922.039K
Loading      nuclide     cd-116 @ 900K
Loading      nuclide     cd-116 @ 1200K
Broadening   nuclide     cd-116 @ 922.039K
Loading      nuclide     in-113 @ 900K
Loading      nuclide     in-113 @ 1200K
Broadening   nuclide     in-113 @ 922.039K
Loading      nuclide     sn-112 @ 900K
Loading      nuclide     sn-112 @ 1200K
Broadening   nuclide     sn-112 @ 922.039K
Loading      nuclide     sn-114 @ 900K
Loading      nuclide     sn-114 @ 1200K
Broadening   nuclide     sn-114 @ 922.039K
Loading      nuclide     sn-115 @ 900K
Loading      nuclide     sn-115 @ 1200K
Broadening   nuclide     sn-115 @ 922.039K
Loading      nuclide     sn-116 @ 900K
Loading      nuclide     sn-116 @ 1200K
Broadening   nuclide     sn-116 @ 922.039K
Loading      nuclide     sn-117 @ 900K
Loading      nuclide     sn-117 @ 1200K
Broadening   nuclide     sn-117 @ 922.039K
Loading      nuclide     sn-118 @ 900K
Loading      nuclide     sn-118 @ 1200K
Broadening   nuclide     sn-118 @ 922.039K
Loading      nuclide     tb-159 @ 900K
Loading      nuclide     tb-159 @ 1200K
Broadening   nuclide     tb-159 @ 922.039K
Loading      nuclide     sn-119 @ 900K
Loading      nuclide     sn-119 @ 1200K
Broadening   nuclide     sn-119 @ 922.039K
Loading      nuclide     tb-160 @ 900K
Loading      nuclide     tb-160 @ 1200K
Broadening   nuclide     tb-160 @ 922.039K
Loading      nuclide     sn-120 @ 900K
Loading      nuclide     sn-120 @ 1200K
Broadening   nuclide     sn-120 @ 922.039K
Loading      nuclide     dy-160 @ 900K
Loading      nuclide     dy-160 @ 1200K
Broadening   nuclide     dy-160 @ 922.039K
Loading      nuclide     sn-122 @ 900K
Loading      nuclide     sn-122 @ 1200K
Broadening   nuclide     sn-122 @ 922.039K
Loading      nuclide     dy-161 @ 900K
Loading      nuclide     dy-161 @ 1200K
Broadening   nuclide     dy-161 @ 922.039K
Loading      nuclide     sn-123 @ 900K
Loading      nuclide     sn-123 @ 1200K
Broadening   nuclide     sn-123 @ 922.039K
Loading      nuclide     dy-162 @ 900K
Loading      nuclide     dy-162 @ 1200K
Broadening   nuclide     dy-162 @ 922.039K
Loading      nuclide     sn-124 @ 900K
Loading      nuclide     sn-124 @ 1200K
Broadening   nuclide     sn-124 @ 922.039K
Loading      nuclide     dy-163 @ 900K
Loading      nuclide     dy-163 @ 1200K
Broadening   nuclide     dy-163 @ 922.039K
Loading      nuclide     sn-125 @ 900K
Loading      nuclide     sn-125 @ 1200K
Broadening   nuclide     sn-125 @ 922.039K
Loading      nuclide     dy-164 @ 900K
Loading      nuclide     dy-164 @ 1200K
Broadening   nuclide     dy-164 @ 922.039K
Loading      nuclide     ho-165 @ 900K
Loading      nuclide     ho-165 @ 1200K
Broadening   nuclide     ho-165 @ 922.039K
Loading      nuclide     sb-121 @ 900K
Loading      nuclide     sb-121 @ 1200K
Broadening   nuclide     sb-121 @ 922.039K
Loading      nuclide     er-166 @ 900K
Loading      nuclide     er-166 @ 1200K
Broadening   nuclide     er-166 @ 922.039K
Loading      nuclide     sb-123 @ 900K
Loading      nuclide     sb-123 @ 1200K
Broadening   nuclide     sb-123 @ 922.039K
Loading      nuclide     er-167 @ 900K
Loading      nuclide     er-167 @ 1200K
Broadening   nuclide     er-167 @ 922.039K
Loading      nuclide     lu-175 @ 900K
Loading      nuclide     lu-175 @ 1200K
Broadening   nuclide     lu-175 @ 922.039K
Loading      nuclide     re-185 @ 900K
Loading      nuclide     re-185 @ 1200K
Broadening   nuclide     re-185 @ 922.039K
Loading      nuclide     lu-176 @ 900K
Loading      nuclide     lu-176 @ 1200K
Broadening   nuclide     lu-176 @ 922.039K
Loading      nuclide     re-187 @ 900K
Loading      nuclide     re-187 @ 1200K
Broadening   nuclide     re-187 @ 922.039K
Loading      nuclide     ta-181 @ 900K
Loading      nuclide     ta-181 @ 1200K
Broadening   nuclide     ta-181 @ 922.039K
Loading      nuclide     au-197 @ 900K
Loading      nuclide     au-197 @ 1200K
Broadening   nuclide     au-197 @ 922.039K
Loading      nuclide      w-182 @ 900K
Loading      nuclide      w-182 @ 1200K
Broadening   nuclide      w-182 @ 922.039K
Loading      nuclide     th-232 @ 900K
Loading      nuclide     th-232 @ 1200K
Broadening   nuclide     th-232 @ 922.039K
Loading      nuclide      w-183 @ 900K
Loading      nuclide      w-183 @ 1200K
Broadening   nuclide      w-183 @ 922.039K
Loading      nuclide     pa-231 @ 900K
Loading      nuclide     pa-231 @ 1200K
Broadening   nuclide     pa-231 @ 922.039K
Loading      nuclide      w-184 @ 900K
Loading      nuclide      w-184 @ 1200K
Broadening   nuclide      w-184 @ 922.039K
Loading      nuclide     pa-233 @ 900K
Loading      nuclide     pa-233 @ 1200K
Broadening   nuclide     pa-233 @ 922.039K
Loading      nuclide      w-186 @ 900K
Loading      nuclide      w-186 @ 1200K
Broadening   nuclide      w-186 @ 922.039K
Loading      nuclide      u-233 @ 900K
Loading      nuclide      u-233 @ 1200K
Broadening   nuclide      u-233 @ 922.039K
Loading      nuclide     th-230 @ 900K
Loading      nuclide     th-230 @ 1200K
Broadening   nuclide     th-230 @ 922.039K
Loading      nuclide      u-232 @ 900K
Loading      nuclide      u-232 @ 1200K
Broadening   nuclide      u-232 @ 922.039K
Loading      nuclide        h-2 @ 650K
Loading      nuclide        h-3 @ 900K
Loading      nuclide        h-3 @ 1200K
Broadening   nuclide        h-3 @ 922.039K
Loading      nuclide       he-3 @ 900K
Loading      nuclide       he-3 @ 1200K
Broadening   nuclide       he-3 @ 922.039K
Loading      nuclide       he-4 @ 900K
Loading      nuclide       he-4 @ 1200K
Broadening   nuclide       he-4 @ 922.039K
Loading      nuclide       be-7 @ 900K
Loading      nuclide       be-7 @ 1200K
Broadening   nuclide       be-7 @ 922.039K
Loading      nuclide       n-15 @ 900K
Loading      nuclide       n-15 @ 1200K
Broadening   nuclide       n-15 @ 922.039K
Loading      nuclide       o-17 @ 900K
Loading      nuclide       o-17 @ 1200K
Broadening   nuclide       o-17 @ 922.039K
Loading      nuclide      na-23 @ 900K
Loading      nuclide      na-23 @ 1200K
Broadening   nuclide      na-23 @ 922.039K
Loading      nuclide      mg-24 @ 900K
Loading      nuclide      mg-24 @ 1200K
Broadening   nuclide      mg-24 @ 922.039K
Loading      nuclide      mg-25 @ 900K
Loading      nuclide      mg-25 @ 1200K
Broadening   nuclide      mg-25 @ 922.039K
Loading      nuclide      mg-26 @ 900K
Loading      nuclide      mg-26 @ 1200K
Broadening   nuclide      mg-26 @ 922.039K
Loading      nuclide      al-27 @ 900K
Loading      nuclide      al-27 @ 1200K
Broadening   nuclide      al-27 @ 922.039K
Loading      nuclide      si-28 @ 900K
Loading      nuclide      si-28 @ 1200K
Broadening   nuclide      si-28 @ 922.039K
Loading      nuclide      si-29 @ 900K
Loading      nuclide      si-29 @ 1200K
Broadening   nuclide      si-29 @ 922.039K
Loading      nuclide      si-30 @ 900K
Loading      nuclide      si-30 @ 1200K
Broadening   nuclide      si-30 @ 922.039K
Loading      nuclide       p-31 @ 900K
Loading      nuclide       p-31 @ 1200K
Broadening   nuclide       p-31 @ 922.039K
Loading      nuclide       s-32 @ 900K
Loading      nuclide       s-32 @ 1200K
Broadening   nuclide       s-32 @ 922.039K
Loading      nuclide       s-33 @ 900K
Loading      nuclide       s-33 @ 1200K
Broadening   nuclide       s-33 @ 922.039K
Loading      nuclide       s-34 @ 900K
Loading      nuclide       s-34 @ 1200K
Broadening   nuclide       s-34 @ 922.039K
Loading      nuclide       s-36 @ 900K
Loading      nuclide       s-36 @ 1200K
Broadening   nuclide       s-36 @ 922.039K
Loading      nuclide      cl-35 @ 900K
Loading      nuclide      cl-35 @ 1200K
Broadening   nuclide      cl-35 @ 922.039K
Loading      nuclide      cl-37 @ 900K
Loading      nuclide      cl-37 @ 1200K
Broadening   nuclide      cl-37 @ 922.039K
Loading      nuclide      ar-36 @ 900K
Loading      nuclide      ar-36 @ 1200K
Broadening   nuclide      ar-36 @ 922.039K
Loading      nuclide      ar-38 @ 900K
Loading      nuclide      ar-38 @ 1200K
Broadening   nuclide      ar-38 @ 922.039K
Loading      nuclide      ar-40 @ 900K
Loading      nuclide      ar-40 @ 1200K
Broadening   nuclide      ar-40 @ 922.039K
Loading      nuclide       k-39 @ 900K
Loading      nuclide       k-39 @ 1200K
Broadening   nuclide       k-39 @ 922.039K
Loading      nuclide       k-40 @ 900K
Loading      nuclide       k-40 @ 1200K
Broadening   nuclide       k-40 @ 922.039K
Loading      nuclide       k-41 @ 900K
Loading      nuclide       k-41 @ 1200K
Broadening   nuclide       k-41 @ 922.039K
Loading      nuclide      ca-40 @ 900K
Loading      nuclide      ca-40 @ 1200K
Broadening   nuclide      ca-40 @ 922.039K
Loading      nuclide      ca-42 @ 900K
Loading      nuclide      ca-42 @ 1200K
Broadening   nuclide      ca-42 @ 922.039K
Loading      nuclide      ca-43 @ 900K
Loading      nuclide      ca-43 @ 1200K
Broadening   nuclide      ca-43 @ 922.039K
Loading      nuclide      ca-44 @ 900K
Loading      nuclide      ca-44 @ 1200K
Broadening   nuclide      ca-44 @ 922.039K
Loading      nuclide      ca-46 @ 900K
Loading      nuclide      ca-46 @ 1200K
Broadening   nuclide      ca-46 @ 922.039K
Loading      nuclide      ca-48 @ 900K
Loading      nuclide      ca-48 @ 1200K
Broadening   nuclide      ca-48 @ 922.039K
Loading      nuclide      sc-45 @ 900K
Loading      nuclide      sc-45 @ 1200K
Broadening   nuclide      sc-45 @ 922.039K
Loading      nuclide      ti-46 @ 900K
Loading      nuclide      ti-46 @ 1200K
Broadening   nuclide      ti-46 @ 922.039K
Loading      nuclide      ti-47 @ 900K
Loading      nuclide      ti-47 @ 1200K
Broadening   nuclide      ti-47 @ 922.039K
Loading      nuclide      ti-48 @ 900K
Loading      nuclide      ti-48 @ 1200K
Broadening   nuclide      ti-48 @ 922.039K
Loading      nuclide      ti-49 @ 900K
Loading      nuclide      ti-49 @ 1200K
Broadening   nuclide      ti-49 @ 922.039K
Loading      nuclide      ti-50 @ 900K
Loading      nuclide      ti-50 @ 1200K
Broadening   nuclide      ti-50 @ 922.039K
Loading      nuclide      cr-50 @ 900K
Loading      nuclide      cr-50 @ 1200K
Broadening   nuclide      cr-50 @ 922.039K
Loading      nuclide      cr-52 @ 900K
Loading      nuclide      cr-52 @ 1200K
Broadening   nuclide      cr-52 @ 922.039K
Loading      nuclide      cr-53 @ 900K
Loading      nuclide      cr-53 @ 1200K
Broadening   nuclide      cr-53 @ 922.039K
Loading      nuclide      cr-54 @ 900K
Loading      nuclide      cr-54 @ 1200K
Broadening   nuclide      cr-54 @ 922.039K
Loading      nuclide      mn-55 @ 900K
Loading      nuclide      mn-55 @ 1200K
Broadening   nuclide      mn-55 @ 922.039K
Loading      nuclide      fe-54 @ 900K
Loading      nuclide      fe-54 @ 1200K
Broadening   nuclide      fe-54 @ 922.039K
Loading      nuclide      fe-56 @ 900K
Loading      nuclide      fe-56 @ 1200K
Broadening   nuclide      fe-56 @ 922.039K
Loading      nuclide      fe-57 @ 900K
Loading      nuclide      fe-57 @ 1200K
Broadening   nuclide      fe-57 @ 922.039K
Loading      nuclide      fe-58 @ 900K
Loading      nuclide      fe-58 @ 1200K
Broadening   nuclide      fe-58 @ 922.039K
Loading      nuclide      co-58 @ 900K
Loading      nuclide      co-58 @ 1200K
Broadening   nuclide      co-58 @ 922.039K
Loading      nuclide      co-59 @ 900K
Loading      nuclide      co-59 @ 1200K
Broadening   nuclide      co-59 @ 922.039K
Loading      nuclide     co-58m @ 900K
Loading      nuclide     co-58m @ 1200K
Broadening   nuclide     co-58m @ 922.039K
Loading      nuclide      ni-58 @ 900K
Loading      nuclide      ni-58 @ 1200K
Broadening   nuclide      ni-58 @ 922.039K
Loading      nuclide      ni-59 @ 900K
Loading      nuclide      ni-59 @ 1200K
Broadening   nuclide      ni-59 @ 922.039K
Loading      nuclide      ni-60 @ 900K
Loading      nuclide      ni-60 @ 1200K
Broadening   nuclide      ni-60 @ 922.039K
Loading      nuclide      ni-61 @ 900K
Loading      nuclide      ni-61 @ 1200K
Broadening   nuclide      ni-61 @ 922.039K
Loading      nuclide      ni-62 @ 900K
Loading      nuclide      ni-62 @ 1200K
Broadening   nuclide      ni-62 @ 922.039K
Loading      nuclide      ni-64 @ 900K
Loading      nuclide      ni-64 @ 1200K
Broadening   nuclide      ni-64 @ 922.039K
Loading      nuclide      cu-63 @ 900K
Loading      nuclide      cu-63 @ 1200K
Broadening   nuclide      cu-63 @ 922.039K
Loading      nuclide      cu-65 @ 900K
Loading      nuclide      cu-65 @ 1200K
Broadening   nuclide      cu-65 @ 922.039K
Loading      nuclide      ga-69 @ 900K
Loading      nuclide      ga-69 @ 1200K
Broadening   nuclide      ga-69 @ 922.039K
Loading      nuclide      ga-71 @ 900K
Loading      nuclide      ga-71 @ 1200K
Broadening   nuclide      ga-71 @ 922.039K
Loading      nuclide      ge-70 @ 900K
Loading      nuclide      ge-70 @ 1200K
Broadening   nuclide      ge-70 @ 922.039K
Loading      nuclide      as-74 @ 900K
Loading      nuclide      as-74 @ 1200K
Broadening   nuclide      as-74 @ 922.039K
Loading      nuclide      se-74 @ 900K
Loading      nuclide      se-74 @ 1200K
Broadening   nuclide      se-74 @ 922.039K
Loading      nuclide      se-79 @ 900K
Loading      nuclide      se-79 @ 1200K
Broadening   nuclide      se-79 @ 922.039K
Loading      nuclide      kr-78 @ 900K
Loading      nuclide      kr-78 @ 1200K
Broadening   nuclide      kr-78 @ 922.039K
Loading      nuclide    ag-110m @ 900K
Loading      nuclide    ag-110m @ 1200K
Broadening   nuclide    ag-110m @ 922.039K
Loading      nuclide     sn-113 @ 900K
Loading      nuclide     sn-113 @ 1200K
Broadening   nuclide     sn-113 @ 922.039K
Loading      nuclide     xe-123 @ 900K
Loading      nuclide     xe-123 @ 1200K
Broadening   nuclide     xe-123 @ 922.039K
Loading      nuclide     ba-130 @ 900K
Loading      nuclide     ba-130 @ 1200K
Broadening   nuclide     ba-130 @ 922.039K
Loading      nuclide     ba-132 @ 900K
Loading      nuclide     ba-132 @ 1200K
Broadening   nuclide     ba-132 @ 922.039K
Loading      nuclide     ba-133 @ 900K
Loading      nuclide     ba-133 @ 1200K
Broadening   nuclide     ba-133 @ 922.039K
Loading      nuclide     la-138 @ 900K
Loading      nuclide     la-138 @ 1200K
Broadening   nuclide     la-138 @ 922.039K
Loading      nuclide     ce-136 @ 900K
Loading      nuclide     ce-136 @ 1200K
Broadening   nuclide     ce-136 @ 922.039K
Loading      nuclide     ce-138 @ 900K
Loading      nuclide     ce-138 @ 1200K
Broadening   nuclide     ce-138 @ 922.039K
Loading      nuclide     ce-139 @ 900K
Loading      nuclide     ce-139 @ 1200K
Broadening   nuclide     ce-139 @ 922.039K
Loading      nuclide    pm-148m @ 900K
Loading      nuclide    pm-148m @ 1200K
Broadening   nuclide    pm-148m @ 922.039K
Loading      nuclide     gd-153 @ 900K
Loading      nuclide     gd-153 @ 1200K
Broadening   nuclide     gd-153 @ 922.039K
Loading      nuclide     dy-156 @ 900K
Loading      nuclide     dy-156 @ 1200K
Broadening   nuclide     dy-156 @ 922.039K
Loading      nuclide     dy-158 @ 900K
Loading      nuclide     dy-158 @ 1200K
Broadening   nuclide     dy-158 @ 922.039K
Loading      nuclide    ho-166m @ 900K
Loading      nuclide    ho-166m @ 1200K
Broadening   nuclide    ho-166m @ 922.039K
Loading      nuclide     er-162 @ 900K
Loading      nuclide     er-162 @ 1200K
Broadening   nuclide     er-162 @ 922.039K
Loading      nuclide     er-164 @ 900K
Loading      nuclide     er-164 @ 1200K
Broadening   nuclide     er-164 @ 922.039K
Loading      nuclide     er-168 @ 900K
Loading      nuclide     er-168 @ 1200K
Broadening   nuclide     er-168 @ 922.039K
Loading      nuclide     er-170 @ 900K
Loading      nuclide     er-170 @ 1200K
Broadening   nuclide     er-170 @ 922.039K
Loading      nuclide     hf-174 @ 900K
Loading      nuclide     hf-174 @ 1200K
Broadening   nuclide     hf-174 @ 922.039K
Loading      nuclide     hf-176 @ 900K
Loading      nuclide     hf-176 @ 1200K
Broadening   nuclide     hf-176 @ 922.039K
Loading      nuclide     hf-177 @ 900K
Loading      nuclide     hf-177 @ 1200K
Broadening   nuclide     hf-177 @ 922.039K
Loading      nuclide     hf-178 @ 900K
Loading      nuclide     hf-178 @ 1200K
Broadening   nuclide     hf-178 @ 922.039K
Loading      nuclide     hf-179 @ 900K
Loading      nuclide     hf-179 @ 1200K
Broadening   nuclide     hf-179 @ 922.039K
Loading      nuclide     hf-180 @ 900K
Loading      nuclide     hf-180 @ 1200K
Broadening   nuclide     hf-180 @ 922.039K
Loading      nuclide     ta-182 @ 900K
Loading      nuclide     ta-182 @ 1200K
Broadening   nuclide     ta-182 @ 922.039K
Loading      nuclide     ir-191 @ 900K
Loading      nuclide     ir-191 @ 1200K
Broadening   nuclide     ir-191 @ 922.039K
Loading      nuclide     ir-193 @ 900K
Loading      nuclide     ir-193 @ 1200K
Broadening   nuclide     ir-193 @ 922.039K
Loading      nuclide     hg-196 @ 900K
Loading      nuclide     hg-196 @ 1200K
Broadening   nuclide     hg-196 @ 922.039K
Loading      nuclide     hg-198 @ 900K
Loading      nuclide     hg-198 @ 1200K
Broadening   nuclide     hg-198 @ 922.039K
Loading      nuclide     hg-199 @ 900K
Loading      nuclide     hg-199 @ 1200K
Broadening   nuclide     hg-199 @ 922.039K
Loading      nuclide     hg-200 @ 900K
Loading      nuclide     hg-200 @ 1200K
Broadening   nuclide     hg-200 @ 922.039K
Loading      nuclide     hg-201 @ 900K
Loading      nuclide     hg-201 @ 1200K
Broadening   nuclide     hg-201 @ 922.039K
Loading      nuclide     hg-202 @ 900K
Loading      nuclide     hg-202 @ 1200K
Broadening   nuclide     hg-202 @ 922.039K
Loading      nuclide     hg-204 @ 900K
Loading      nuclide     hg-204 @ 1200K
Broadening   nuclide     hg-204 @ 922.039K
Loading      nuclide     pb-204 @ 900K
Loading      nuclide     pb-204 @ 1200K
Broadening   nuclide     pb-204 @ 922.039K
Loading      nuclide     pb-206 @ 900K
Loading      nuclide     pb-206 @ 1200K
Broadening   nuclide     pb-206 @ 922.039K
Loading      nuclide     pb-207 @ 900K
Loading      nuclide     pb-207 @ 1200K
Broadening   nuclide     pb-207 @ 922.039K
Loading      nuclide     pb-208 @ 900K
Loading      nuclide     pb-208 @ 1200K
Broadening   nuclide     pb-208 @ 922.039K
Loading      nuclide     bi-209 @ 900K
Loading      nuclide     bi-209 @ 1200K
Broadening   nuclide     bi-209 @ 922.039K
Loading      nuclide     ra-223 @ 900K
Loading      nuclide     ra-223 @ 1200K
Broadening   nuclide     ra-223 @ 922.039K
Loading      nuclide     ra-224 @ 900K
Loading      nuclide     ra-224 @ 1200K
Broadening   nuclide     ra-224 @ 922.039K
Loading      nuclide     ra-225 @ 900K
Loading      nuclide     ra-225 @ 1200K
Broadening   nuclide     ra-225 @ 922.039K
Loading      nuclide     ra-226 @ 900K
Loading      nuclide     ra-226 @ 1200K
Broadening   nuclide     ra-226 @ 922.039K
Loading      nuclide     ac-225 @ 900K
Loading      nuclide     ac-225 @ 1200K
Broadening   nuclide     ac-225 @ 922.039K
Loading      nuclide     ac-226 @ 900K
Loading      nuclide     ac-226 @ 1200K
Broadening   nuclide     ac-226 @ 922.039K
Loading      nuclide     ac-227 @ 900K
Loading      nuclide     ac-227 @ 1200K
Broadening   nuclide     ac-227 @ 922.039K
Loading      nuclide     th-227 @ 900K
Loading      nuclide     th-227 @ 1200K
Broadening   nuclide     th-227 @ 922.039K
Loading      nuclide     th-228 @ 900K
Loading      nuclide     th-228 @ 1200K
Broadening   nuclide     th-228 @ 922.039K
Loading      nuclide     th-229 @ 900K
Loading      nuclide     th-229 @ 1200K
Broadening   nuclide     th-229 @ 922.039K
Loading      nuclide     th-233 @ 900K
Loading      nuclide     th-233 @ 1200K
Broadening   nuclide     th-233 @ 922.039K
Loading      nuclide     th-234 @ 900K
Loading      nuclide     th-234 @ 1200K
Broadening   nuclide     th-234 @ 922.039K
Loading      nuclide     pa-232 @ 900K
Loading      nuclide     pa-232 @ 1200K
Broadening   nuclide     pa-232 @ 922.039K
Loading      nuclide      u-237 @ 900K
Loading      nuclide      u-237 @ 1200K
Broadening   nuclide      u-237 @ 922.039K
Loading      nuclide      u-239 @ 900K
Loading      nuclide      u-239 @ 1200K
Broadening   nuclide      u-239 @ 922.039K
Loading      nuclide      u-240 @ 900K
Loading      nuclide      u-240 @ 1200K
Broadening   nuclide      u-240 @ 922.039K
Loading      nuclide      u-241 @ 900K
Loading      nuclide      u-241 @ 1200K
Broadening   nuclide      u-241 @ 922.039K
Loading      nuclide     np-235 @ 900K
Loading      nuclide     np-235 @ 1200K
Broadening   nuclide     np-235 @ 922.039K
Loading      nuclide     np-236 @ 900K
Loading      nuclide     np-236 @ 1200K
Broadening   nuclide     np-236 @ 922.039K
Loading      nuclide     np-238 @ 900K
Loading      nuclide     np-238 @ 1200K
Broadening   nuclide     np-238 @ 922.039K
Loading      nuclide     np-239 @ 900K
Loading      nuclide     np-239 @ 1200K
Broadening   nuclide     np-239 @ 922.039K
Loading      nuclide     pu-236 @ 900K
Loading      nuclide     pu-236 @ 1200K
Broadening   nuclide     pu-236 @ 922.039K
Loading      nuclide     pu-237 @ 900K
Loading      nuclide     pu-237 @ 1200K
Broadening   nuclide     pu-237 @ 922.039K
Loading      nuclide     pu-243 @ 900K
Loading      nuclide     pu-243 @ 1200K
Broadening   nuclide     pu-243 @ 922.039K
Loading      nuclide     pu-244 @ 900K
Loading      nuclide     pu-244 @ 1200K
Broadening   nuclide     pu-244 @ 922.039K
Loading      nuclide     pu-246 @ 900K
Loading      nuclide     pu-246 @ 1200K
Broadening   nuclide     pu-246 @ 922.039K
Loading      nuclide     am-244 @ 900K
Loading      nuclide     am-244 @ 1200K
Broadening   nuclide     am-244 @ 922.039K
Loading      nuclide    am-244m @ 900K
Loading      nuclide    am-244m @ 1200K
Broadening   nuclide    am-244m @ 922.039K
Loading      nuclide     cm-241 @ 900K
Loading      nuclide     cm-241 @ 1200K
Broadening   nuclide     cm-241 @ 922.039K
Loading      nuclide     cm-245 @ 900K
Loading      nuclide     cm-245 @ 1200K
Broadening   nuclide     cm-245 @ 922.039K
Loading      nuclide     cm-246 @ 900K
Loading      nuclide     cm-246 @ 1200K
Broadening   nuclide     cm-246 @ 922.039K
Loading      nuclide     cm-247 @ 900K
Loading      nuclide     cm-247 @ 1200K
Broadening   nuclide     cm-247 @ 922.039K
Loading      nuclide     cm-248 @ 900K
Loading      nuclide     cm-248 @ 1200K
Broadening   nuclide     cm-248 @ 922.039K
Loading      nuclide     cm-249 @ 900K
Loading      nuclide     cm-249 @ 1200K
Broadening   nuclide     cm-249 @ 922.039K
Loading      nuclide     cm-250 @ 900K
Loading      nuclide     cm-250 @ 1200K
Broadening   nuclide     cm-250 @ 922.039K
Loading      nuclide     bk-249 @ 900K
Loading      nuclide     bk-249 @ 1200K
Broadening   nuclide     bk-249 @ 922.039K
Loading      nuclide     bk-250 @ 900K
Loading      nuclide     bk-250 @ 1200K
Broadening   nuclide     bk-250 @ 922.039K
Loading      nuclide     cf-249 @ 900K
Loading      nuclide     cf-249 @ 1200K
Broadening   nuclide     cf-249 @ 922.039K
Loading      nuclide     cf-250 @ 900K
Loading      nuclide     cf-250 @ 1200K
Broadening   nuclide     cf-250 @ 922.039K
Loading      nuclide     cf-251 @ 900K
Loading      nuclide     cf-251 @ 1200K
Broadening   nuclide     cf-251 @ 922.039K
Loading      nuclide     cf-252 @ 900K
Loading      nuclide     cf-252 @ 1200K
Broadening   nuclide     cf-252 @ 922.039K
Loading      nuclide     cf-253 @ 900K
Loading      nuclide     cf-253 @ 1200K
Broadening   nuclide     cf-253 @ 922.039K
Loading      nuclide     cf-254 @ 900K
Loading      nuclide     cf-254 @ 1200K
Broadening   nuclide     cf-254 @ 922.039K
Loading      nuclide     es-253 @ 900K
Loading      nuclide     es-253 @ 1200K
Broadening   nuclide     es-253 @ 922.039K
Loading      nuclide     es-254 @ 900K
Loading      nuclide     es-254 @ 1200K
Broadening   nuclide     es-254 @ 922.039K
Loading      nuclide     es-255 @ 900K
Loading      nuclide     es-255 @ 1200K
Broadening   nuclide     es-255 @ 922.039K
Loading      nuclide c-graphite @ 800K
Loading      nuclide c-graphite @ 1000K
Broadening   nuclide c-graphite @ 922.039K
MixMacros: MT 2022 greater than MT 2 for nuclide 60146.
MixMacros: MT 2022 greater than MT 2 for nuclide 60148.
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
MixMacros: MT 2022 greater than MT 2 for nuclide 62148.
MixMacros: MT 2022 greater than MT 2 for nuclide 66164.
MixMacros: MT 2022 greater than MT 2 for nuclide 74182.
MixMacros: MT 2022 greater than MT 2 for nuclide 74186.
MixMacros: MT 2022 greater than MT 2 for nuclide 72180.
MixMacros: MT 2022 greater than MT 2 for nuclide 60146.
MixMacros: MT 2022 greater than MT 2 for nuclide 60148.
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
MixMacros: MT 2022 greater than MT 2 for nuclide 62148.
MixMacros: MT 2022 greater than MT 2 for nuclide 66164.
MixMacros: MT 2022 greater than MT 2 for nuclide 74182.
MixMacros: MT 2022 greater than MT 2 for nuclide 74186.
MixMacros: MT 2022 greater than MT 2 for nuclide 72180.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:17:26

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.00000   0.000E+00 1.530E+06 (    1,252)   1.000E+00 (    2,  0) 13:17:29    2.7 s     2.7 s  90.0%    F
     2    0.38405   1.604E+00 1.516E+03 (  461,  6)   1.642E+00 (   38,  0) 13:17:31    5.4 s     2.7 s 133.0%    F
     3    0.31537   2.178E-01 1.286E+00 (  895,  1)   2.157E-01 (  242,  0) 13:17:34    8.0 s     2.7 s  89.3%    F
     4    0.36896   1.452E-01 1.374E+00 (   14,  7)   1.803E-01 (  944,  0) 13:17:37   10.7 s     2.7 s  90.0%    F
     5    0.47444   2.223E-01 3.934E+00 (   14,  7)   1.551E-01 (  584,  0) 13:17:39   13.4 s     2.7 s 134.5%    F
     6    0.62216   2.374E-01 1.495E+01 (   14,  8)   1.351E-01 (  941,  0) 13:17:42   16.1 s     2.7 s  89.3%    F
     7    0.80139   2.236E-01 2.303E+01 (  242,  9)   1.276E-01 (  517,  0) 13:17:45   18.8 s     2.7 s  89.3%    F
     8    0.99683   1.961E-01 1.165E+00 (  150,  1)   1.109E-01 (  517,  0) 13:17:47   21.5 s     2.7 s 134.5%    F
     9    1.19120   1.632E-01 1.161E+00 (   88,  1)   9.099E-02 (  517,  0) 13:17:50   24.2 s     2.7 s  89.3%    F
    10    1.36881   1.298E-01 1.158E+00 (  897,  1)   7.131E-02 (  517,  0) 13:17:53   26.8 s     2.7 s  89.3%    F
    11    1.51838   9.851E-02 1.156E+00 (   88,  1)   5.345E-02 (  517,  0) 13:17:55   29.5 s     2.7 s 133.5%    F
    12    1.63413   7.084E-02 1.154E+00 (  831,  1)   3.808E-02 (  517,  0) 13:17:58   32.2 s     2.7 s  90.0%    F
    13    1.71545   4.740E-02 1.153E+00 (  150,  1)   2.536E-02 (  517,  0) 13:18:01   34.9 s     2.7 s  89.7%    F
    14    1.76549   2.835E-02 1.151E+00 (   88,  1)   1.522E-02 (  517,  0) 13:18:03   37.6 s     2.7 s 134.0%    F
    15    1.78963   1.349E-02 1.151E+00 (   88,  1)   7.427E-03 (  936,  0) 13:18:06   40.2 s     2.7 s  89.0%    F
    16    1.79400   2.436E-03 1.150E+00 (  150,  1)   4.824E-03 (  584,  0) 13:18:09   42.9 s     2.7 s  89.3%    F
    17    1.78451   5.322E-03 1.149E+00 (   88,  1)   6.857E-03 (  944,  0) 13:18:12   45.6 s     2.7 s  89.0%    F
    18    1.76624   1.034E-02 1.149E+00 (  897,  1)   7.819E-03 (  584,  0) 13:18:14   48.3 s     2.7 s 134.5%    F
    19    1.74327   1.318E-02 1.148E+00 (  150,  1)   8.001E-03 (  584,  0) 13:18:17   51.0 s     2.7 s  90.3%    F
    20    1.71864   1.433E-02 1.148E+00 (  897,  1)   7.642E-03 (  944,  0) 13:18:20   53.7 s     2.7 s  89.3%    F
    21    1.69445   1.427E-02 1.148E+00 (  150,  1)   7.110E-03 (  517,  0) 13:18:22   56.3 s     2.7 s 133.5%    F
    22    1.67210   1.337E-02 1.148E+00 (  769,  1)   6.699E-03 (  947,  0) 13:18:25   59.0 s     2.7 s  89.0%    F
    23    1.65235   1.195E-02 1.147E+00 (  146,  1)   6.016E-03 (  517,  0) 13:18:28   61.7 s     2.7 s  89.0%    F
    24    1.63558   1.025E-02 1.147E+00 (  769,  1)   5.187E-03 (  947,  0) 13:18:30   64.4 s     2.7 s 133.5%    F
    25    1.62183   8.475E-03 1.147E+00 (  146,  1)   4.306E-03 (  947,  0) 13:18:33   67.0 s     2.7 s  89.0%    F
    26    1.61097   6.744E-03 1.147E+00 (  769,  1)   3.443E-03 (  517,  0) 13:18:36   69.7 s     2.7 s  89.0%    F
    27    1.60271   5.152E-03 1.147E+00 (  146,  1)   2.643E-03 (  517,  0) 13:18:38   72.4 s     2.7 s 135.5%    F
    28    1.59672   3.752E-03 1.147E+00 (  146,  1)   1.936E-03 (  517,  0) 13:18:41   75.1 s     2.7 s  89.0%    F
    29    1.59263   2.569E-03 1.147E+00 (  769,  1)   1.336E-03 (  947,  0) 13:18:44   77.8 s     2.7 s  89.0%    F
    30    1.59008   1.606E-03 1.147E+00 (  769,  1)   8.446E-04 (  936,  0) 13:18:46   80.4 s     2.7 s 133.0%    F
    31    1.58872   8.526E-04 1.147E+00 (  769,  1)   4.587E-04 (  933,  0) 13:18:49   83.1 s     2.7 s  90.3%    F
    32    1.58828   2.785E-04 1.147E+00 (  175,  1)   1.687E-04 (  944,  0) 13:18:52   85.8 s     2.6 s  88.3%    F
    33    1.58841   8.081E-05 1.147E+00 (  740,  1)   2.751E-04 (  584,  0) 13:18:54   88.4 s     2.7 s 132.5%    F
    34    1.58871   1.885E-04 1.147E+00 (  740,  1)   3.308E-04 (  584,  0) 13:18:57   91.1 s     2.7 s  88.3%    F
    35    1.58925   3.427E-04 1.147E+00 (  175,  1)   3.540E-04 (  944,  0) 13:19:00   93.8 s     2.7 s  89.3%    F
    36    1.59001   4.751E-04 1.147E+00 (  205,  1)   3.510E-04 (  584,  0) 13:19:02   96.4 s     2.7 s 134.5%    F
    37    1.59087   5.394E-04 1.147E+00 (  741,  1)   3.314E-04 (  944,  0) 13:19:05   99.1 s     2.6 s  88.3%    F
    38    1.59173   5.434E-04 1.147E+00 (  741,  1)   3.153E-04 (  947,  0) 13:19:08  101.7 s     2.6 s  87.7%    F
    39    1.59254   5.071E-04 1.147E+00 (  205,  1)   2.949E-04 (  517,  0) 13:19:10  104.3 s     2.6 s 130.5%    F
    40    1.59325   4.478E-04 1.147E+00 (  741,  1)   2.658E-04 (  947,  0) 13:19:13  107.0 s     2.6 s  88.0%    F
    41    1.59385   3.781E-04 1.147E+00 (  205,  1)   2.325E-04 (  947,  0) 13:19:16  109.6 s     2.7 s  88.3%    F
    42    1.59434   3.071E-04 1.147E+00 (  235,  1)   1.980E-04 (  517,  0) 13:19:18  112.3 s     2.7 s 135.5%    F
    43    1.59473   2.407E-04 1.147E+00 (  742,  1)   1.650E-04 (  517,  0) 13:19:21  115.0 s     2.7 s  88.7%    F
    44    1.59502   1.824E-04 1.147E+00 (  235,  1)   1.348E-04 (  947,  0) 13:19:24  117.7 s     2.7 s  89.7%    F
    45    1.59523   1.339E-04 1.147E+00 (  742,  1)   1.085E-04 (  947,  0) 13:19:26  120.3 s     2.7 s 133.5%    F
    46    1.59538   9.523E-05 1.147E+00 (  742,  1)   8.649E-05 (  517,  0) 13:19:29  123.0 s     2.7 s  88.7%    F
    47    1.59549   6.698E-05 1.147E+00 (  235,  1)   6.850E-05 (  933,  0) 13:19:32  125.7 s     2.7 s  88.3%    F
 k-eff =       1.59549074     Time=      0.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.444
 Inscatter Source  :     0.229
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.028
 Total (per outer):      2.700

  Total iteration time breakdown (sec):
 Transport Sweeping:   114.855
 Inscatter Source  :    10.741
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.298
 Total Time        :   126.894

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.59611E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:22:06

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.59549   6.698E-05 1.147E+00 (  742,  1)   6.346E-05 (   14,  0) 13:22:09    2.6 s     2.6 s  88.0%    F
     2    1.59537   7.544E-05 1.147E+00 (  742,  1)   2.081E-04 (  242,  0) 13:22:11    5.3 s     2.6 s 131.5%    F
     3    1.59530   4.230E-05 1.147E+00 (  235,  1)   4.329E-05 (  895,  0) 13:22:14    7.7 s     2.5 s  82.0%    F
 k-eff =       1.59530291     Time=      1.00d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.358
 Inscatter Source  :     0.204
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.389
 Total (per outer):      2.951

  Total iteration time breakdown (sec):
 Transport Sweeping:     7.073
 Inscatter Source  :     0.613
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.166
 Total Time        :     8.852

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.59459E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:24:56

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.59530   4.230E-05 1.147E+00 (  713,  1)   1.349E-03 (  581,  0) 13:24:58    2.5 s     2.5 s 126.5%    F
     2    1.59497   2.096E-04 1.231E+00 (  242,  4)   4.051E-04 (   14,  0) 13:25:01    5.2 s     2.7 s  88.7%    F
     3    1.59457   2.475E-04 1.147E+00 (  266,  1)   1.919E-04 (  242,  0) 13:25:03    7.9 s     2.7 s 134.5%    F
     4    1.59416   2.627E-04 1.147E+00 (  713,  1)   1.897E-04 (  242,  0) 13:25:06   10.5 s     2.6 s  88.3%    F
     5    1.59373   2.660E-04 1.147E+00 (  713,  1)   1.877E-04 (  941,  0) 13:25:09   13.2 s     2.6 s  88.0%    F
     6    1.59332   2.600E-04 1.147E+00 (  655,  1)   1.832E-04 (  947,  0) 13:25:11   15.8 s     2.6 s 132.5%    F
     7    1.59293   2.456E-04 1.147E+00 (  655,  1)   1.747E-04 (  517,  0) 13:25:14   18.6 s     2.8 s  92.0%    F
     8    1.59257   2.245E-04 1.124E+00 (  507,  2)   1.629E-04 (  947,  0) 13:25:17   21.2 s     2.6 s  86.3%    F
     9    1.59225   1.987E-04 1.104E+00 (  507,  3)   1.486E-04 (  517,  0) 13:25:19   23.7 s     2.5 s 126.5%    F
    10    1.59198   1.708E-04 2.195E-03 (  584,  4)   1.331E-04 (  947,  0) 13:25:22   26.3 s     2.6 s  88.0%    F
    11    1.59175   1.430E-04 9.664E-04 (  584,  4)   1.175E-04 (  517,  0) 13:25:25   29.0 s     2.6 s  88.3%    F
    12    1.59157   1.168E-04 4.563E-04 (  944,  4)   1.025E-04 (  947,  0) 13:25:27   31.6 s     2.7 s 133.0%    F
    13    1.59142   9.349E-05 2.390E-04 (  944,  4)   8.884E-05 (  517,  0) 13:25:30   34.3 s     2.6 s  87.3%    F
    14    1.59130   7.558E-05 1.306E-04 (  944,  4)   7.667E-05 (  947,  0) 13:25:32   36.8 s     2.6 s 128.5%    F
 k-eff =       1.59129749     Time=     24.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.402
 Inscatter Source  :     0.227
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.085
 Total (per outer):      2.714

  Total iteration time breakdown (sec):
 Transport Sweeping:    33.625
 Inscatter Source  :     3.173
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.194
 Total Time        :    37.992

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.59035E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:28:14

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.59130   7.558E-05 9.306E-01 (  242,  4)   2.261E-03 (  948,  0) 13:28:16    2.6 s     2.6 s 131.5%    F
     2    1.59089   2.581E-04 1.071E+00 (   14,  4)   4.858E-04 (  242,  0) 13:28:19    5.3 s     2.6 s  88.0%    F
     3    1.59032   3.570E-04 5.489E-01 (   14,  4)   2.807E-04 (  584,  0) 13:28:22    7.9 s     2.6 s  88.0%    F
     4    1.58967   4.065E-04 2.685E-01 (  944,  4)   2.736E-04 (  242,  0) 13:28:24   10.6 s     2.7 s 132.5%    F
     5    1.58900   4.255E-04 1.128E-01 (  944,  4)   2.645E-04 (  903,  0) 13:28:27   13.3 s     2.8 s  91.7%    F
     6    1.58833   4.227E-04 4.845E-02 (  584,  4)   2.604E-04 (  941,  0) 13:28:30   16.0 s     2.7 s  90.7%    F
     7    1.58769   4.020E-04 2.050E-02 (  584,  4)   2.489E-04 (  517,  0) 13:28:33   18.7 s     2.6 s  88.3%    F
     8    1.58710   3.674E-04 8.447E-03 (  944,  4)   2.312E-04 (  947,  0) 13:28:35   21.2 s     2.5 s 126.0%    F
     9    1.58659   3.234E-04 3.585E-03 (  944,  4)   2.091E-04 (  947,  0) 13:28:38   23.9 s     2.7 s  89.0%    F
    10    1.58616   2.748E-04 1.577E-03 (  584,  4)   1.845E-04 (  517,  0) 13:28:40   26.5 s     2.7 s 133.5%    F
    11    1.58580   2.258E-04 7.423E-04 (  944,  4)   1.594E-04 (  947,  0) 13:28:43   29.2 s     2.7 s  89.7%    F
    12    1.58551   1.799E-04 3.973E-04 (  584,  4)   1.352E-04 (  947,  0) 13:28:46   31.9 s     2.7 s  89.7%    F
    13    1.58529   1.394E-04 2.460E-04 (  584,  4)   1.131E-04 (  517,  0) 13:28:48   34.6 s     2.6 s 132.0%    F
    14    1.58512   1.052E-04 1.722E-04 (  584,  4)   9.371E-05 (  947,  0) 13:28:51   37.2 s     2.6 s  88.0%    F
    15    1.58500   7.749E-05 1.327E-04 (   14,  4)   7.725E-05 (  947,  0) 13:28:54   39.8 s     2.6 s  87.3%    F
    16    1.58490   6.259E-05 8.308E-05 (  272,238)   6.376E-05 (  517,  0) 13:28:56   42.3 s     2.5 s 125.5%    F
 k-eff =       1.58490181     Time=     70.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.420
 Inscatter Source  :     0.227
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.074
 Total (per outer):      2.722

  Total iteration time breakdown (sec):
 Transport Sweeping:    38.723
 Inscatter Source  :     3.640
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.183
 Total Time        :    43.546

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.58421E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:31:43

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.58490   6.259E-05 1.000E+00 (    1,  3)   2.307E-03 (  948,  0) 13:31:45    2.7 s     2.7 s 135.0%    F
     2    1.58480   6.232E-05 1.217E+00 (  242,  3)   9.885E-05 (  242,  0) 13:31:48    5.4 s     2.7 s  89.3%    F
     3    1.58462   1.160E-04 7.117E-01 (  242,  3)   1.770E-04 (  944,  0) 13:31:51    8.1 s     2.7 s  91.3%    F
     4    1.58438   1.537E-04 3.799E-01 (  944,  3)   1.810E-04 (   14,  0) 13:31:53   10.8 s     2.7 s 134.5%    F
     5    1.58407   1.942E-04 1.721E-01 (  584,  3)   1.846E-04 (  242,  0) 13:31:56   13.5 s     2.7 s  89.7%    F
     6    1.58371   2.250E-04 7.641E-02 (  944,  3)   1.831E-04 (  944,  0) 13:31:59   16.2 s     2.7 s  89.3%    F
     7    1.58333   2.409E-04 3.272E-02 (  944,  3)   1.783E-04 (  813,  0) 13:32:02   18.9 s     2.7 s  89.3%    F
     8    1.58295   2.419E-04 1.359E-02 (  584,  3)   1.758E-04 (  947,  0) 13:32:04   21.5 s     2.7 s 134.0%    F
     9    1.58258   2.306E-04 5.693E-03 (  584,  3)   1.678E-04 (  947,  0) 13:32:07   24.3 s     2.7 s  90.7%    F
    10    1.58225   2.105E-04 2.402E-03 (  944,  3)   1.558E-04 (  947,  0) 13:32:09   26.8 s     2.5 s 125.0%    F
    11    1.58196   1.853E-04 1.038E-03 (  584,  3)   1.415E-04 (  517,  0) 13:32:12   29.5 s     2.7 s  89.7%    F
    12    1.58171   1.581E-04 4.804E-04 (  944,  3)   1.262E-04 (  947,  0) 13:32:15   32.2 s     2.7 s  90.3%    F
    13    1.58150   1.313E-04 2.512E-04 (  944,  3)   1.110E-04 (  947,  0) 13:32:17   34.8 s     2.7 s 133.0%    F
    14    1.58133   1.065E-04 1.547E-04 (  944,  3)   9.659E-05 (  517,  0) 13:32:20   37.5 s     2.7 s  88.3%    F
    15    1.58120   8.472E-05 1.112E-04 (  584,  3)   8.366E-05 (  947,  0) 13:32:23   40.1 s     2.6 s  88.3%    F
 k-eff =       1.58119635     Time=    115.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.442
 Inscatter Source  :     0.230
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.080
 Total (per outer):      2.752

  Total iteration time breakdown (sec):
 Transport Sweeping:    36.636
 Inscatter Source  :     3.444
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.203
 Total Time        :    41.283

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.58019E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:35:07

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.58120   8.472E-05 1.000E+00 (    1,  2)   2.391E-03 (  581,  0) 13:35:10    2.7 s     2.7 s  88.3%    F
     2    1.58123   2.065E-05 1.174E+00 (  242,  2)   9.066E-05 (  242,  0) 13:35:12    5.3 s     2.6 s 131.0%    F
     3    1.58113   6.425E-05 7.140E-01 (  242,  2)   1.420E-04 (  944,  0) 13:35:15    7.9 s     2.7 s  88.7%    F
     4    1.58097   1.015E-04 3.930E-01 (  584,  2)   1.495E-04 (  242,  0) 13:35:18   10.6 s     2.7 s  89.7%    F
     5    1.58076   1.283E-04 1.853E-01 (  944,  2)   1.567E-04 (   14,  0) 13:35:21   13.3 s     2.7 s  90.7%    F
     6    1.58051   1.597E-04 8.471E-02 (  944,  2)   1.593E-04 (  944,  0) 13:35:23   16.0 s     2.7 s 134.5%    F
     7    1.58022   1.836E-04 3.712E-02 (  944,  2)   1.581E-04 (  944,  0) 13:35:26   18.8 s     2.7 s  91.0%    F
     8    1.57991   1.947E-04 1.577E-02 (  944,  2)   1.543E-04 (  941,  0) 13:35:29   21.5 s     2.7 s  90.3%    F
     9    1.57961   1.935E-04 6.717E-03 (  944,  2)   1.508E-04 (  517,  0) 13:35:31   24.2 s     2.7 s 135.0%    F
    10    1.57932   1.825E-04 2.864E-03 (  584,  2)   1.428E-04 (  947,  0) 13:35:34   26.7 s     2.5 s  84.7%    F
    11    1.57906   1.653E-04 1.237E-03 (  584,  2)   1.322E-04 (  517,  0) 13:35:36   29.1 s     2.4 s 120.0%    F
    12    1.57883   1.445E-04 5.604E-04 (  944,  2)   1.199E-04 (  947,  0) 13:35:39   31.7 s     2.6 s  87.0%    F
    13    1.57864   1.230E-04 2.790E-04 (  944,  2)   1.072E-04 (  517,  0) 13:35:41   34.3 s     2.6 s 130.5%    F
    14    1.57848   1.022E-04 1.612E-04 (  584,  2)   9.495E-05 (  947,  0) 13:35:44   36.9 s     2.6 s  87.0%    F
    15    1.57834   8.325E-05 1.103E-04 (  584,  2)   8.353E-05 (  517,  0) 13:35:47   39.5 s     2.5 s  84.7%    F
 k-eff =       1.57834411     Time=    161.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.403
 Inscatter Source  :     0.224
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.079
 Total (per outer):      2.706

  Total iteration time breakdown (sec):
 Transport Sweeping:    36.050
 Inscatter Source  :     3.363
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.180
 Total Time        :    40.593

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.57729E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:38:34

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.57834   8.325E-05 8.434E-01 (  242,  2)   2.457E-03 (  581,  0) 13:38:37    2.8 s     2.8 s  93.7%    F
     2    1.57846   7.521E-05 8.366E-01 (   14,  2)   2.036E-04 (  242,  0) 13:38:39    5.6 s     2.8 s 139.5%    F
     3    1.57842   2.841E-05 4.221E-01 (  242,  2)   1.166E-04 (  584,  0) 13:38:42    8.3 s     2.7 s  91.0%    F
     4    1.57830   7.193E-05 2.043E-01 (  584,  2)   1.262E-04 (   14,  0) 13:38:45   11.1 s     2.8 s  92.0%    F
     5    1.57814   1.021E-04 8.845E-02 (  944,  2)   1.387E-04 (  242,  0) 13:38:48   13.9 s     2.8 s  94.0%    F
     6    1.57795   1.238E-04 3.875E-02 (  584,  2)   1.421E-04 (  944,  0) 13:38:51   16.7 s     2.8 s  94.3%    F
     7    1.57772   1.467E-04 1.662E-02 (  584,  2)   1.436E-04 (  584,  0) 13:38:53   19.4 s     2.7 s 135.0%    F
     8    1.57746   1.615E-04 6.965E-03 (  584,  2)   1.403E-04 (  944,  0) 13:38:56   22.3 s     2.8 s  94.7%    F
     9    1.57720   1.656E-04 2.926E-03 (  944,  2)   1.375E-04 (  517,  0) 13:38:59   25.1 s     2.8 s  94.7%    F
    10    1.57695   1.600E-04 1.231E-03 (  584,  2)   1.320E-04 (  517,  0) 13:39:02   27.9 s     2.8 s  92.7%    F
    11    1.57672   1.478E-04 5.329E-04 (  944,  3)   1.237E-04 (  517,  0) 13:39:04   30.2 s     2.3 s 115.0%    F
    12    1.57651   1.316E-04 2.503E-04 (  584,  3)   1.135E-04 (  947,  0) 13:39:06   32.6 s     2.4 s 119.0%    F
    13    1.57633   1.136E-04 1.379E-04 (  944,  2)   1.027E-04 (  947,  0) 13:39:09   35.2 s     2.7 s  89.0%    F
    14    1.57618   9.594E-05 1.073E-04 (  870,238)   9.192E-05 (  947,  0) 13:39:12   37.8 s     2.6 s  85.7%    F
    15    1.57605   8.085E-05 9.629E-05 (  272,238)   8.180E-05 (  517,  0) 13:39:14   40.1 s     2.3 s 113.0%    F
 k-eff =       1.57604985     Time=    206.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.438
 Inscatter Source  :     0.231
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.083
 Total (per outer):      2.753

  Total iteration time breakdown (sec):
 Transport Sweeping:    36.570
 Inscatter Source  :     3.467
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.251
 Total Time        :    41.288

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.57496E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:42:00

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.57605   8.085E-05 8.146E-01 (  242,  2)   2.519E-03 (  581,  0) 13:42:03    2.6 s     2.6 s  88.0%    F
     2    1.57622   1.076E-04 7.854E-01 (   14,  2)   2.693E-04 (   14,  0) 13:42:06    5.3 s     2.6 s  88.3%    F
     3    1.57621   7.156E-06 3.863E-01 (   14,  2)   1.031E-04 (  944,  0) 13:42:08    8.0 s     2.7 s 134.0%    F
     4    1.57612   5.460E-05 1.842E-01 (  584,  2)   1.137E-04 (  242,  0) 13:42:11   10.5 s     2.6 s  85.3%    F
     5    1.57598   8.852E-05 7.908E-02 (  944,  2)   1.287E-04 (   14,  0) 13:42:14   13.2 s     2.7 s  90.7%    F
     6    1.57581   1.109E-04 3.451E-02 (  584,  2)   1.326E-04 (  584,  0) 13:42:16   16.0 s     2.7 s 136.0%    F
     7    1.57560   1.302E-04 1.480E-02 (  584,  2)   1.361E-04 (  944,  0) 13:42:19   18.5 s     2.6 s  86.0%    F
     8    1.57537   1.453E-04 6.202E-03 (  944,  2)   1.339E-04 (  944,  0) 13:42:22   21.1 s     2.6 s  86.7%    F
     9    1.57514   1.512E-04 2.600E-03 (  584,  2)   1.304E-04 (  947,  0) 13:42:24   23.8 s     2.6 s 131.5%    F
    10    1.57490   1.481E-04 1.090E-03 (  584,  3)   1.262E-04 (  517,  0) 13:42:27   26.4 s     2.6 s  86.0%    F
    11    1.57468   1.383E-04 4.690E-04 (  944,  3)   1.189E-04 (  947,  0) 13:42:29   28.5 s     2.2 s 108.5%    F
    12    1.57449   1.239E-04 2.190E-04 (  584,  3)   1.095E-04 (  517,  0) 13:42:31   30.5 s     2.0 s  98.5%    F
    13    1.57432   1.085E-04 1.211E-04 (  944,  3)   1.002E-04 (  947,  0) 13:42:33   32.8 s     2.3 s 115.0%    F
    14    1.57417   9.225E-05 1.042E-04 (  272,238)   9.010E-05 (  517,  0) 13:42:35   34.9 s     2.1 s 105.0%    F
    15    1.57405   8.112E-05 9.449E-05 (  870,238)   8.190E-05 (  947,  0) 13:42:37   36.2 s     1.3 s  67.5%    F
 k-eff =       1.57404612     Time=    252.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.193
 Inscatter Source  :     0.220
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.079
 Total (per outer):      2.491

  Total iteration time breakdown (sec):
 Transport Sweeping:    32.889
 Inscatter Source  :     3.302
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.180
 Total Time        :    37.371

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.57295E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:45:25

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.57405   8.112E-05 7.858E-01 (   14,  2)   2.584E-03 (  948,  0) 13:45:28    2.7 s     2.7 s  89.3%    F
     2    1.57425   1.279E-04 7.372E-01 (  242,  2)   3.109E-04 (  242,  0) 13:45:31    5.3 s     2.6 s  88.3%    F
     3    1.57426   7.112E-06 3.542E-01 (   14,  2)   9.267E-05 (  944,  0) 13:45:33    8.0 s     2.7 s 132.5%    F
     4    1.57419   4.386E-05 1.667E-01 (  944,  2)   1.074E-04 (  242,  0) 13:45:36   10.6 s     2.6 s  87.3%    F
     5    1.57406   7.979E-05 7.104E-02 (  584,  2)   1.206E-04 (  242,  0) 13:45:39   13.3 s     2.7 s  89.0%    F
     6    1.57390   1.038E-04 3.089E-02 (  584,  2)   1.299E-04 (  584,  0) 13:45:41   15.9 s     2.7 s 134.0%    F
     7    1.57371   1.209E-04 1.325E-02 (  584,  2)   1.318E-04 (  584,  0) 13:45:44   18.6 s     2.6 s  87.0%    F
     8    1.57350   1.361E-04 5.549E-03 (  944,  2)   1.305E-04 (  944,  0) 13:45:46   21.1 s     2.6 s 127.5%    F
     9    1.57327   1.433E-04 2.321E-03 (  584,  2)   1.266E-04 (  517,  0) 13:45:49   23.7 s     2.6 s  87.7%    F
    10    1.57305   1.415E-04 9.699E-04 (  944,  3)   1.230E-04 (  947,  0) 13:45:52   26.3 s     2.6 s  86.0%    F
    11    1.57284   1.330E-04 4.152E-04 (  944,  3)   1.163E-04 (  517,  0) 13:45:54   28.9 s     2.6 s 128.0%    F
    12    1.57265   1.204E-04 1.934E-04 (  584,  3)   1.080E-04 (  517,  0) 13:45:56   30.8 s     1.9 s  94.5%    F
    13    1.57248   1.057E-04 1.119E-04 (  870,238)   9.872E-05 (  947,  0) 13:45:58   32.9 s     2.1 s 106.0%    F
    14    1.57234   9.071E-05 1.028E-04 (  870,238)   8.951E-05 (  517,  0) 13:46:00   34.3 s     1.4 s  69.0%    F
 k-eff =       1.57234076     Time=    297.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.220
 Inscatter Source  :     0.225
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.086
 Total (per outer):      2.530

  Total iteration time breakdown (sec):
 Transport Sweeping:    31.075
 Inscatter Source  :     3.149
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.200
 Total Time        :    35.424

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.57110E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:48:46

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.57234   9.071E-05 1.000E+00 (    1,  1)   2.654E-03 (  581,  0) 13:48:49    2.7 s     2.7 s  89.3%    F
     2    1.57255   1.340E-04 1.110E+00 (  242,  1)   3.308E-04 (   14,  0) 13:48:52    5.4 s     2.7 s  89.7%    F
     3    1.57257   9.357E-06 7.116E-01 (   14,  1)   9.306E-05 (  944,  0) 13:48:54    8.0 s     2.7 s 133.0%    F
     4    1.57250   4.350E-05 4.086E-01 (  584,  1)   1.086E-04 (  242,  0) 13:48:57   10.7 s     2.7 s  88.3%    F
     5    1.57237   8.056E-05 2.034E-01 (  584,  1)   1.230E-04 (  242,  0) 13:49:00   13.4 s     2.7 s  89.3%    F
     6    1.57221   1.056E-04 9.702E-02 (  944,  1)   1.329E-04 (  944,  0) 13:49:02   16.1 s     2.7 s 136.0%    F
     7    1.57201   1.242E-04 4.413E-02 (  584,  1)   1.347E-04 (  584,  0) 13:49:05   18.7 s     2.6 s  88.3%    F
     8    1.57179   1.405E-04 1.945E-02 (  584,  1)   1.335E-04 (  944,  0) 13:49:08   21.4 s     2.6 s  87.3%    F
     9    1.57156   1.482E-04 8.527E-03 (  944,  1)   1.293E-04 (  517,  0) 13:49:10   24.0 s     2.6 s 132.5%    F
    10    1.57133   1.465E-04 3.722E-03 (  944,  1)   1.257E-04 (  517,  0) 13:49:13   26.6 s     2.6 s  87.0%    F
    11    1.57111   1.378E-04 1.631E-03 (  584,  1)   1.189E-04 (  947,  0) 13:49:16   29.2 s     2.6 s  87.0%    F
    12    1.57091   1.246E-04 7.324E-04 (  584,  1)   1.103E-04 (  947,  0) 13:49:18   31.2 s     2.0 s  98.0%    F
    13    1.57074   1.095E-04 3.484E-04 (  944,  1)   1.009E-04 (  517,  0) 13:49:20   33.4 s     2.3 s 113.0%    F
    14    1.57059   9.353E-05 1.852E-04 (  584,  1)   9.096E-05 (  947,  0) 13:49:21   34.9 s     1.5 s 148.0%    F
 k-eff =       1.57059499     Time=    343.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.266
 Inscatter Source  :     0.228
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.085
 Total (per outer):      2.580

  Total iteration time breakdown (sec):
 Transport Sweeping:    31.723
 Inscatter Source  :     3.198
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.195
 Total Time        :    36.116

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56936E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:52:10

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.57059   9.353E-05 7.295E-01 (  242,  2)   2.717E-03 (  948,  0) 13:52:13    2.7 s     2.7 s  89.7%    F
     2    1.57082   1.421E-04 6.454E-01 (  242,  2)   3.484E-04 (  242,  0) 13:52:16    5.4 s     2.7 s  90.0%    F
     3    1.57084   1.548E-05 2.995E-01 (   14,  2)   9.076E-05 (  584,  0) 13:52:19    8.1 s     2.7 s  90.0%    F
     4    1.57078   3.972E-05 1.387E-01 (  944,  2)   1.067E-04 (  242,  0) 13:52:21   10.7 s     2.6 s 132.5%    F
     5    1.57066   7.827E-05 5.913E-02 (  944,  1)   1.184E-04 (   14,  0) 13:52:24   13.4 s     2.6 s  87.0%    F
     6    1.57049   1.041E-04 2.640E-02 (  944,  1)   1.350E-04 (   14,  0) 13:52:27   16.2 s     2.8 s  94.0%    F
     7    1.57030   1.227E-04 1.162E-02 (  944,  1)   1.345E-04 (  584,  0) 13:52:29   18.9 s     2.7 s 135.5%    F
     8    1.57008   1.398E-04 5.006E-03 (  584,  1)   1.341E-04 (  944,  0) 13:52:32   21.5 s     2.6 s  86.0%    F
     9    1.56985   1.483E-04 2.141E-03 (  584,  1)   1.297E-04 (  947,  0) 13:52:35   24.1 s     2.7 s  88.7%    F
    10    1.56962   1.473E-04 9.107E-04 (  944,  1)   1.263E-04 (  517,  0) 13:52:37   26.7 s     2.6 s 130.5%    F
    11    1.56940   1.389E-04 3.961E-04 (  584,  1)   1.197E-04 (  947,  0) 13:52:40   29.3 s     2.6 s  86.3%    F
    12    1.56920   1.259E-04 1.894E-04 (  944,  1)   1.111E-04 (  517,  0) 13:52:42   31.3 s     2.0 s 100.5%    F
    13    1.56903   1.108E-04 1.152E-04 (  272,238)   1.016E-04 (  947,  0) 13:52:44   33.6 s     2.3 s 114.5%    F
    14    1.56888   9.465E-05 1.056E-04 (  272,238)   9.161E-05 (  947,  0) 13:52:47   36.1 s     2.5 s  83.0%    F
 k-eff =       1.56887963     Time=    388.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.342
 Inscatter Source  :     0.235
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.085
 Total (per outer):      2.662

  Total iteration time breakdown (sec):
 Transport Sweeping:    32.790
 Inscatter Source  :     3.285
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.195
 Total Time        :    37.270

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56762E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:55:36

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56888   9.465E-05 7.037E-01 (   14,  2)   2.776E-03 (  948,  0) 13:55:39    2.8 s     2.8 s  92.7%    F
     2    1.56911   1.494E-04 6.087E-01 (   14,  2)   3.625E-04 (  242,  0) 13:55:41    5.5 s     2.7 s 134.0%    F
     3    1.56915   2.103E-05 2.778E-01 (   14,  2)   8.723E-05 (  944,  0) 13:55:44    8.1 s     2.6 s  88.3%    F
     4    1.56909   3.681E-05 1.275E-01 (  584,  2)   1.063E-04 (   14,  0) 13:55:47   10.8 s     2.7 s  89.0%    F
     5    1.56897   7.628E-05 5.487E-02 (  584,  1)   1.206E-04 (  242,  0) 13:55:49   13.4 s     2.6 s 130.5%    F
     6    1.56881   1.033E-04 2.445E-02 (  944,  1)   1.331E-04 (  584,  0) 13:55:52   16.1 s     2.7 s  89.7%    F
     7    1.56862   1.223E-04 1.076E-02 (  944,  1)   1.353E-04 (  584,  0) 13:55:55   18.8 s     2.7 s  90.0%    F
     8    1.56840   1.402E-04 4.625E-03 (  584,  1)   1.352E-04 (  944,  0) 13:55:57   21.4 s     2.6 s 128.5%    F
     9    1.56816   1.496E-04 1.971E-03 (  944,  1)   1.306E-04 (  517,  0) 13:56:00   24.0 s     2.6 s  88.0%    F
    10    1.56793   1.492E-04 8.338E-04 (  584,  1)   1.275E-04 (  517,  0) 13:56:02   26.6 s     2.6 s 130.5%    F
    11    1.56771   1.411E-04 3.608E-04 (  584,  1)   1.210E-04 (  517,  0) 13:56:05   29.1 s     2.5 s  83.3%    F
    12    1.56751   1.277E-04 1.734E-04 (  944,  1)   1.120E-04 (  947,  0) 13:56:07   31.1 s     2.0 s 102.5%    F
    13    1.56733   1.125E-04 1.163E-04 (  272,238)   1.027E-04 (  947,  0) 13:56:09   33.5 s     2.3 s 116.0%    F
    14    1.56718   9.619E-05 1.067E-04 (  870,238)   9.249E-05 (  517,  0) 13:56:12   36.0 s     2.5 s  82.7%    F
 k-eff =       1.56717871     Time=    434.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.340
 Inscatter Source  :     0.225
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.085
 Total (per outer):      2.651

  Total iteration time breakdown (sec):
 Transport Sweeping:    32.765
 Inscatter Source  :     3.151
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.195
 Total Time        :    37.111

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56593E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 13:59:03

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56718   9.619E-05 6.790E-01 (  242,  2)   2.834E-03 (  581,  0) 13:59:06    2.6 s     2.6 s  87.7%    F
     2    1.56742   1.546E-04 5.752E-01 (   14,  2)   3.738E-04 (   14,  0) 13:59:08    5.3 s     2.7 s 133.5%    F
     3    1.56746   2.504E-05 2.585E-01 (   14,  2)   8.499E-05 (  944,  0) 13:59:11    8.0 s     2.7 s  89.0%    F
     4    1.56741   3.475E-05 1.177E-01 (  584,  2)   1.055E-04 (  242,  0) 13:59:14   10.6 s     2.7 s  88.7%    F
     5    1.56729   7.523E-05 5.106E-02 (  584,  1)   1.224E-04 (  242,  0) 13:59:16   13.2 s     2.6 s 129.5%    F
     6    1.56713   1.031E-04 2.271E-02 (  944,  1)   1.328E-04 (  584,  0) 13:59:19   15.9 s     2.7 s  89.0%    F
     7    1.56693   1.226E-04 9.987E-03 (  584,  1)   1.363E-04 (  944,  0) 13:59:22   18.5 s     2.7 s  88.7%    F
     8    1.56671   1.412E-04 4.286E-03 (  944,  1)   1.364E-04 (  584,  0) 13:59:24   21.1 s     2.5 s 126.5%    F
     9    1.56648   1.512E-04 1.820E-03 (  944,  1)   1.316E-04 (  517,  0) 13:59:27   23.7 s     2.6 s  87.7%    F
    10    1.56624   1.512E-04 7.656E-04 (  584,  1)   1.287E-04 (  947,  0) 13:59:29   26.3 s     2.6 s 130.0%    F
    11    1.56602   1.432E-04 3.298E-04 (  584,  1)   1.222E-04 (  517,  0) 13:59:32   28.8 s     2.5 s  83.3%    F
    12    1.56581   1.298E-04 1.594E-04 (  944,  1)   1.132E-04 (  947,  0) 13:59:34   30.9 s     2.1 s 105.5%    F
    13    1.56563   1.144E-04 1.175E-04 (  870,238)   1.037E-04 (  517,  0) 13:59:36   33.3 s     2.4 s 117.5%    F
    14    1.56548   9.781E-05 1.078E-04 (  272,238)   9.341E-05 (  947,  0) 13:59:39   35.8 s     2.5 s  84.7%    F
 k-eff =       1.56547988     Time=    479.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.330
 Inscatter Source  :     0.224
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.085
 Total (per outer):      2.639

  Total iteration time breakdown (sec):
 Transport Sweeping:    32.624
 Inscatter Source  :     3.134
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.194
 Total Time        :    36.952

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56423E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 14:02:28

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56548   9.781E-05 6.556E-01 (  242,  2)   2.894E-03 (  948,  0) 14:02:30    2.6 s     2.6 s 132.0%    F
     2    1.56573   1.595E-04 5.445E-01 (  242,  2)   3.841E-04 (  242,  0) 14:02:33    5.3 s     2.7 s  88.7%    F
     3    1.56577   2.889E-05 2.414E-01 (   14,  2)   8.344E-05 (  944,  0) 14:02:36    7.9 s     2.6 s  88.0%    F
     4    1.56572   3.290E-05 1.100E-01 (  944,  1)   1.047E-04 (   14,  0) 14:02:38   10.6 s     2.7 s 133.0%    F
     5    1.56561   7.443E-05 4.764E-02 (  944,  1)   1.231E-04 (   14,  0) 14:02:41   13.2 s     2.6 s  86.0%    F
     6    1.56545   1.031E-04 2.116E-02 (  944,  1)   1.340E-04 (  944,  0) 14:02:44   15.8 s     2.7 s  88.7%    F
     7    1.56525   1.233E-04 9.297E-03 (  584,  1)   1.368E-04 (  584,  0) 14:02:46   18.5 s     2.7 s 133.5%    F
     8    1.56503   1.426E-04 3.982E-03 (  584,  1)   1.379E-04 (  584,  0) 14:02:49   21.1 s     2.5 s  85.0%    F
     9    1.56479   1.532E-04 1.684E-03 (  944,  1)   1.329E-04 (  944,  0) 14:02:51   23.7 s     2.6 s 132.0%    F
    10    1.56455   1.535E-04 7.040E-04 (  584,  1)   1.301E-04 (  517,  0) 14:02:54   26.3 s     2.6 s  87.0%    F
    11    1.56432   1.456E-04 3.019E-04 (  944,  1)   1.235E-04 (  947,  0) 14:02:57   28.8 s     2.5 s  84.0%    F
    12    1.56411   1.321E-04 1.468E-04 (  584,  1)   1.145E-04 (  517,  0) 14:02:59   31.0 s     2.2 s 108.0%    F
    13    1.56393   1.165E-04 1.188E-04 (  272,238)   1.049E-04 (  947,  0) 14:03:01   33.4 s     2.4 s 120.0%    F
    14    1.56378   9.964E-05 1.090E-04 (  870,238)   9.445E-05 (  517,  0) 14:03:04   35.9 s     2.5 s  85.0%    F
 k-eff =       1.56377689     Time=    525.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.339
 Inscatter Source  :     0.224
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.085
 Total (per outer):      2.648

  Total iteration time breakdown (sec):
 Transport Sweeping:    32.744
 Inscatter Source  :     3.139
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.194
 Total Time        :    37.077

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56250E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 14:05:55

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56378   9.964E-05 6.332E-01 (   14,  2)   2.950E-03 (  581,  0) 14:05:57    2.7 s     2.7 s 132.5%    F
     2    1.56403   1.635E-04 5.163E-01 (   14,  2)   3.928E-04 (   14,  0) 14:06:00    5.3 s     2.7 s  88.3%    F
     3    1.56408   3.199E-05 2.260E-01 (   14,  2)   8.263E-05 (  584,  0) 14:06:03    7.9 s     2.6 s  88.0%    F
     4    1.56403   3.153E-05 1.031E-01 (  944,  1)   1.048E-04 (   14,  0) 14:06:05   10.6 s     2.7 s 134.0%    F
     5    1.56392   7.407E-05 4.456E-02 (  944,  1)   1.213E-04 (   14,  0) 14:06:08   13.2 s     2.6 s  86.0%    F
     6    1.56376   1.036E-04 1.976E-02 (  584,  1)   1.365E-04 (  242,  0) 14:06:11   15.9 s     2.7 s  89.7%    F
     7    1.56356   1.243E-04 8.676E-03 (  584,  1)   1.383E-04 (  944,  0) 14:06:13   18.6 s     2.7 s 135.0%    F
     8    1.56334   1.443E-04 3.708E-03 (  944,  1)   1.393E-04 (  584,  0) 14:06:16   21.2 s     2.6 s  86.0%    F
     9    1.56309   1.554E-04 1.562E-03 (  944,  1)   1.344E-04 (  944,  0) 14:06:19   23.9 s     2.7 s  89.3%    F
    10    1.56285   1.560E-04 6.488E-04 (  944,  1)   1.314E-04 (  517,  0) 14:06:21   26.5 s     2.6 s 132.0%    F
    11    1.56262   1.481E-04 2.769E-04 (  584,  1)   1.249E-04 (  947,  0) 14:06:24   29.0 s     2.5 s  84.0%    F
    12    1.56241   1.344E-04 1.355E-04 (  944,  1)   1.158E-04 (  517,  0) 14:06:26   31.2 s     2.2 s 109.5%    F
    13    1.56222   1.185E-04 1.201E-04 (  272,238)   1.060E-04 (  947,  0) 14:06:28   33.6 s     2.4 s 122.0%    F
    14    1.56206   1.014E-04 1.102E-04 (  870,238)   9.544E-05 (  517,  0) 14:06:31   36.3 s     2.6 s  87.3%    F
    15    1.56193   8.502E-05 9.976E-05 (  272,238)   8.544E-05 (  947,  0) 14:06:33   38.4 s     2.1 s 106.0%    F
 k-eff =       1.56193119     Time=    570.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.328
 Inscatter Source  :     0.229
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.079
 Total (per outer):      2.636

  Total iteration time breakdown (sec):
 Transport Sweeping:    34.917
 Inscatter Source  :     3.435
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.191
 Total Time        :    39.543

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.56078E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 14:09:27

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56193   8.502E-05 6.120E-01 (   14,  2)   3.002E-03 (  948,  0) 14:09:30    2.7 s     2.7 s  88.7%    F
     2    1.56220   1.752E-04 4.906E-01 (   14,  2)   4.091E-04 (  242,  0) 14:09:32    5.3 s     2.7 s 133.0%    F
     3    1.56227   4.434E-05 2.124E-01 (  242,  2)   7.472E-05 (  584,  0) 14:09:35    8.0 s     2.7 s  89.3%    F
     4    1.56224   2.399E-05 9.702E-02 (  944,  1)   9.939E-05 (  242,  0) 14:09:38   10.7 s     2.7 s  89.7%    F
 k-eff =       1.56223674     Time=    616.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.435
 Inscatter Source  :     0.229
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.289
 Total (per outer):      2.953

  Total iteration time breakdown (sec):
 Transport Sweeping:     9.739
 Inscatter Source  :     0.917
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.158
 Total Time        :    11.814

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.55903E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 14:12:30

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.56224   2.399E-05 5.699E-01 (   14,  2)   3.095E-03 (  584,  0) 14:12:33    2.6 s     2.6 s  88.0%    F
     2    1.56247   1.487E-04 4.734E-01 (   14,  2)   3.458E-04 (  242,  0) 14:12:35    5.3 s     2.6 s 131.5%    F
     3    1.56243   2.292E-05 2.041E-01 (   14,  2)   1.585E-04 (  944,  0) 14:12:38    7.9 s     2.7 s  88.7%    F
     4    1.56228   9.676E-05 9.409E-02 (  944,  1)   1.874E-04 (  242,  0) 14:12:41   10.5 s     2.6 s  86.7%    F
     5    1.56205   1.497E-04 4.056E-02 (  584,  1)   2.103E-04 (  242,  0) 14:12:43   13.2 s     2.6 s 132.0%    F
     6    1.56171   2.165E-04 1.776E-02 (  584,  1)   2.172E-04 (  584,  0) 14:12:46   15.8 s     2.6 s  86.7%    F
     7    1.56129   2.704E-04 7.559E-03 (  584,  1)   2.184E-04 (  944,  0) 14:12:48   18.4 s     2.7 s 133.0%    F
     8    1.56082   2.980E-04 3.111E-03 (  944,  1)   2.104E-04 (  944,  0) 14:12:51   21.1 s     2.7 s  89.0%    F
     9    1.56035   3.003E-04 1.270E-03 (  944,  1)   2.046E-04 (  947,  0) 14:12:54   23.7 s     2.6 s  88.0%    F
    10    1.55991   2.841E-04 5.323E-04 (  584,  1)   1.937E-04 (  517,  0) 14:12:56   26.2 s     2.4 s 122.0%    F
    11    1.55951   2.562E-04 2.560E-04 (  584,  1)   1.780E-04 (  947,  0) 14:12:59   28.8 s     2.7 s  88.7%    F
    12    1.55916   2.223E-04 1.853E-04 (  272,238)   1.596E-04 (  517,  0) 14:13:02   31.6 s     2.7 s  91.0%    F
    13    1.55887   1.868E-04 1.675E-04 (  870,238)   1.405E-04 (  947,  0) 14:13:04   34.2 s     2.6 s 131.0%    F
    14    1.55864   1.527E-04 1.484E-04 (  272,238)   1.218E-04 (  517,  0) 14:13:07   36.8 s     2.6 s  87.3%    F
    15    1.55845   1.219E-04 1.296E-04 (  242,  1)   1.045E-04 (  947,  0) 14:13:09   39.4 s     2.6 s 130.5%    F
    16    1.55830   9.528E-05 1.195E-04 (   14,  1)   8.915E-05 (  517,  0) 14:13:12   42.0 s     2.6 s  87.0%    F
    17    1.55818   7.466E-05 9.551E-05 (   14,  1)   7.583E-05 (  517,  0) 14:13:15   44.8 s     2.8 s  92.0%    F
 k-eff =       1.55818109     Time=    661.75d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.408
 Inscatter Source  :     0.224
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.069
 Total (per outer):      2.701

  Total iteration time breakdown (sec):
 Transport Sweeping:    40.933
 Inscatter Source  :     3.805
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.173
 Total Time        :    45.911

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.55728E+00
 Equivalent core height is infinite.
***Warning:            Only one temperature is on input bound-kernel library for nuclide   1001
                       Temperatures for mixture and kernel differ: mix tempr; kernel tempr=    922.0389  800.0000
MixMacros: MT 2022 greater than MT 2 for nuclide 46108.
 ===================================================================================================================================
   Outer iteration sweep begins 08/ 08/ 2019 at 14:16:05

  Outer   Eigenvalue Eigenvalue Max Flux   Max Flux     Max Fuel   Max Fuel     Wall   Elapsed   Iteration  CPU   Inners
 Iter. #              Delta      Delta   Location(r,g)   Delta   Location(r,g) Clock   CPU Time   CPU Time Usage Converged
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     1    1.55818   7.466E-05 5.728E-01 (   14,  2)   3.095E-03 (  948,  0) 14:16:08    2.7 s     2.7 s  88.7%    F
     2    1.55849   1.970E-04 4.452E-01 (   14,  2)   4.396E-04 (   14,  0) 14:16:11    5.3 s     2.6 s  88.0%    F
     3    1.55860   7.008E-05 1.894E-01 (   14,  1)   6.218E-05 (  361,  0) 14:16:13    8.0 s     2.7 s 133.0%    F
     4    1.55859   7.801E-06 8.644E-02 (  584,  1)   8.599E-05 (  242,  0) 14:16:16   10.7 s     2.7 s  90.7%    F
 k-eff =       1.55858515     Time=    707.25d Nominal conditions


  Time per Iteration (sec):
 Transport Sweeping:     2.430
 Inscatter Source  :     0.229
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     0.292
 Total (per outer):      2.951

  Total iteration time breakdown (sec):
 Transport Sweeping:     9.721
 Inscatter Source  :     0.915
 Coarse-Mesh Accel :     0.000
 Else (Convergence):     1.170
 Total Time        :    11.806

 Critical Spectra Calculated with the B1 Method
 Input buckling of  0.00000E+00 gives a corresponding k-eff of  1.55553E+00
 Equivalent core height is infinite.
cp /tmp/scale.ybb.57441/StdCmpMix00001 /home/ybb/SCALE_beta/MSRE/MSRE_beta_60/MSRE_beta_60.stdcmp_m1
