SCALE Job started on Tue 20/08/2019 12:36:24
With Host name DESKTOP-KRG1AAR
working directory C:\Users\vicen\AppData\Local\Temp\scale.vicen.4876
and process id 4876.
Input file named C:\Users\vicen\Desktop\SCALE_beta_solid_par\ORIGEN_Testing\origen.inp
and output file named C:\Users\vicen\Desktop\SCALE_beta_solid_par\ORIGEN_Testing\origen.out
##########################################################
copy /Y C:\Users\vicen\Desktop\SCALE_beta_solid_par\ORIGEN_Testing\MSDR_burnup.f33cmb msr.f33cmb
  Now executing origen.exe                      
