cd /home/ybb/SCALE_beta/MSBR_2Y/MSBR_beta_10/
qsub MSBR_10.pbs

cd /home/ybb/SCALE_beta/MSBR_2Y/MSBR_beta_10_B/
qsub MSBR_10.pbs

cd /home/ybb/SCALE_beta/Parametric/MSBR/MSBR_beta_1/
qsub MSBR_1.pbs

cd /home/ybb/SCALE_beta/Parametric/MSBR/MSBR_beta_2/
qsub MSBR_2.pbs

cd /home/ybb/SCALE_beta/Parametric/MSBR/MSBR_beta_4/
qsub MSBR_4.pbs

cd /home/ybb/SCALE_beta/Parametric/MSBR/MSBR_beta_8/
qsub MSBR_8.pbs

cd /home/ybb/SCALE_beta/Parametric/MSBR/MSBR_beta_16/
qsub MSBR_16.pbs

cd /home/ybb/SCALE_beta/Parametric/MSRE/MSRE_beta_1/
qsub MSRE_1.pbs

cd /home/ybb/SCALE_beta/Parametric/MSRE/MSRE_beta_2/
qsub MSRE_2.pbs

cd /home/ybb/SCALE_beta/Parametric/MSRE/MSRE_beta_4/
qsub MSRE_4.pbs

cd /home/ybb/SCALE_beta/Parametric/MSRE/MSRE_beta_8/
qsub MSRE_8.pbs

cd /home/ybb/SCALE_beta/Parametric/MSRE/MSRE_beta_16/
qsub MSRE_16.pbs

cd /home/ybb/SCALE_beta/Parametric/MSDR/MSDR_beta_1/
qsub MSDR_1.pbs

cd /home/ybb/SCALE_beta/Parametric/MSDR/MSDR_beta_2/
qsub MSDR_2.pbs

cd /home/ybb/SCALE_beta/Parametric/MSDR/MSDR_beta_4/
qsub MSDR_4.pbs

cd /home/ybb/SCALE_beta/Parametric/MSDR/MSDR_beta_8/
qsub MSDR_8.pbs

cd /home/ybb/SCALE_beta/Parametric/MSDR/MSDR_beta_16/
qsub MSDR_16.pbs

cd /home/ybb/SCALE_beta/MSBR/MSBR_beta_100/
qsub MSBR_100.pbs

cd /home/ybb/SCALE_beta/MSBR/MSBR_beta_80/
qsub MSBR_80.pbs

cd /home/ybb/SCALE_beta/MSBR/MSBR_beta_60/
qsub MSBR_60.pbs

cd /home/ybb/SCALE_beta/MSBR/MSBR_beta_40/
qsub MSBR_40.pbs

cd /home/ybb/SCALE_beta/MSBR/MSBR_beta_20/
qsub MSBR_20.pbs

cd /home/ybb/SCALE_beta/MSBR/MSBR_beta_15/
qsub MSBR_15.pbs

cd /home/ybb/SCALE_beta/MSBR/MSBR_beta_12/
qsub MSBR_12.pbs

cd /home/ybb/SCALE_beta/MSBR/MSBR_beta_10/
qsub MSBR_10.pbs

cd /home/ybb/SCALE_beta/MSBR/MSBR_beta_5/
qsub MSBR_5.pbs

cd /home/ybb/SCALE_beta/MSBR/MSBR_beta_0/
qsub MSBR_0.pbs

cd /home/ybb/SCALE_beta/MSRE/MSRE_beta_100/
qsub MSRE_100.pbs

cd /home/ybb/SCALE_beta/MSRE/MSRE_beta_80/
qsub MSRE_80.pbs

cd /home/ybb/SCALE_beta/MSRE/MSRE_beta_60/
qsub MSRE_60.pbs

cd /home/ybb/SCALE_beta/MSRE/MSRE_beta_40/
qsub MSRE_40.pbs

cd /home/ybb/SCALE_beta/MSRE/MSRE_beta_20/
qsub MSRE_20.pbs

cd /home/ybb/SCALE_beta/MSRE/MSRE_beta_15/
qsub MSRE_15.pbs

cd /home/ybb/SCALE_beta/MSRE/MSRE_beta_12/
qsub MSRE_12.pbs

cd /home/ybb/SCALE_beta/MSRE/MSRE_beta_10/
qsub MSRE_10.pbs

cd /home/ybb/SCALE_beta/MSRE/MSRE_beta_5/
qsub MSRE_5.pbs

cd /home/ybb/SCALE_beta/MSRE/MSRE_beta_0/
qsub MSRE_0.pbs

cd /home/ybb/SCALE_beta/MSDR/MSDR_beta_100/
qsub MSDR_100.pbs

cd /home/ybb/SCALE_beta/MSDR/MSDR_beta_80/
qsub MSDR_80.pbs

cd /home/ybb/SCALE_beta/MSDR/MSDR_beta_60/
qsub MSDR_60.pbs

cd /home/ybb/SCALE_beta/MSDR/MSDR_beta_40/
qsub MSDR_40.pbs

cd /home/ybb/SCALE_beta/MSDR/MSDR_beta_20/
qsub MSDR_20.pbs

cd /home/ybb/SCALE_beta/MSDR/MSDR_beta_15/
qsub MSDR_15.pbs

cd /home/ybb/SCALE_beta/MSDR/MSDR_beta_12/
qsub MSDR_12.pbs

cd /home/ybb/SCALE_beta/MSDR/MSDR_beta_10/
qsub MSDR_10.pbs

cd /home/ybb/SCALE_beta/MSDR/MSDR_beta_5/
qsub MSDR_5.pbs

cd /home/ybb/SCALE_beta/MSDR/MSDR_beta_0/
qsub MSDR_0.pbs

cd /home/ybb/SCALE_beta/MSRE_HEU/MSRE_beta_100/
qsub MSRE_100.pbs

cd /home/ybb/SCALE_beta/MSRE_HEU/MSRE_beta_80/
qsub MSRE_80.pbs

cd /home/ybb/SCALE_beta/MSRE_HEU/MSRE_beta_60/
qsub MSRE_60.pbs

cd /home/ybb/SCALE_beta/MSRE_HEU/MSRE_beta_40/
qsub MSRE_40.pbs

cd /home/ybb/SCALE_beta/MSRE_HEU/MSRE_beta_20/
qsub MSRE_20.pbs

cd /home/ybb/SCALE_beta/MSRE_HEU/MSRE_beta_15/
qsub MSRE_15.pbs

cd /home/ybb/SCALE_beta/MSRE_HEU/MSRE_beta_12/
qsub MSRE_12.pbs

cd /home/ybb/SCALE_beta/MSRE_HEU/MSRE_beta_10/
qsub MSRE_10.pbs

cd /home/ybb/SCALE_beta/MSRE_HEU/MSRE_beta_5/
qsub MSRE_5.pbs

cd /home/ybb/SCALE_beta/MSRE_HEU/MSRE_beta_0/
qsub MSRE_0.pbs

cd /home/ybb/SCALE_beta/MSBR_N/MSBR_beta_100/
qsub MSBR_100.pbs

cd /home/ybb/SCALE_beta/MSBR_N/MSBR_beta_80/
qsub MSBR_80.pbs

cd /home/ybb/SCALE_beta/MSBR_N/MSBR_beta_60/
qsub MSBR_60.pbs

cd /home/ybb/SCALE_beta/MSBR_N/MSBR_beta_40/
qsub MSBR_40.pbs

cd /home/ybb/SCALE_beta/MSBR_N/MSBR_beta_20/
qsub MSBR_20.pbs

cd /home/ybb/SCALE_beta/MSBR_N/MSBR_beta_15/
qsub MSBR_15.pbs

cd /home/ybb/SCALE_beta/MSBR_N/MSBR_beta_12/
qsub MSBR_12.pbs

cd /home/ybb/SCALE_beta/MSBR_N/MSBR_beta_10/
qsub MSBR_10.pbs

cd /home/ybb/SCALE_beta/MSBR_N/MSBR_beta_5/
qsub MSBR_5.pbs

cd /home/ybb/SCALE_beta/MSBR_N/MSBR_beta_0/
qsub MSBR_0.pbs

cd /home/ybb/SCALE_beta/Poison/MSBR/MSBR_beta_4/
qsub MSBR_4.pbs

cd /home/ybb/SCALE_beta/Poison/MSBR/MSBR_beta_3/
qsub MSBR_3.pbs

cd /home/ybb/SCALE_beta/Poison/MSBR/MSBR_beta_2/
qsub MSBR_2.pbs

cd /home/ybb/SCALE_beta/Poison/MSBR/MSBR_beta_1/
qsub MSBR_1.pbs

cd /home/ybb/SCALE_beta/Poison/MSBR/MSBR_beta_0.5/
qsub MSBR_0.5.pbs

cd /home/ybb/SCALE_beta/Poison/MSBR/MSBR_beta_0.25/
qsub MSBR_0.25.pbs

cd /home/ybb/SCALE_beta/Poison/MSRE/MSRE_beta_4/
qsub MSRE_4.pbs

cd /home/ybb/SCALE_beta/Poison/MSRE/MSRE_beta_3/
qsub MSRE_3.pbs

cd /home/ybb/SCALE_beta/Poison/MSRE/MSRE_beta_2/
qsub MSRE_2.pbs

cd /home/ybb/SCALE_beta/Poison/MSRE/MSRE_beta_1/
qsub MSRE_1.pbs

cd /home/ybb/SCALE_beta/Poison/MSRE/MSRE_beta_0.5/
qsub MSRE_0.5.pbs

cd /home/ybb/SCALE_beta/Poison/MSRE/MSRE_beta_0.25/
qsub MSRE_0.25.pbs

cd /home/ybb/SCALE_beta/Poison/MSDR/MSDR_beta_4/
qsub MSDR_4.pbs

cd /home/ybb/SCALE_beta/Poison/MSDR/MSDR_beta_3/
qsub MSDR_3.pbs

cd /home/ybb/SCALE_beta/Poison/MSDR/MSDR_beta_2/
qsub MSDR_2.pbs

cd /home/ybb/SCALE_beta/Poison/MSDR/MSDR_beta_1/
qsub MSDR_1.pbs

cd /home/ybb/SCALE_beta/Poison/MSDR/MSDR_beta_0.5/
qsub MSDR_0.5.pbs

cd /home/ybb/SCALE_beta/Poison/MSDR/MSDR_beta_0.25/
qsub MSDR_0.25.pbs

